ansible_become_pass: ENC[AES256_GCM,data:U0B68AciQIBgYXwnmg+iHBLx3A==,iv:1rZ6eKHK6fEDmsZ6RATOzQIrK+f6hTpBqjq03fP1Wl8=,tag:L77SQfztsv4N9BxnnYgxAA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbFZnQWVDZ1plWWtKMk5n
            ZjViZnZoQlBZM1VxUGNTZ1VrRnNkMDgya3dBCmMwU2R5WUsvSHNXZzlUVjFUc0VW
            azh2VGRQcGI0cUQwZkpURC81bFdDQjAKLS0tIFVuOGU2OWsrdWpwTytJVTFiemlk
            UTJFZ2JzWTNzRjAwVXhmY2pvZUpQNHMKeJNa3PRJpvfMllx143oTjpfmEHfnOU+g
            aRjaCrFW2452Pcbd9fPPXyAjLbYvA4x4fARQaQtQNIuA6c/4DpgcQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:08:13Z"
    mac: ENC[AES256_GCM,data:4g0PEw4boPi6Ep1tV/wmN6yyl/91L9/mtkMTBFUkGgjP1BT5XP/1z4jJmLyw/YO3pEoVVpR9qc9YhCwtnh7bcqxKbR9sW950u8pOOjoSCO0WNV7Mqaf+iPbip9OTlYMIgRqBSw52exxGcSl0R5NQVyLF4y66Px9+GQ0jwfYsGGI=,iv:aK3z/NJ+bajZ8qvWHoRdea1rT/Ax5XzkGHiBPKhdnj8=,tag:k9yfUyGjIjCaP2vvuPSCrA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
