ansible_become_pass: ENC[AES256_GCM,data:6y4tQptz1EvhpxZNJuE0FW0RUA==,iv:ruhIRMqZfZOXyPmORu4r9nBHRX0WTdaC19NCYvjXsCU=,tag:7+a/6bDfeP6O098zEb4kGg==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYnFvYkJYVXgxNmFyeTBC
            SVRoazROamx1eXJoQzBGWWtDeWRpNW05c2kwCjJQOVFEeHg5byswZ3liS0R4cjJX
            MXdnZlRwZzBIc1lURXBvQkpBZ3lqdW8KLS0tIEtxcXpDbGtXdkorMkl2R2d3ODl0
            UUxMVVNqS1BlaFQzMXN4aXlvNzB4NTQKclUrB3jVivOKfbKD7v9SYn33INgGnyZY
            yEJ+lrTrCy+X96qbYHopJqaSI4j2sUNidJWrNbgyWCpYTxFB95bgow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:23:57Z"
    mac: ENC[AES256_GCM,data:6j6GWc/ExDfbtMCowMXlzV43VnnXI4E8l0btOeyuLeu6L6nGDNlzmoK6IOwAjNFQ65lyTjRYFFhp/eV3kptEuWfdLsqwMPI88FVwGEGKCja8GivUhxDAzDvWGsEpI/tbRn4C/atX2VdKgepNG92a51KZgE3nP//JNF/SHck1Jkg=,iv:tGtIBA8kbuyc3bxc1nUJL2pAfnqeww68aN3i/sTKmlc=,tag:7AGWUv9Wa/+1PygPOKnYdQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
