ansible_become_pass: ENC[AES256_GCM,data:NSmXO7fQAS2Ts9edeXJi3sS9pQ==,iv:eqw0N21T0CRLxeL3wVt7RO/oGo/KMq6peKFpvR8/yYA=,tag:70AxW1OJhX1TXfwP2R1FZg==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MnhGeUlKaWV5YmtqT21W
            OUhJRHQ1OHRFTHRwSElZb0NJWmFSOUMzUFg4CmYvbGY5UDlZUzVYc3JyQ0tJSjNY
            NVh4azhQbERYVndkS0k5dVgrZkZUdG8KLS0tIGUyRlFMN21WL1prZXRFeFV5VFRC
            dGQ1TGZicGsxbVd5aWdYTkxhbStVU1UKmnzauOzJUgHIowBWIk/Ibc3vdnAW+lZk
            iZtS3hZstU4YyDi+sZguC36379yp5thVn1QOlIRFMy20aKBHkamP3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:45:46Z"
    mac: ENC[AES256_GCM,data:aycf3TegkIrcCqMTKAiapiiizSNxoDdC5Ge8vSK7teBJ2AJ2+Ej91kgFnktkeJ5aceZldLa2oXxn3degOt4r6L1uYNhMd4vsCCysY77sJ58AaYEc+SnTnrJBgG45W/IwtPu2AfPoyBitgmmbwoo01+P3DQuVvlTIjisT3JIy+rE=,iv:KShZjZzOHwgJLjc+xL7cgE9I66AWS5tdjuHQvAXufJU=,tag:jyCStETwNiE2GsIqkvclGg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
