ansible_become_pass: ENC[AES256_GCM,data:uByYmFz17I2VJb900GOOWaNQsw==,iv:wlneSpCb6dQ/ZR9IVJTAcCankHwkEpj7dk5rC+V2eVs=,tag:iXiZivuNWKZKDhQxquNiwQ==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNzcrK1pvQXVSRHVxTEpk
            dFIvN2c1b2xrUnl0Qm1iekl0aXo3cjUxZEZjCkFpM215UkdLUkxTRUJOc2VGcWhB
            VHAxRmpocVZZYjk3UEpzNlE4Z05YSUEKLS0tIFRHaVZVaks5dzNsNC9wcUJFYjVY
            S1Zpdjc0djRBWFBUOEVPQjdlRTF5WTQKdWppG/BTm45jhfb6EcsVFLIsXrm7ikVZ
            T67ZfVVR/xHfL+KLkAOEUybFjPw8JbEsNwoMf/YPKaOQ9HNuyVr6aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:02:35Z"
    mac: ENC[AES256_GCM,data:HT0/lSRPGtv8BLzV1M1VonBXZLCWThLlrkJEc3tk+43qf41p79SDCGryqks08Gl24pLjxEV3CnxYxern4VsRsjIk+uYl4fxqbaQffgvqHsVWEFJaER0LDPLHRxXPpvyYC4qeaLUzRSuoUxpgPZJW0Asf1IXQQLlRA6URPqA83SA=,iv:CbUbD11HdO6RCuUy1frVx+n8eO9+YaCRbs7hx3U8VoI=,tag:XEP5r2tFE6g6SGF3T5/c0w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
