ansible_become_pass: ENC[AES256_GCM,data:QFOiZmlvrnc7DSiFvtM/0/1/pw==,iv:78mt9MRJUm7inVmNjFaxSWK9K/jVP/QbrtVyqcp4Z1o=,tag:lqLTXWRqhGEEOuH4p81BYw==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRXcrdjROb2Zac3FpbzNK
            MDNjUjNkbW8yTmZkUStxbllLL2NYdWI0bFRVCkhrM2k1VVY1MzlIMHpNVDhNS0hx
            dWRHa1ZyMmFKVXlxbWJIYmNVc1VsbWsKLS0tIFc4ZmV3clZoVlRkbndFVS8xczFH
            TC9aVDUyelludERZOWk0MFB4Ulp4TUUKW9JhsS2JcXM3g6D8yjFrcZVdOxgn4LpR
            t6GfYx/dM68kRreXZ765BfjLGhQ6Y3yIFLjdgAJzaoDWEQm/SamGIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:19:23Z"
    mac: ENC[AES256_GCM,data:ONAqddygghVP+1MegA49z7PqgbIO/kDzgfuc4a0fVVN9A+kVpinyxl6yiGzqZPvpOhkCHH2UmKkmv7gahVaDTIc3eRiUbYNpdrJUiJ7IHbDYh1O4XawA8cF6egysW/hh/vN713/4w3Oy2lRNMsiJmS/ktPRsGDKdwig2h0VmKW4=,iv:/COJfiibygOtqyDSYtXh/IeoLAt88swfZygeBz1ejKw=,tag:T1DOSCi4s7Toos6/HftAnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
