ansible_become_pass: ENC[AES256_GCM,data:UIR+RwDnUD6xJ+9z9VxEN9lkug==,iv:pTMGBaMAZJ0rN4xSGgyNfnXh+R13IDvjttaGEsPpOzo=,tag:quChxcB1jtM2v5yyBSc/gA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWnN2ankzNXdsWFZ3Z05s
            N21uQXVuM2pkNHdiZi9RaTVBbXBjZi9FNGhNCklPWHp0ZXFrNkZoL0dIUHhZVzVS
            V1BsZjRPdnhad0h0T1JDcDJWOWFlNUEKLS0tIDJTVlZ1NURyTmJ4QnRvL0FsdVU1
            TCtMUjAxL245bEtRcUlFZjQxSXBOczAKxxWwfsv/6i8yeQQCjHWEkhLw+VN6dqR2
            l+lJ0DNG/WL9NFWY0m9TE/oC2JJozhiV3nucoHdG4DTlzuP08sQjdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:16:17Z"
    mac: ENC[AES256_GCM,data:O9j/jNWu9mS6uI8JD4zYtCmAWFG7sg250ESE2yoxTyjmCRihuNoHUiDRrOwBKxRgOMbbNKISBUsnLM6viVFqb/t3aAeGdYSasGqA3nFDVV2pMLLusJ457Sq9awzY0JUSqoJVKYvFabkXWIT6JEH7UnUGjdp3XtnmFKK4CPOcsnQ=,iv:fQ9mOx+De0teJTgQhoJ2VZHrO7gjQHeAUtQwiFwg4SM=,tag:spnG2vGqB6ynNHH4KgQV2w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
