ansible_become_pass: ENC[AES256_GCM,data:HQwmZjhAd+i5ZgK+mzXAydIkaQ==,iv:hsgmH5jhcmjBXkUaD0Jf9OEJLcteR3lh7n/Wir4C2Do=,tag:eYGhGk1U7X8oqzFUqsEkdA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Sm15bDhReHZJS1lCMVJD
            SXBET050cGVqRHN1Mkc3REVoSm5nUUZsRUc4ClZnWlRaRzlGVkRtbU54TVp0RFEv
            RFRPOFZlZ0J3dlFpS1hqdjF3Q0NxQmsKLS0tIHAxYnlHWW9HN1F4b1RSdkt4TU1H
            TzNqbGFxTUs5ekMwK1l5Y1NHNXc0bEkKG7msVZ6ppDgKbShsB8oWnZdHoVFLocC/
            HxNRAnNBCG3PdMNheeaRagUKf8uiLNONoLbIhDyA7z+MXwe1uFRCQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:16:18Z"
    mac: ENC[AES256_GCM,data:78vIYvwArbiT7phgAB6EWRZBwtihUVVBYqs8svb76BMiXJ/+/pTN9l5zFkaH6YMuPhGV4ImUCsO2UCnc6KJDRvYevspEIThq9B3kUa4ko1dVUQzI5EGg26AHSW3DwNUkRZdxXm7qs634lHC/KDktNPenXhN0GMO0f7qF00Wq5EM=,iv:MdNQ0LeI3dr0zPo27RS/1VzraZlo3aWi2q5KJGnMC+k=,tag:PS0eveHssmiQJM3ic93fKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
