ansible_become_pass: ENC[AES256_GCM,data:n3aYryjuFUty3w/Mx4tGdBqDww==,iv:JbRPqdxf1IiSfOiEiAZyt9PaHyVFARaORzO4THRNUZs=,tag:3y8KntyQFR3p+fMm4kAZPw==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRk1BMlduSVZLZlY0NzZY
            UHFja3NXeU5ZdVlQeHVYS3ZuM0dmeFRJSmt3ClN3bFRNUlA5U3cyclB6ZUlPM05M
            a2JmY1RzT2ZQUStSSDdySUlQSHhTRGMKLS0tIEhkNGJnNERhTFFiaFRHWmJ1Z2ZU
            UElHcXZXdUtlSndrdS9OTjBlQ2NHa2cKDJvvbENqJyla2QDZMhY9Kdr/LnvJgO3r
            xjHHNdHuwpvaoLLzrfoJT0k0RXf7D1IQiCEx3Jsb6L4ZtXKScG2nfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:08:14Z"
    mac: ENC[AES256_GCM,data:UNzOL7oaPi77iDlY+8wCe9V2jm6o3VZw9fE4/D0rycEqHqSSqqwRl5x3qUg940mlrNNts7D97imif1itceC0vK069UnJNIWWJAVJGmYkq9kuTHkZMiZgEa/24Q8PgBBF6tu+6lOiavn2k9whRKtXEO8+F5L5c2kqGwqQddxALiQ=,iv:9xtqX+Vvfy/0NQbDVJSc/jfRGG/xjNGIRvS3hExUgfE=,tag:mqLCPt9a1ffJjo2+vf5S0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
