ansible_become_pass: ENC[AES256_GCM,data:8UvIHd/1r5Ebk4DhoCYtDShPDA==,iv:fJTO4l1lbWPlnKbLE6xZzKyBMsIdnXFnxGXVUUqWnMU=,tag:a5vBI8MM+NRRgwmWby7xQA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QnFHUUljQlVaeG9QV0xL
            UmtLTVlsV1BPeVdkRExNMnVVY3RRYTJCVnh3ClhPSWozdEkyNzBqbUNIUk1ydndu
            Q1luSGRjaFdRVnkrVXVER2JUbDhzSEUKLS0tIGtoSW5rV3hzT2p4cGtPN21IamNU
            WWp6dXhDTC9FY0luK1oyK0F0b0g5dkkKbaCgwZx//wtoZ6uiXzRT4D+KlTAcfB7b
            tW3IsbpfAyNcyUXkjSn6PaHrvWQZCC5aYjZJ7CKMZhvA/5hJOyx1uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:02:35Z"
    mac: ENC[AES256_GCM,data:oKzkQx1bU1Nie8FZ4IEF2C2A3yaE1hcbXxEUg1/23a8XcGe6mE7Ez+5jvp7l682KToMFanj1Cj5pStqTBmFBviSPGcH8kvnilknM4QpdqLw/JdBcOefLxYd5L6dNeWnpUfo6Yhpw4mOK2QoV42/Rqa4G4Rb5K10bUsgp9jkut3c=,iv:0vkwDN848luiVMAKhMF62nshfCDtBogjYDHEve2wWwo=,tag:EyUxjACCXJsVJeItE/bNpA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
