ansible_become_pass: ENC[AES256_GCM,data:vM4aCenQZfaUyBS7K2HWtWexaA==,iv:4Iv/R39wHBA67q1hZGyJ36YfDZPX9aU7DqsTcED64ms=,tag:Lx4VxykP1L+RyCdOGbBmRQ==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrS2FxaWdwaDcvSXpIcTZK
            OWJSVWRmNGF3bHE0dmhKaG9wQ1gyT3FONG5VCnVqcGxYT1hoMmRPejE4UjBMOUtl
            eTIyR09zTGRNdXpiN3YxSlNKQjNXalkKLS0tIGNtZDJNQ2ZReXpFVUd3WkRSUmRG
            RTdsbW42d0JuNlY2RzhTU3BhSGJldXMKwN/V+K4KUWSsNm4UNnPfUTof8ayTgpkA
            6kYBQW/Jn62bZBeUAdYkTa0xfT5FxuEILbKf1dqTmxw3J6GeiXKl4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:45:46Z"
    mac: ENC[AES256_GCM,data:3a198mvD/HRmKLv63JyoAYTBEn0WVO59uxXYWeaZGb5qVpfY2Tsm1x/uvkfqrLv39BErKoAQbHQeCFTGOedSQ6cfYiG3SxI5YamsHcq2FUL6hvLWJ0V+k8FnTDNlY3VpRE4zkYMGe6Yi8ChlHYP0xguCBXOvbMyv+AGWcKwJgCM=,iv:X7Wsd8tdfMkQBKu83/lnf95kbPF/RhZdR45dQIrLwZw=,tag:MRXjz3g8y3XIn5SG4huJOg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
