ansible_become_pass: ENC[AES256_GCM,data:EzsveD5lIJMWZcbdl/onSD24qQ==,iv:4YZ8gEPeg1/1EEOrc5tuMGHIERmoWitlar3MQ2n0XWY=,tag:XWfQqaFGNEww1hAg55gAxA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcFZMRTdwcC8wWGdXaEtK
            UlNXcFR2cktQU3d4KzRxQWt4dE5mcEM4U2xrCmhFYXp5Q09ERXlJSnp5TTdRZ0VX
            RXdnVWlOTzJLQm9xdDRSUm5lQUk5L0kKLS0tIHNNYXhvMUVYUlpSeVJVS0E1QWZu
            K1hCMllZendaS0s5ekt6RVdrRmRRSVEK2erlWPyP1HzYZcxcTzsNZIBdT9lWFwko
            QpCMFjgMPJgjz609EyFb7VHkBq7zbe+4G8OH6RLg7B8OVhRQl95gkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:19:23Z"
    mac: ENC[AES256_GCM,data:iqZlK2R95i3IbndiniPDboPfi64LhMGrblxlTXyg/UWBhxeTNIZ0ify1oeOAou9CIXoiylF3mDwtQCtSfj7tYCR6qPaOWZLYI/mbUnBSVOEcc6iFO3fOkT+90woJtzYJw0JZhDym6a0oQvYdTc52fiD5/CC/e+3opu47B4oMhM8=,iv:bbzzsFDfkFozmzA8dO46tWNRyaxnX52TfJx/Vf5H5Ms=,tag:ByZfx44mR29hsKcK9mga3w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
