ansible_become_pass: ENC[AES256_GCM,data:u2aaJV4U1uFeQNCQhAUY1K78Vg==,iv:SQk7alCsYspwMbTXiv45cYzqlN4zRAZD8cMNkiUcZeY=,tag:ZfooH1lRQyIByfWUekhqnA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMzl1ck51VTZGaFFkcEQw
            aVB6KzJ1RCtpMUZueWI4bmNSTVpwbThHZ1JNCkJMMU02WmpjNEpzaXppb3VCUXNV
            ckNOUGVRQ25QTmdGVEp0UFd5SkZwNUUKLS0tIFQvem8ybFlrQzlvU1RIZnRVaDZK
            K0pnL1B4b1hndG1Ocmw1d0NrQTVRbE0KSrQdJLvIL7UCyMEJl+3BgBrT44TSjZbn
            zojlsz0jL+q2vytjinvbjzKWzSH5Ub8JsgHiXt2gVAwwrKzcRs4/rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:23:58Z"
    mac: ENC[AES256_GCM,data:PkWTOgHcL/1qUopm6UZEiQahPUzE0cJsfbOEJaeG3V8AbBFJGgfVF09L8e1WCmu0NSrHCvU/COdLhHhizvdx4ACHd5vOBR+zD15tZjpVO7GY2BTu5ZcyFjFNoo7RXIkMivMsUtFnsgRjV1/SOg73bbQmES8FDNYkT2/CbExonDY=,iv:TbU//R0tnuqoVksJIh+H0eP3ologvx5dRBnhP0eX7TM=,tag:GPJnnXYHR1B1DfcA/Q3GKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
