---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./bjw-s-labs.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./democratic-csi.yaml
  - ./descheduler.yaml
  - ./docker-vernemq.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./grafana-community.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kerberos.yaml
  - ./metrics-server.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
