apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:6Pia2EhatnsFlxycJU63zEF/DSpjgBovrs9teF8j0JC05ddN,iv:xFdSeWUuO3jOKA57ieu+e5p8w+l5nRgCc07B7Lpyuxo=,tag:Gof5YsnLrlIdhKARQC5cyw==,type:str]
    credentials.json: ENC[AES256_GCM,data:Grf8X7u61LOR4YAQrXoZIrxD1oWtyUH8dsDlGja5yUJ1YCugOC1XY3XdYp6qg0lUeUSjmDoTqWjBpXvRcPYs/6Qe0TbDorl+67OVKL1aWBuJAQnWnLU0y0aquAlmgOoGbGKx8buKHcIOM7UiD5na/wwrnieLXagW048A5OHtaVSKUFMsz/tLmO5wglaDqPlpN30iwfk1Kn7ePEBuTwSWEkYi8oR7bSSl94CgtC3vVw==,iv:Y0NHWmmOhav/mKf1KY4YDRNA6pqRj3ljQAMnv8m6usk=,tag:0//Q4CqJV2j0Mak+BEbO4Q==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SnE4SXlpZnlYRDFDOXZ5
            WGtBeFBoblJVdnJSazdFY2t2OC8rZ0xneng4CmRteUVPMzdyRFhOME9kZlhTcGxG
            dnYzWStBalYvNno2cEt4UUV2WDBkWWMKLS0tIDhjeXgvazlvbFZUTzQ2Q2RoT09N
            N25GaGRMbWtmWU5XY1hYRHRlajduQ0UKH+EdVvJOh/+dPSpdLhyEMMspcb7dhdLJ
            c2Tr1pL3tNYCe2c/828pKFnvzsOSExyaXwRzoQSa8gU0HP+2Bc7yNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:04:13Z"
    mac: ENC[AES256_GCM,data:clUGfNru8fNT5o9F9ln8N95AGAZOJCD0J7NVK8YpyvluK+GnK8trs1ey5eIpPHG/e1eMuXSw1hyUns966oyfcL3vKafpsO80QW1wWbnlya1L6cjss8KNd9RcmseApT8N/o0isPq+IyeioDsRlBztKxdMO11JCL11HrBt4WvtQUk=,iv:RqdpAkjtVgErtuki7d/l3tJyVPvWsX6huEGNJxIxJ7k=,tag:0qMjXlSQZY1dIvsjEiV8zA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
