apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:X3IC9zTJjGPCpp2n0F7GuxFqoOhuVCz0hJFGXr870ymSveuv,iv:o2ILvSJ+bfLzIKfTB+9ltjpZP7iJrZBbl9DP1PHilcQ=,tag:bfzUyWar+dBT41gtJFkuhA==,type:str]
    credentials.json: ENC[AES256_GCM,data:AmBTOQ4GOM2G7Z3Ij3WYcEjv03jC5YwqoIIZkpvucz7clJyXrMSbpVML3V+VFvB/UaZLWIpkAFugy1MTNRd1lFBHvAkN00jY0Ye871q92I6miSsI8cYHig99zdKJIA3sVurLLVSv/oTm5RKx8llbwmmUtWdto42kh1OrCSHMwlkXLybWOFayW1HmRZHbiulZPqMjRwCBU7EVU/B+9kRZAKDHV8hYlqyfpbnytAmeJA==,iv:pqepsjuCJB5vDV2t9+CsiqPQCme2XKb6PQms7auOIYU=,tag:q9yoTM/r8XvsZLaWXkjRAw==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBta2tHcFgvbEhlLzZNdnYx
            cmVGTU1NY2dUbWJGdmt3WXBkZGhqQ2tUSG1jCkFxN2lLNS9Sd1FqMEZYWktsQ29t
            SEhxalNDQnBrall4ZnNCU3dZbktnZUUKLS0tIDlIeUw3ZnhrYnp2b1E0WmxrRDl3
            bTJyZ0ozUXhHZVZ5NnFJN0J6ckE0WVUK8t8c3w6RPszmcleOfxJYWHLMc88v3m1u
            Rg8JEQ21ZkK15l/LJtbl2Q+03fyaVC5+txLCUxHRkZ6hgQqLOhoI1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:25:41Z"
    mac: ENC[AES256_GCM,data:u7EzyBiPmhFn7cIxD1USVmn1hBI+GmqYXbZKhPtU9YBT/yCjeG1KnMCiTDk6eCONXtNAwW+gjE1Q65qU8hYTtfI1xpsetOxBI2QTw/gKzcTjpnyqNNx//vPYAXWZ+2/QXUQFQUiEM+7P1y1PMA7hMj8cO2e5L8jMABh9z/NT39I=,iv:qGBhzqshYLHLs5iA1UhrxEjAMNf+ACmXYABWKFO+PAg=,tag:RUvsBzVWqgCOK5Snkgo1JA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
