apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:e612PqfPJblB/6S7IeLeQ6T5KZUlYJGRNBogYgU3fqfATAfQ,iv:JS7q4FxH9gY8ceSov/27d7ruhc546/UyZQn4/9dIjH4=,tag:TsaImbXdFNnlb+/g8/QgJQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:3+CrGeWHhJNNF0S9KpKQ53aup5g0mD0EOknSQyNCaxkK0/v23heI9xAMyEjxrWi0CSCqhSSusuXmNw3OD7oO48OvTFcGjcQzFEi4xF0vk78u+CU5V7hMirRM0u6SqZ+cOYI1gw4aABOJbRpUFDy1XMNgBy6OcWHEcflEomMchhbTuX8Nc78wl3octK2bJWr6C+c/3DDrp56Pf+LCM7s+ZxPCsFfzdHqS0l9noane9Q==,iv:+5B5tssa5CAWy6b7V8SWhRwe3IlFIzy76t8MAf2ER88=,tag:nupgDrZkRC3LlzV0OF9fbw==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrKy9OMFdNa3c0citVKzBR
            NHFSZHpnZWNEbFdQT2gxcTExZXRCd0JMOEdvCmx5Y0ZHcFc3RUt2T004UlNRTVYw
            d3ZpdnplNG1uRzFxU09SRjhPeTUrTUEKLS0tIDYvd2pZMjZYZy9nT2ZZSzVRQ1Ra
            cjY5dGV6YWlxVXhONmlLcjdyS3JZUHcKHyqrRc9EDqeHDua0XyZ0fvIUfcAKX2mF
            aqXUUAwblm3zmIah3aN5CF3NxBL1iV2h6d7vpIe7M002iMH5HGgjWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:17:56Z"
    mac: ENC[AES256_GCM,data:Hls67OmlEFUxwOixGBBwQ+MoI6BgggINpOmg0SFdFQZcJBBQMUgJDNCUZ+Qp89kGvr77csVStkqw4sgRToLLFNShSZi0ITRjvX40jZ9XkcO5dPFW9AIgPw+uNmEjp9YBee/76d32cmR4FZKSMu+bWxZGoh0Sxu3IZstCoMhKPAg=,iv:gJVDSczFV3QfknwweNgJrcMvyP+4E370RGjZUz96Gw0=,tag:rNiMpmrKjXed+Om1RuKkag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
