apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:D8+Qq0JVr4xnuD1M6lg5VkFmv2KnQtgbYSpZJmJ0m0PTQ5aK,iv:8L3FKrt1POzdejx8CWDJb1uiNwf8Aj4tioWB6ky+1sw=,tag:5aboMJH7An1ZMeGHIFdjVw==,type:str]
    credentials.json: ENC[AES256_GCM,data:c328otd7vNiCAc7Xvt6Q5TuWgNlSLQ4KsAIMDVkSMqn4IVVBsVYUiaBUsURuhzRzRFp+VJfzCwUAfHHlrtANmlDjx72syGZLQpDn/SL6guITKW0HNJ2ZO/73P+SyV54ysWHRD7XXO5yUhDUPbWV8oFvNNHRHmmtN+hP/Olqy+aeuyafOiuhUrftswcDdz9LnJQiO+A4dSbGBp/QQm/aI5u1Uy1ImrfJunO6GYnPkeg==,iv:oNnIkjHlw02a4e9LDLeL2bco1bVnc9xFSRe+9jj+/kY=,tag:aNg89NvrsrljH0E69qyfKQ==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOVEyc08wd1ZyOE9RMzUv
            ZzVNalZlUnVlclFmK0RXSkF5NlBEV2pTK1FVClVHTStQN1llWlFjS0xOYUt0eVlT
            M04rQWFLTkVLNWkvbEFHenExNWtIK1UKLS0tIGsvRlgvK29EcTNhVmRESTdiSjVv
            Qzh5RGxPSzB4QWFHQ2lUQm1JWFdoeG8K7fBNJdzmqZjJJ2IT6myMtZNMpgOXUcOZ
            bMvIDBMkx/QDUsG324XvrahIi8f7dVduBI6BeJedG+bYyUrlzqrFbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:47:23Z"
    mac: ENC[AES256_GCM,data:L4tJHmSgvnnTZvFPZ1IybixacSg5pYiGvC6Dh6hNReXOSA0IGOdeuU4GUy1HOAMT5QivS63H8K4h7nsgIHO0eQ+aE3d5VJ2sOGPN2jdsQV2uMVubaAJ0TMKKqbf7IE533g9rHDNO3NyP3U0mBJ02OMuYDYCDQ7GFgZdkKZsYUiE=,iv:wrbbzgCS6d0/g2U4ni4hykTLbNH3VSaV51OcaVsKnls=,tag:IiosxWkQDsAQ6SRQaSCpoQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
