apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:EwNKD3yaz2N2qYoPBJXwWh8+mBSQ5uTuxk+ccJeKtEhc8DAG,iv:vy/ZhJZo7fNX4vPucr72e2yn3H1eF9hgeQ70622uXnY=,tag:fazIVm2fynwNDwOF7gj4BA==,type:str]
    credentials.json: ENC[AES256_GCM,data:pddhqCJ4S0tEgbkfGVwD9J/jQvFf8Svrzg4xFlvA1R4AoAXIfRiewEAJmagc0hy2H3QWxueX+U/CVA+NMFEz9Y+alPxHgPtSh8dEfyhS33vJm9tRZd7y2E78QP5H+avVIeQ3xnzjj0Be+wCAxcufX/v7uYlIfe6l3nDfzII4r7seWfvusE1VCcG+iGxcG3723rMN54qyOT0PtvVAW/XS28KDb5JXW6qJ0jdQm1MsQQ==,iv:+XFM3wxOjhGYXIc8f2S4ktu6DlwWH5mZexWBGhK6B0A=,tag:VfHdBrwdBS/PnTGFbLUjcw==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Y2wyQVo4S2NHQ1BrdCtU
            L01jam55RFVIUThPQmxXMElybXZlUTMxMTBjCmRndm5WTEJydXZmRDZOa29UQ1ZO
            TVVKVDlCNHV5TGt2QlIyMDJCWHZOaE0KLS0tIExYSUVpaGpYcFZmcWlkdWdOUU9p
            MEpZL3BiK2N6QmRLN3NDMWZoVm5aRm8KtlcaRMq+wsPYvdTmnYh9L4f3HirqoMmI
            C7MASV/Nx8/afP70RZ8Z4Kk/yvgLLFRyol+7gVlwG1lDUg1At/LFIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:20:59Z"
    mac: ENC[AES256_GCM,data:sIHjP90Y8Jo9wihiZDgLl4prODanY4QfVs48R1bvJ+2nhWWP2oYKfcgToTesoI4i3GRYc78hDck8Cb44Kpsst63Rt2UjtziSkpipmZI1fXw1BdTWcfWfO6dWJOf0Sf+jEhLcPJ0qckx0Dj0DBD8KpIYul2Gg6oYCvVQoS6bG3vE=,iv:btgk2NlzPT4MfJhBE8f6cUqpN3zWsMUqiPKBKwaBfUw=,tag:xuy3z2jk/xc6cnyE5/llew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
