apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:VBJdG7mIO1QfHz3NtvVlyLvrvRyXJE/CfV4+POwKuuHL7gZY,iv:PaF+ol6u1y38NJb55F9JVrtuNOyHY92wlNMHMTo7feI=,tag:V2nSsfkxWqtUe4/xIkjrrA==,type:str]
    credentials.json: ENC[AES256_GCM,data:VY4MXstHNMdOjLQH5EXGXWIG7DKyVmZ5x/MlsYle7IHTjuqR3NcAZz6XgXAXPhPssyFwmoBYI2OZHWK4Z19mc+V3erKX6BljKW5Id0Rfm7xfVlD6GN7RtmgsoJOo1smshDw0iOcwHS1yfM4TCJhllUjHxSzDcZnqNAUd69MqY+d8meEoTXBjRmJKlN9juXWjwYONo+itLgAYgIDGTjkj0GDNHilsYuUBBM1MrvOLnA==,iv:gX1eTojbjexpIJdFs/4l1sbSGqJPFSpEwfzHdd/tPFI=,tag:wjGq5ss8mZgtrLb3CivVTQ==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cnZESnNnWDE3TElaU3J0
            ak5UMHN0ZzY4L1JKMmN6SUFVVUNnQlVjOWhVCnZqUVMwMEJGVzMzc0o4emdFcTVP
            QWVuR3ZmUnVIR0ZmZkozamRaeHp5TE0KLS0tIEJiNDV0ZFRrZzdiU2dVSGNTczRn
            T2NBekFsaUNEMlNyTHBUeUF1bDFsZVEK4dr9kDd1jjnvpWsDGLeTqWz/cbQpbl90
            nvb+Qj/JKZBLQk7VkVWP24cMVF/o3WvqL78l940N8g2A4PCsftsyKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:09:52Z"
    mac: ENC[AES256_GCM,data:PS910y7bANuWEfFRHFnkqs6FeVHF62rkhOfyfwwdMoRolknQv35qU/zkUsLiKTFh8NSAQ9Al6iDRMftyFM8h3xhP8fgsjJcnVvZke3YJHIlTBoy2S0JADDZVYPNTNcTnd3uiutHvJSPK9G1j42seith9gSQVdG0Jc8X5zQnoWk4=,iv:tZlQY/dDVF+FPf0bnizO3yn4yBtB7m/PvQqUdBMbuEE=,tag:Q7pcMNQ4taFrv0dv+TCVwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
