apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:phIFJ1G7Oqo2eosXi3yPvpqN6bI5gl4p,iv:9jLODWg8J2XbePnGVR0sJy0axHoafzoXlwHTmJkrx1o=,tag:QSp4QpLkV/ELqfzygyaZSA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cmJRTjlkdHF4UUdzc1pj
            ekdFK0NrYWd4dnlReHJQU0orcUg1eDdjREM4ClU5M3pRSmJQT1NPVEpjbEhuWE5U
            a3BCTUtCNDVyZHJzOXZLV3hHNTJoYk0KLS0tIDllVnhNSDc2elJhRXFZRStZbGJC
            ejFha21yNm9GNllkUnpaTno4dmh2encKAC569T2w8KSCZ/LyKJXYJzxooLZY9lSD
            DOSFa7rCTnSti964NJkQAMM4C+o07VxhgQK/CRFdoAb36YY4tlV/pQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:04:12Z"
    mac: ENC[AES256_GCM,data:DSNkaXe+EI3nRGcZ/wu/9GCpqRpGHUrDBo2WFB7MHYO/ZDjoq1S2kerWEUTYGd4brZLet+ED1jZDE7IxkqsYZmpQao9lpifnQx5KQf9czFIjAIWCijg2gZ/Sy6vYhyHBbO1zEw4IjSBnvpIStq1B+Vz9M2+AZc3Swzg3yU/DW8k=,iv:3QTREZRO2CaTbAmiEpaexr+Psy8cJqvDq6VswS9mgIE=,tag:yPas9ZNkHTexen2JQ2JibA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
