apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:BmJDOgvlI+PGTo7iDsumGQH2icrIKxCw,iv:PbD+kAesR0tBldH3Xghq/d4K4Vg14RPtxXnklGtmcN4=,tag:BAhm0pZSJ3AeEcS+cwxXkA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXblBwWVVXQ2E3NWNYUDR2
            ZGhEQTF3ZUZkRG9uMkJRUUlDNFd6dEdYYndzCktqMXVOR1IyQ2k2enVMRE50ZlNF
            Z0RvclFGaWdxNW8zTG9KS2V4aGRwdHMKLS0tIGJvTitMaFB3bGVxU0lHZW54b3dr
            SmM1aWJQQVBBRWdKK0NCQ2lZaXN5OWMKlgVftoSwHCqGg111wxixrKe0+F202g+k
            cc/XHUr73FQbcBYxDNRevAubPKUMIse3u1bJP47vBLlguZECpPH1NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:47:22Z"
    mac: ENC[AES256_GCM,data:WQFLHw1rcNgDlWRro59P6MdHLqsEYqgVCu4UPRZ/V5TdWz2rmlCIKBzkllVkAqlHAFG/aRWZL7Pts3FsiACHz//K3Uyl41bDQ7VRc5NeIyU9Zk674Wk81rUzcZmNqPig5WWXebTXujWxL5/5FKDyG8gQAk8nrLlh75Mj2kgSgos=,iv:rh38XCRmV2V+oby4nBYI4IYceDd0YRu44AJ0WdG9nGs=,tag:DBidJUFEls20+Qq5ICGyyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
