apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:bILGeiqfv12tx9IVRkLJjjzPTvm9PBYI,iv:wOc8Hf4//QZ8S+Agk03d09LXS6/Pdu1Qb+ZGtnvCwkg=,tag:oDKG1uiqGDKWB5MKaiYIag==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSHlaWCtEZGtobFMxN1da
            UnlwV0FNOTdlWEFzeS9Jc0dzNjRERTN0R1I4Ci9uaEZWQ1pha1UzbGxLK1hmQ1l6
            ckVNWDNzSENwRVNybVBEQVQ1d213bEEKLS0tIGt1aFJzUHhreE82MWlHRFkrSHB4
            R1dVMEVtc3pBeWFLVW5jS2NwQkQ5ZzQKTJbLsIdwQ9sf2CPupbOSfTDaATuMF4ZP
            vobWBqsgehNGMQ+5AS1GQ9c9EShTio7NIJ2qBUEuSQtzxZB3EG2XUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:09:51Z"
    mac: ENC[AES256_GCM,data:tbTxcAPQ3P5Q8bwlKojiXwNrmVmwvXRWVdWn6PO71bVGMm6JOZnFgH+xdvRl5N26HO+YvJQQx0VlrwPgUi/8mZxvn9P/2Fzu8MDh/qJobTJcCYx1yImNf6ryWmudFKryoEdMAfM+0nCMv5Q/izdQn+lSJquGECxwQSb9zGic3ys=,iv:CVTc4RPIWYZaqy6e5+UEEq+RKDkYxOj1ViVWaylN0KI=,tag:6XCV+CUvDYARatmvp7c7BA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
