apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:c/XtPewe1UDgCCPJYbYeljG1prxhSPhB,iv:HAIPauoJM0QkF0yxaCpTa79Sgj1TCQIJ7q2SWkPOsSI=,tag:kvoBKXq9T7e2UZqiOXzbLg==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bGxURTRHRnlkSjVMVGFi
            NS9JRmIxdnJ4bUNTdVFyeFhXR0FHNml1SmxnClBLM2VGQ1creTkrSDRZcDI3YXBs
            VmZnYUVpeGgxN3h2cXlzM1ZwZDM1TGcKLS0tIEtNbEtCM2pWWUJvNDVWSlBHWnZG
            R3hCL3c2dmVJU0FmQStqd2twcmdvc0kKcjBz4OvInwu+3ldMJydJfyZy/e4O4bIh
            ccDwYZ9+TF5tt1FZnQv4Ma/XJu/U2iky5tCHwkZSer+tHhhS+rpFqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:25:40Z"
    mac: ENC[AES256_GCM,data:cmhlH0S/6x0b9J7YoEsGy9KkMYA746ngpS3aw/U2KtUrADuGthMut9iPRGMOdm9AP4O3kWANSPyC4s287DxxNvjN74OlXkGnlZ47v/FeFseKSg/NDnug8fhpL5LTNV6dE61LBa2oemxIa+QCVMdD89+r8CWWnGHLPSvELw9yVu0=,iv:GbxUIS5YPce6HO782Z6+7ZTAuDlC5Mo8iJHc8ttJKmA=,tag:n0OQWmclp/QwunBweyYmUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
