apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:YqrbeS19tq7t/Yx45FpNlBhdvVotRxem,iv:xh2/XM8rNwKOyqAWbAB+4tAJppok23AISqgJLs2Z5ug=,tag:6/9LRO4wj1tNLVWwiRg2Iw==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreFJXMFNrbVpVVWh2WWpX
            Mmh2U3ErZkJCS2VVdUF5akVuc2MrbEY5NkRVClA4cmF1aVRTNjhYK1ZQb3hTVzhV
            ckVQNkY4SlRjZXJxdlZmZkFBRXZQMkkKLS0tIDdyZFlrbi9ZOWpIV0U5eWpFdThu
            N1JWQWRXalUwY1MzZ2xUR2YrdzVjd0UK0UbIcMUwScpNtMNpHXfu2NYIok8cHIhh
            eFOizKI5p4I2Owf+u5f5NK0z2uzN5pBfFOvi23fw2Y/Ba6+HzPPMSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:17:55Z"
    mac: ENC[AES256_GCM,data:JIH+ue+rXIXV9x8HBKLmUvlL07zC30o2brUlmGYnqYaDbopFisfXPx7cf8ADKWwz/BvoqOKpcHQ0NObxMaozSrC94U5MVnnrAgBs/PVgm3ux7RLwnx4YaKVp72xfhZ4unNznHU2kj5aNbj71ngz8rOqKgrHMu7wumZNmW4uflaA=,iv:8rbcViaS89v9AyVibjVfLkT/Ws3hCo43sUsHNdGzRz4=,tag:b4YxWBrN49HmibX+JZfK/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
