apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
stringData:
    mongodb-root-password: ENC[AES256_GCM,data:YJY5y4vGWWDT8pXfWx27aMgkDIkSq9k7hkkBjXxeeqI8QgshS2JM4w==,iv:f2LWGqzWRoogjYNuttp1MGWfY4O+p++WOB0M1BzVO64=,tag:aJv8BmGCskGbGhpewkoF7g==,type:str]
    rootUser: ENC[AES256_GCM,data:zzjCCw==,iv:AAZ3/OOwCMKdnd1RWY8qmZ3WpKS2Fw7F30KuEO1G+yA=,tag:xj5EZHh7j3MRkGgt6VopVQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKa3Q5WHFMcjFqNDZobEFw
            T0pzRmE0VWZkeDZDd3FkYkFQRThLSVlUbXhZCmFINkNiNnFTZm9EZUtyNGswWDJm
            QXZ4VEIyV21WMTN5U3VRRithRzBXaWsKLS0tIFpmbTlIOUEvWWZkVm0rOStPL3hz
            UlRLZ3NhVjJ4bUl3cnpCcjRaMC9XejQKZzq8y9vSrjHVtNAWegljdj1PlmGWqlAC
            xPsNBrc7uySC6ayx3rygHj03Jl+fibbij+In4WECu4sAHHvkezpnyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:10:18Z"
    mac: ENC[AES256_GCM,data:XyOJeODUMyLyOsfJw0jvK07gV15iTbth7OmmtHfzg3lJEPZmGRJ79SoAEuzN6C7mtAE7a/sdxzuF0wMbKjN9JChlZWL/MNFeQw7sjvL1UrDt9i/K0ldqq6bQqiZfJ+pGkzvkIsForuBUOuGreniyYTO3wtcGcviKj/H1gihQIZ4=,iv:TfFBjPnUd9uT7toSh2M/XxBUH6hrmd7hV1I3waZP2Y8=,tag:SOp32rU9IGbQ0OWWrViX+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
