apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
stringData:
    mongodb-root-password: ENC[AES256_GCM,data:dCzEfEC497hrmGyWEusVRtm33Y69jVmPC06rB3QQwbYqzzhRx/vYvw==,iv:fcXiL0cVKnls8mAdHiI1p8QRo+fPV1yQHLgN9YM0q5g=,tag:AXCxu/ZYIGtRaC1Yl7/yKw==,type:str]
    rootUser: ENC[AES256_GCM,data:tTTxZg==,iv:SHxMRZpUgn5lnmj7TuuvgwETP8kIP6HBiLVfOY+dmRs=,tag:9EKSGRH/QSDazHV/6esCgg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMm5sZ1c4d3l2bE9OVC9x
            QUxOUFh1YWtVdzlTWm0yMEdTSURhdXh0dEZZClc0U0UveGhmOWlEaFZOUDZXWWc1
            SGEvTllMU1ZGakhxQUhQR1FkQUo3K2sKLS0tIFg5V2V3V1p2eUZSN2NpNzV6Zi82
            YlBhcUdnSnFHUU9DR0J2em5kL1BHK1EKLK/GLe7WB/p1vlDC9/ZSUVm4IFh25Xrp
            s91rIVv8Zuo2d++pWAvUv2McPJkfTL0/5RsO5Npm2RCOW4DsmybpJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:26:17Z"
    mac: ENC[AES256_GCM,data:ieN5RWJQGNPWEDb7uDzC9fXoUHQNTM2BV9hXfm4X0szVLiJYg0gveoQUA3KtoYtVcNsHW/SxWfsb+gVYKj6F0NI935ndYFTXvgQBxTrqrKDMvKVf76NhsTz1HsiCNK4sBB8VkxIY1wBxVNt313e8mov/aIoi0mbVFm8uYdSAr1E=,iv:uCMq1z6O3TrpyUKlOA5bBVYOHV2nBdBkFLpBUMojhRQ=,tag:k0vo9e1ooW47sqwh3lZyEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
