apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
stringData:
    mongodb-root-password: ENC[AES256_GCM,data:M2onIBuUMd109ithHIwnRIqXT/TYe4A7hJHIWzwsbB0MgvMQCKvYXQ==,iv:Djb4gDUGgZpLeVF4oOvym/X694zxtBAyqtw90csIkt0=,tag:kfZ4xO5iwGwCvWONKWCiuA==,type:str]
    rootUser: ENC[AES256_GCM,data:7mNCWw==,iv:dQrGl5woQMhGtup5XKkUEHmAwmXPD5g3SQdlxKhaxig=,tag:wKBWSq78vCHpU+uyK2U3QQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dUJvNS9ZeW1WeG9IbE9I
            WjkrcVN2T3VxTHorKzdxTHVjOTVlSlNQSUV3CkpnZ2ZZNFJIUlRYVTdNcEhTMGxM
            TW5CWlVRWW9CcktVcE9kVVVMandocDQKLS0tIGVhUDlKOVpPYVc1Y0RzaThZSld1
            THhDOTFlaVhYc3JLOW0vcUJIT2hJQ2cKTS9FI4EsxrLacvmRuyCrGGX2naY/ik9h
            aDgvVQf0n1oMzw2lwWtrsU+88gjgho5LncyQH135cny+nnfLCi6jPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:18:18Z"
    mac: ENC[AES256_GCM,data:ph4xkyknzTKIUDohbvLDZ5JoAqt8vzFsn6Md/LXuSX3XAghwPenV1LmDfvTYiAqXYldIn1calGHNkGJVIQqWnf/kJu/oSgxAxX5T/GfNAM0KIT4kD6J/1PYdAKn+wJK3aUNzMvWn18WohU+oKHlpKoEsRDcO2Am5/syrbIBx4oY=,iv:hRgbbx5Z6DmRh7n9D98LAqtUVSe0YIiBBhG2NrjBxfw=,tag:4XK0dgFzDlNEuvoVLYri0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
