apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
stringData:
    mongodb-root-password: ENC[AES256_GCM,data:YbQIqG2jk2YCXuBfGEllCnILYaaXsfe1MOXKNvdq6n6kTYsnST7Mdg==,iv:OITSS+zlveBoHhei35wv3s4fGcv2eX1tjaLEy1R47TA=,tag:cV4bU0OL/T/AGhIiia/Sog==,type:str]
    rootUser: ENC[AES256_GCM,data:mKVepw==,iv:u/n4wNOhT0p9+jA8gCb+h0ZVtGO63ZP8QTPgLO/YvDQ=,tag:XFE6a7lkiZxbfqBuQrUTug==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VW5nYUpRRHJ0Rlozbks2
            KzhUOW1tOFlYQzdqMmZsY2lQY1FCYXpmY1NRCkFDdXFwNnc5aDRhRlNBdWdYODRy
            OWptZFdiZ3RSOGsrdFRobU1mMHd3S0EKLS0tIElVdVZUbVdwcktIMGdaaVRpM28r
            QVViM1ZKRmpFMmVBWFRJWUFjaUEzdzgK6+u065j0+FZfcEudcNmpBvXsMI8pgWIx
            U59fbzuXlRGll8F7aglhxExbt/V32wpTAJCB6oTkEgTpyO18jQGXXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:04:40Z"
    mac: ENC[AES256_GCM,data:DOIW8YFX0IydnEjXUMIE6AYmnWPvgOJM6PZbW+SUe5SohWLUZXRfRe/C9B/YfdLQ8Ms214SEW1g99YKO/21aSYEFCS1P7m7d4cjDVYWGvBbXqDDbhDXidkZoarf5Rj85E+j2AxLZOxz0SMOubSVvubNdtI6xI1HwGW6dWQ87M5c=,iv:5ZzAfXjTOwqRfO2dEXT2XXDn6yIfkU7i0+MGuKX+d0g=,tag:qmuqmT9R0Sp/Q30FROYQ8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
