apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
stringData:
    mongodb-root-password: ENC[AES256_GCM,data:xpMsvAvbAcwr0tIdScLwkltVoFjJt0L3+w6RBbun+0GLe/V+xxwpmA==,iv:JMsF04OT/DZ0o0ukKzCQLb+mjJV2f5SxUnNCxj0W9Eg=,tag:5trFmCSwFner9l2S5/vp5A==,type:str]
    rootUser: ENC[AES256_GCM,data:F52sHg==,iv:15iBZj87FVd9vs0kdJXm+RnKP0Q+j/KIV+YsPgyXV0g=,tag:nAEl3We6cfnhiiV7vcZAQw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTXBidkdtQlJDLzFxTDZQ
            YVcyZFlNemNhaGVCalIvbTVqTkFLc0lEd0NBCnlxazRxbUpsbDNzaFJhUm51SHhJ
            dHNFK2R5cnJPM2cyc3Q1M0FwRlhwTmsKLS0tIEl6TmZOOXovaUZ2V2RwT2FaVXRl
            U0xuM0xmcFpWTS9tQ0ZVZXZiM3pOYzAK443SALhEEhWjhKoH9p5+b7SyGY55L5X0
            h80y6KFjqC8hkKFaTdphHSRGEy9Qd+dx5xfmWs6+R2HA8JbitpZvjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:21:26Z"
    mac: ENC[AES256_GCM,data:6/yePYp+18BdjJN5nScLm/Q6NWhPCsM1J7hEiOMQrPQuJ1psrmUU9N6Eg3EVIftaIBnHd7SuzQ9Q2mYxHGpS1UiFso1Bp8MCHdatqyVDjQ5/9NlGRiqlglejoghn+sb/VrgSwfNFD4AFGALJOfB0Mz5z1FaSzk+k8+kAHQcCkjM=,iv:OGK+xiJwcH7sgzhnP+6OixeDoBvzZqM+W5/8rRJZqmI=,tag:AcU4CEbQwPLckNC1kaWEqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
