apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
stringData:
    mongodb-root-password: ENC[AES256_GCM,data:JtG94Ac3wd8sLXQgrSU3UT1Xqz7lr66nSHg22l3KofrpB+yKlAmD4w==,iv:kkDJCL+4XcjC+wyrmdo4fEWSOT1P/ir7IWH5wg7vE4Q=,tag:XVKs/D0nCY9fpfv6E2nxJg==,type:str]
    rootUser: ENC[AES256_GCM,data:eUJVvQ==,iv:cuNDKFc+ZQHW97iIegTtbU8+NwYYPfvvBT/rNJBPZlg=,tag:YS0eP5KKT0SDbv8t3qaVzg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q29HWHVhUUdISFlPSmFn
            WDNqcDJablpTbHVEVS9XVHFTTEJ2NHJ5ZG5rCjVwVjZNRjNmcTZSb3JBc2p2Yk16
            d2ZqRCt5SnM4S3pFbEtZOEhpUWVaaHMKLS0tIDM5MnZXT1ZmUURMeG5tck1qQnda
            T2NmRXh6S3JaaFF0a0N6Vm1oNzZxWkkKT7ehmHd3Y9BoFYR1AIxzaMkKdt9+chA3
            ZExEVNOsP5SrF8qDsK4tAeyKEyrcX9DAneV2Cf1NTKBWsqMWk+Swrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:47:48Z"
    mac: ENC[AES256_GCM,data:2ECcQhyYKtTqgvwckCSUzsmKfHpcf2rfzOVmB5opt+bCkMljShsJVwLA6tJvjIScRcKMS5oUSiqhuMZKr75FEcRKRtfcn4ClRC4jq3FCWebtG1xznpbcu0N0v8XLTotGOsQ2ZIhYWTbxrZSg0HEwXqcOKt/Nh2G6FMDKgI18ZnY=,iv:LhIhcbIgREk1WNW/rJqpPfr5GJhlhxkjlGZ6LUxijDg=,tag:48YnDmeB4LtSb7eQ/OUi4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
