apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:YgqJQriM3hK8JLj+FdP6wdqGCQyx5pqiSM2cybniam+dJTMW5j/n8g==,iv:rs2vZuwNHDVdEqQuRc+rXej2d4Y+Z6owFVerXOJDPEI=,tag:JOOFqjDdGPyT2UUTyKEHZw==,type:str]
    admin-user: ENC[AES256_GCM,data:vd9LJ4M=,iv:uNbIuKpAI9UfRbHjTCAMbLWBI9wZg2oIzFyBLz5naew=,tag:FlKi/r6cinMmqB7ywZ6v+g==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxekNWV2g2Ym1ZYWdST2J0
            NW9LQlhhNGxUdkwwTHRSUXMrUUNkYnkvQjNvCkhkenNwMlQ5S0xleFc2M3ZrRUNH
            cEFNbjlmNDBVSVErQXVweGtZQllhMUEKLS0tIEFtcUV5MG1LZHhBSU9zR2NtUktr
            R1U2aUFVaytSQnE4Tjd5QVkyKzdRTVkKTogUF6ZOSrffJSYVXM5dWaymt+z1kp9P
            qdnldSnf29odrDbVWlW6jojN/AMHY+TC70Q2t1GF0emw19kvK3ILOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:04:24Z"
    mac: ENC[AES256_GCM,data:HecQdSYJb2I7OySalIX1Uicdm3vjiU2pSBjVT0b8UIGiUYEWkX0t5LjOkdXeGaQNejshJmdDskoaXOlxxRbPL867k7tXT1jwsK1VSrGHmjcyOzz4MJXTuydk6+vDwvKkdY0PJ7FcVlu9v+frL2kyBp5++4vXZW77Ws2+YpYHk8Q=,iv:bOp8wuIsxa/SvBwSQ5srOP4sr/cMNapWCFV98gBvDvw=,tag:z+uFyQpUl1A4UwAtTSsQUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
