apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:nLR2xkPw9Cp6q0YM++txXz+aMpnzUHBRnEc296ahiKuJj1/5uEnGwA==,iv:5JT6YOj5/oRnL/6Lg79nUgVxUsiDrBrDnZN0zwque08=,tag:APc60Sv36Ovc+7++rrokIw==,type:str]
    admin-user: ENC[AES256_GCM,data:ecQdmyw=,iv:7B9zxZmAAu2+Og4Vca7RAL809Q+VpRVwTIW+RJmMvZ4=,tag:S9V4OVUNjdbI5Bvk5nBrvA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZDhyeHE3bmczazNWR0RI
            SURkZjQvNVRaeldiTkhBMkVCNG43VVBYaHh3Cjc2VjJQMUlicFFGeUkyb0FFRGJh
            RkpUajl0dW5HTWRUYUlQSFZoNmhEZHMKLS0tIDF0WStKWkFFWWYwZmptak5pWEhp
            OWV1aWJnN05aakZ6ZDBLbGpHWTZsUWMKo2bxm/dhhIINvsvqKheIhcHg3d9ZACuW
            HyiHx3EgrsNy9H9IHGf6sHBiq9k7McHqwea79X5INkJZO9fn5BaBPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:25:53Z"
    mac: ENC[AES256_GCM,data:/agY/oMaUDuSEz57Uuw7u+T0hFJ2nLKrN6ZmvBK2aiHSgY/ZWx3cZ1x+DzDVv3/zcUzGAjqJpMoC62X5ZT0NOlpTjIvava0OxXOnd6Y2M6QM8/b62X0UApo4P4elDPOGzoLJ0M2hlyDvVIb6T1LMZ8Qv7B2maPCHZwROjvurm+8=,iv:skz6IMGeeHT90PT1mbWoC1PzV+DY/2XW+aR4Csz9R68=,tag:+Ztrw/ueJJY/5lVRlm+URg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
