apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:TDNXegP7aL+yAcmWHhZJfgXW6L9UNiQ81JGh6m2n04J7DJsbVVZYjQ==,iv:+Jeoip75ufb1sQrg3+7MzZUSpXB89HwedC2huZrhp1k=,tag:yCMCTHe3bel+ju6iklFbEg==,type:str]
    admin-user: ENC[AES256_GCM,data:CVpHTKA=,iv:qZqa+zavsv/C5S1/+OYuLDBziVE6DOSGYodyQFKpaeo=,tag:HC3XVsMhd9sAI06/3R3WIg==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaG1Md2NIUG1Cd2M3aXlK
            YThCZ0JDTEdFbUtOcThZdDhyd0dOQ2lnY1c0CmFIT2RuUmdCY0FLallhRlZXZ2pB
            NlJScXp4QnhoSzRUdmZ0SFlQSjhldGsKLS0tIDFFRW5KcU55ZTVaVTR5enpMdlJn
            bFpGcGtCTzRDTTlWNVVyY09USmNpaEEKQtxsEgfdBvl95JcwKblzme20Nwdbuz3y
            jcgtgBOHnn7+WEz+sbkOH/p7Mjp00g1HMJXL5vJgbOkFcdNQCx6oMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:10:02Z"
    mac: ENC[AES256_GCM,data:HlgMletE+4hk7EXYh3BL52S4Z1bhDVsWTQ/w6nnyWVJUls/QtO8wGrUoq/iL45Ue9Wcuv/JCYwBFuJZB9VvFZoKAhVaeR7S7CEYkkllPoopOPsA4qAVKNxGT5UmUZpRH1rD1Fo71yMIup3312h7zgOdKm7xDNorHK0brYh8zzn8=,iv:YjLHpkWvjEVqSFUe7v+53lhgmY1rUcpb/oLL/ibo2wo=,tag:vRPR/hxquZo28UQSgd0buQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
