apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:sStXsKuHs2/MvqdSHuQjwRfuLGFZXa46tErKKooGOMrG45Pdvpe68g==,iv:TYwNSom8T7T1n18Y/gWlgd6l5P0YnUzxJhMFTX1h41I=,tag:BT8orDjvhr/oW3gdmHFAyw==,type:str]
    admin-user: ENC[AES256_GCM,data:w9z7688=,iv:KJrm8JGoP0NDWGGsy3LQso90mMbqtq2+qh8RGAZcgC8=,tag:Kzy0AO8VRvagcerVS6H1WA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcUZ5S1pLQThiaXdKNUls
            NmxId0g4Vlk1K0FlYWkvYWxEL0hyL1p0LzFvCkYyY3ArN1d6b04rQlJLSi9iK3J0
            bUxXbXB4S3htNUovUEdFTVR3bksrQlEKLS0tIGhWamJkZUFTZDFSQ2pvSFg1TFpK
            dUoxdEQ3a2xoQUZ3dmp0ckxVekNUL3cKHWYp/EXmGjM3Z4G+ygBrZH+vWIxyOYs3
            juJU4Xt+kYEothTwWlV4MZrCQynfWj97z0PD+TE7aKH6E6g5X8RYJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:18:07Z"
    mac: ENC[AES256_GCM,data:9+1wUy1+uHQf0vWJvNttOvvv8+vL+aRNWglqBEUdq5MPYwyy5dYw6S7ugTn3mBMw4ulk/84YwPvc7Wbe0zdgiVX2P1SZI3KMuWk1GxzfI3HTpEY4F4SANXcG39vb9FbltJ60itBTwwZRiVCTI5Cfrdbz/Cou/W712b9nwcuzE9U=,iv:uO8bZOv/FngMygzNVzJiTF658s7KcYZ0ySlqrYdRbhk=,tag:oXiFP3t5zntMbe358nGuMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
