apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:cY48xkv5mKPY8dtISPA0xENrG5W4/0nZ87RQ94cdod0cEfOrq0NU/w==,iv:+a1NDHSXWJU/i6yl3BXstZYJuLTYskeju4bPfVEEPw4=,tag:e0ykPkzPfPEzgSXUzI4dsw==,type:str]
    admin-user: ENC[AES256_GCM,data:N8RGHNM=,iv:6WCB9eyUfqWIzhPHAAlokrtgYqhN8CIjkTuSwb911Ps=,tag:E04152PZpxv858nsIVEDbA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VDJ6ZUtDa1pjakRXd0Ro
            bDZmdTBrV2NPQU83OCtoM1lHZTFmNmUwOUFRCmxhajkvNU1iMnZSNW1yNU5SM2U1
            NjcyT2xhMVh2azVVRHYyZHlOOTVEOWsKLS0tIGNFaFlMODVJdHFqeWN5M3JKZGlq
            Mm9ockVoZ2l1Mi9oYzhQYmkrbVNKSDgKTBhpHcKS3SGJ9b5rA5WZksMzXFkKBhwl
            P9Thqlsbji9wuuTVANPIYIKzoty2IBihyzNTCkIcLhJq/FgvVy2jVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:21:09Z"
    mac: ENC[AES256_GCM,data:RDe82ksLlKp/pzo7LYq807X7SjhCI67u5VnTazO85phP7D8tql6aYCWBh056NhQzyKoRr5cqCWAAk86zLvAFxN5cF8RaGYNPG4eqkAg5GqJ+gujlXFXoHEM0dSgYfiUURRMJsYhfGVMNj8CKplOwyVOzOtiHxqgMuyhYenHmfYY=,iv:C2OA1X0l24r9C/HTa6AfyhZm1sBEUfh4ku7mW1KFuYk=,tag:5mYZutTXhkNOf0p4YBDwzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
