apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:1LJKzCGl0i994Ajm3XqAADslmIrkY7A2lskSk78umAhk7W5SvXpYow==,iv:+395S9dw4X2uUILyoJvtJxLhAhJIL02uBPr6JuM/Gho=,tag:7L6k2s1novrIAJP1xTIYIg==,type:str]
    admin-user: ENC[AES256_GCM,data:DctpHRg=,iv:HEXaTztlHl8+qFX2Yr8tyRcdne9DRiG3Y+ug5mAArUU=,tag:DkkL0mvCwifGYW1bOMmAaA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdjJPWkFycE1KUC9rOE1F
            bmtjSlM3WjRhdnpScXVrU3JtOWxhemQwOEZJCjQzbEZZNlhJRnVWVlVZTDBiTy9j
            MVFZT2k0UGxZam1ocWJzNnZuQnF1ZncKLS0tIEI5SUJMUTRJVjRRVGdkdzJZYy81
            Q1hGSndrYm5ibURMSDFXM3UvbEEydVkK23A7eLerhTm3MNYD84gzs/b2qEF2nHEx
            QwGSDdqZHhugMntfqwqJrj11PQPV7DrkWK697+o1MqTZ24YUZtRvOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:47:33Z"
    mac: ENC[AES256_GCM,data:lUpJSpb2CXA80mQ9b84oFwRjE8Pp+5pUVbK/BUYkWRhFL79FUtfrxEImcgvml2dNQHFWb6HxmiZZSY2WJt/IUkLOF0Jf+gcULD0bFCAAvmpVdTGRPV7OWvFusbWJd+2OAW/qQcJLSuyigmVpzBcIhxlnES3hH/X/YsJzmibs2w0=,iv:O4vUoJ/ijGRQVhWkAIqMAcsHALTeL27PWcQ7vEcwQJQ=,tag:LkjwlNoyqwcHIsu6U5Pinw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
