apiVersion: v1
data:
    RABBITMQ_PASSWORD: ENC[AES256_GCM,data:5a17zxDeosFmHEVMjKrAZw==,iv:1eb7wneAU4i6+rnAmgLQ0nYz2WMWXAUk2SCuQF+681E=,tag:LWhefcurFXx+EtbzI+KFaw==,type:str]
kind: ConfigMap
metadata:
    name: rabbitmq-map
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUjY5bkxEUlF1Yll6dDVa
            VHNzYm5udG1tdW40RlN1bFlNZXdDU2JPM0VFClFvVncwSG8zdVpEUlExRUs1d2gr
            d1VKbVFkdVE1TVlpYlJFUDJjeUMxQVkKLS0tIHF5cmVxWlVvNHpRZGhnTmFUNFBX
            bUF2cVpkT3Iwa1ZTNFdoUFJGVlFQU2cKytHS0PRtNrKkKLbDdOOQAZ/b1QfMBITg
            rcGRgn78cfozObV69mT2cKsVPjnkvCiBKYXLzS580Tmg/8s9DJ3q2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:04:32Z"
    mac: ENC[AES256_GCM,data:gLdpyGpJaEjAW+NyPiTJ/Q9GMKsrVOixD+1VK/DHzeme3NYKwbkgiASzu9bwjcDWNNjINPILbRTDsUKdHbPQQHstNS7q0UrQ7f01PspZG+QDhl0CRLgVSdQqCuX3pxsTmz4thfkQUflpcMk8AH6o3vrzjce93nxhelLXm5d8WLQ=,iv:up6bfUSqjEdTun+8bWCRXUWBZebCuo3YIL9srsx2Nb4=,tag:NI1r88dDjRkPOViHfs7TbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
