apiVersion: v1
data:
    RABBITMQ_PASSWORD: ENC[AES256_GCM,data:IHIkSAm5TDhK+ssuEcEhwg==,iv:h+KQKzBIIr4oJSlXYTjbkSIBjEAcTKsXW7xGTUoBWoU=,tag:cTElKuotMcS5gVTI+tCOGw==,type:str]
kind: ConfigMap
metadata:
    name: rabbitmq-map
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVkFWVmMvL05JL1dZYWtY
            aWplN0UycS9GMzFrQytxYldKM2tQMHJhYURNCnVBYlllRkhoZTZFR3FGOVUrUy90
            WVRGNXJ5VTlUdDE1bkV5cWpJRXBpQTgKLS0tIEVHeUZwS0RUQzVCTG5TNk1BUWo5
            bmtST1FJR2xobDRvcWEwbTU1dzlkQW8K9GwXklrOJwARLvifHk51rV1/KKstn4cQ
            z+0QjV6uAtELPVyU3GOfzCuKn7KeYRAG6AVPG5ZW9HMLnHjVnhq41w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:47:41Z"
    mac: ENC[AES256_GCM,data:Sz986ebuZsPVx7FIxtNtHTtIEd5nrchyaB1x5xtfWhTAKbN506+9UXPhuAwvOMjch8KIdP7Z4cFVxorsBV9NjXfoQy2CkbNh2ho+ioSmCzPCxdwuax6+cXYnEpK4YhAAv+8VHpte5AonJUfqz/GPXCpTnkyGhYARuOEkMB5bEOA=,iv:+5pLjY4MBqKHjnZCVJVo+PQ1qQ4QCEXmcymFogHTLWI=,tag:vjs5dvhBDUmMbbGkjfx9Ug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
