apiVersion: v1
data:
    RABBITMQ_PASSWORD: ENC[AES256_GCM,data:SHUxYaw8QD30KpkRtb8gMg==,iv:dvYgZGGleB9AyQmXb00KhNLRZisdsKu1rXS2YDap+f0=,tag:8Q11bvPSz/TwhwILWnhO4Q==,type:str]
kind: ConfigMap
metadata:
    name: rabbitmq-map
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVDVySXl0akVZcjJVUGxo
            RGVWa0lIRFRocTk5OWlHcERUMEV2ZlNHOEVjCkZWalhMZ1phai9XUUdsYkg4VE1m
            bmQrMzdqaE5VaUJjRWtQZVVYb09UNUEKLS0tIE5TejgwdVEwR0J5TU0zQTUxYk5r
            MUtRS054V2Uvc3FieFBkVFVVa29vQlUKCrM3ly1szJezv7ttTB8y8qR3Y6OsVJ4k
            wEUMV5/lnAAdSLNM0UHFy9lZyzl9XqdXX2GjXwYBhpr0DikLTSXB/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:26:09Z"
    mac: ENC[AES256_GCM,data:Sovm/c0Ef1Fjx2qqPKtTxAQ9r5Vb6nTDb9JcLt6kcd/o5jKp0gkXsP1DKzSHOqSK2/I/xaEiYdaNy/B8khSuXYgFCmP+f1rFS7bEGeO2lJbYDiNL9Oia8Ek4M6YuBjbglLMk9rcBhgyuqQ7P/UQBCOkE4fsF5akpPeLNm8izOi4=,iv:hvKy4ri4eApIH+BJdbgo6Xro/iznu3bK6jyJXsnqf0Q=,tag:c4hP5flz+83gUrrWUhV3Nw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
