apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq
stringData:
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:nS1KP2talf3wWQRgE/Be8yIYlmAGl964+v3Ulmqi166t,iv:iQgx8a3KzRVmZ9VOfa3M+OPt+d+2tlJyX8zsLLhTKyg=,tag:P9G7lNr9fAqlNwgYmkmmeg==,type:str]
    rabbitmq-password: ENC[AES256_GCM,data:SYnpdDm/vm4FxZUrLyI2vA==,iv:u4KnXBGmOtMRMdqakX0AHQNo8ZHNiUPeMj4FJeLpj8c=,tag:Zyf0CC/TzSk41GQEANsyHA==,type:str]
    rabbitmq-user: ENC[AES256_GCM,data:Fpt1Fvs64K8hJ/79zA==,iv:cX1TZzKMEUNLSYjMn6s9JCjXXanwlo5Us1NKu4n5sAI=,tag:/jmwbZ+IECXVAtyTd6tJ/Q==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdHNuVDZGQ1BjOWs2dmEz
            ZlBBSEFkVUJ1azRZU2NIUGdreGplRnM1N3dvCi9ZMmdyRUc4ZlBDVlFUd2N6SW9D
            b2xXSlNZSVVhNVNHYUI5S2Y3VUNTVTQKLS0tIGdJM2ZsNDkrQ2tDZjZuVzBYYWVq
            dm1hbUFEQXhYT2JhUlZZZnhWcThETzAKdKyQrpjXS9nfyiXenvfiWxK816fJVsOa
            hhgOYknAzDWXw6by2Pv0sPvQvkB4Eb8+FjhpycxQUVvPQKRMJGn/rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:04:32Z"
    mac: ENC[AES256_GCM,data:I0FX4kUVUJXyNc1fI/AFXfSc57BSw0hlZhbznLvhwRQoporY0noZDL0WpKtOQBheJHb5Uplu9JpWpLSpPJXqFQtcAXhC9n2ih786eBRmCxWcnW6b5qewNPqx18pAu0YFO+iFaOasIClrkHoulK9QlFf+mUSnB13RUFHQXR8x65E=,iv:zjiOvrvPqvuvEs1Yb80hcAM/3UAiNDUbWTka+XfgVUY=,tag:nzD6SiEglWMoApvgYscA2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
