apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq
stringData:
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:4gS+9Y7PU9KHRkwoKlKO2SpZowkNBF8+QhVt9viNpKE6,iv:LjV5WNeXf7S0ol2GKM9Qw+4I4pgSXs3HKvAtvZ4hK0I=,tag:Hv31xCmEp1MHAEfiF/V+tA==,type:str]
    rabbitmq-password: ENC[AES256_GCM,data:q+YduxvGoGh/wMS36QCbMA==,iv:vpNKsnKXhqMo6Sp28KawrqUiJCEWQQ2kZE3FGyMn4JA=,tag:dChni4cxWt7xw4TPNyDeLw==,type:str]
    rabbitmq-user: ENC[AES256_GCM,data:jpGYo3+AfGhoSfKKog==,iv:tZl3MRp+xnXyPPK1pCPWfLvvZTLW7DHJLq1EV4GtzFA=,tag:XIyeYHLGMdkWqGf1QzROBw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZ093dVZ4Z0ZqSU5CRzVj
            aFN5TDdKdlhHNEZWRUFvUFBoQUUzVEl2d2x3CjdTVGc4cTZ1ZWVldXE5dlZPY054
            OWRRTHdiSEJvdXZjZWd5bzJQM2VqRG8KLS0tIHk2ajg3YVhRQkNmR1JKMjk2Wmha
            eWtISHlvR09ZQkNxRklWUm9NOVBwalUKkmsWxGMWdYAbOBRf2BnO8M312UaWzAnt
            TBVY7273lp2pVTf2D360HqpE3N+9VvHUnrfzfvva9zCVpdHzHDc1aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:21:18Z"
    mac: ENC[AES256_GCM,data:JuiabCJbABOVyFEiSa1qXFs9BmtVFUkd5ANF1VWj6Sjg5AbCuBjcM+wDN38NmReWZUmpU6lAjkhYnOacse5emhk1BVGUsYvqkjZvsIrulOT80A+Z18U95G/woMroQsU57rjs0Ctt7vCecku2PN3dA12ezVv8ztZd2hGTWws2QXs=,iv:ukA0iIljsiIh4+QCx6/7/8tVqTFx1SMeSAYiizBezkA=,tag:Qk23YKH3gC7Fk3uEVgWpeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
