apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq
stringData:
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:4tIpnWc5+J4pqP9N+PC4+/9V2UeLhsCn54UctuumhFw7,iv:3SYFoexjBgWDpGVF7qNKBNkQwkQPhlcT577CgpXJ7xk=,tag:zV5pQtq3wGauYTB55EMrHA==,type:str]
    rabbitmq-password: ENC[AES256_GCM,data:2LN/wrF5TpDDooNl9dJd/w==,iv:R7pA67EH61Fm7g16wq54Be6ZPYvOTzun569cBQqKTHc=,tag:hNdVTBWT9PvYCYfAoou41Q==,type:str]
    rabbitmq-user: ENC[AES256_GCM,data:LHIdizXrmYNu4r5mEw==,iv:/S7GIuJcabAyM1FQlkeYpGMkYJtAkdtJKUKQloaKvpA=,tag:v1Hfzs2nc/6w4AjXpUrRBQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbnp5UjF0SG1NemNGQ2Jw
            YmpLSzdFQTU4WU50UlVWTW1CNFNDS1ExUkVBCmZHSWp0Nm9uckFMZlVqN1RIQ0Qy
            dUNJYnc2eThqSU1jcDF4RzJ5aVJFYk0KLS0tIHBWWHBMaE9SQVJMeTdXRUxvcURu
            emRKWFYyZkJkOGlWUXNrOE0wb3ZEaVkK5YBMalGf6d2n8AgEKaBqjBMFDW15HzSg
            kywmbX2VGpVa87nN6+eLiNx8MoiOOM1M2gaOUiwGgjUN57QIpxczKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:18:15Z"
    mac: ENC[AES256_GCM,data:C5scDfdZ94aak1C4ZWyG7uMRWL5ZWKNCujbQyU/iVMam+n042yI87kDi5o7zzryuWdXdU0bmEUP9tPbfIwXNFBDaP8ouZV0F3RUrLN/p3g/WOXxVjo3G6DqcuOVqO49EQxY2iFTeE+cRwhtY4+I0ZFGJ06J9TToPBUz+U6p6m5w=,iv:LQHYn+JHf6qVJtpdojUTDZRxFwERVsourJMLJFispPk=,tag:Bz4e/iPYpbm8agP5e2gWTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
