apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq
stringData:
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:QrNWlWi7ckzNYyBpU6CWcG6ML8nevxJC6mhRuECkmh4N,iv:RZhtgfWFlELKHVT4RHq/iVFPuAwh7JuxtnlQBvz7VpY=,tag:n0E8/MzCO72iGW2Np2rnwA==,type:str]
    rabbitmq-password: ENC[AES256_GCM,data:JUlcvk5FYL0869Tm8ohzhQ==,iv:Ze9rf35+2Bls2Qh+MobgkgwT6SNezLQa00ilxGZbabk=,tag:yumKIOIvprD66d2YGt+zpQ==,type:str]
    rabbitmq-user: ENC[AES256_GCM,data:yO4sZ+7loM4W78JRdg==,iv:HSwdCk6gd+FnetVfaNAL7OtDgBuNofW8MK2fK0P5T+Q=,tag:2JCKdFIRYo6vr/vdezaPdA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVFBDZW10TjBBRkVoSjUv
            ejZxTnFSR3VvTjZ3Z0Q4bUF1c0dFY2I5QkF3CllpaXJiZ3dQOW9NZlpWWWhmTGtm
            R1M1cklhR2hYZk1jME5SdHJoUzZSaFkKLS0tIGhUQmdNU0Q5QjlLaDBwc3FMeVRW
            SXJjWlhrSkQ1S1hsRWxEdFhZTGZVQXMKU5vmrISqOVGQiPwClEOI7dLvTZpoV47t
            WVB9iZaCfwq4USp4yBkv+Vmt7W1L6tELx/c6AHN0uZhzjh/lRQnIbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:47:41Z"
    mac: ENC[AES256_GCM,data:o0uLvrIOTuIqiDjuz5vBPZmGWH/zPeKuc67knyeG3GqR0V69OUUHY54W2BUQn4njBa777O6IrVLMOVDrGwDIZhXM0F6SzJnn/aXok3p+TcUB331jukBno6u+p86Jprd4934ZAn0EYpgoorG9uYGFxTDMCXre9fd9fqer81l/CzI=,iv:rKpx2iS/VXoZKog3UJQfawU6smgSUGgKC77+Jcv9Orc=,tag:L2kQSvHLjcD2car5x7g/6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
