apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq
stringData:
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:UpmyvSQgoH7fXF6f8FNiz3U1gEugTRcG2gNYYWphs2Mx,iv:xwlr9rWytizOQIwMOx+1Y/jEKk3EXl12t/dkA+SVz0o=,tag:DhBWU1674L6ZTVOyPYFhRQ==,type:str]
    rabbitmq-password: ENC[AES256_GCM,data:+ejagQl+EXdK/Too2E1KzQ==,iv:qMbfWTC7lgI7JpgrvIQqMirI8hswxHVlOF0Y7v4IC74=,tag:RtU1awhBEqOuvciCGYvVfQ==,type:str]
    rabbitmq-user: ENC[AES256_GCM,data:oRhY4QAOMjo8pyZboQ==,iv:05yAxHgRj6nrTA1bSWA/ZtM1h0ivh5xRXp1SR1k/Bjg=,tag:n5QOUIfw2GXwlVl1sHpjAw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSmFMQmJMeWN4Z05TRUZl
            LzByZWFSS2gxellWeFFHbEFUWjhsT2l3ZFF3CitQWWdrVzJZYjFiMDVKRHAvVlll
            b3pjdUhjcnZrT3RyT1FIVTBsektlK3MKLS0tIEtUVkJBSkUzRW5vK005b1R1dVda
            Qm9ySXNtdGZPNzFSak5FQjYzOTdPZlUKtBf4PTHEuu8PQehXwLcvs40rB0U9SKLK
            2+megmrKOYdtILjCJ1U/AZNWJsPyp121TWI52Abjtt66Q7+GQIYMnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:26:10Z"
    mac: ENC[AES256_GCM,data:7/Vc43pYhGdPIIJ0nnxzXWRzCJ2ISCVh0NJxYzKzFzJhCIbTEi6cjScP9NtthuwMvpbsiBv7s/ItMa4TNO3B+eaCFHYmSC+wvHGMxWBX5r9qdG4KuK8pWTqJtcJ9EgQO19JK+ay+G7IWz5qwp6AcB1i+BdzmObGO6gaNibEW0S4=,iv:QdwGrW8vEn3VVAo2ocSa5dH4jKOwtc3Y5XmmN1v2Dv0=,tag:cVIjjG4w+pPT1hTfzk7AzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
