apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq
stringData:
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:e5R7AMLKNcS0QB4UdSK0zEXg2StfX/SJ15Z6fH6xHY27,iv:6BRENq0Aml/Oj3Ds3By3yCMcBLGnx8GMCZq13/Tl2lw=,tag:srrkkxvA/9Lfw0ei7J9uxA==,type:str]
    rabbitmq-password: ENC[AES256_GCM,data:0SPk2gqz48AkWvEq6dnjeg==,iv:eEQePzQkR6ArC+3nA74kF3glC4xscInpS3mBKq9F1/k=,tag:FI9dlKlsFNuTj0UHEaxKsA==,type:str]
    rabbitmq-user: ENC[AES256_GCM,data:9rwTFEA13yqpy4Oy3A==,iv:iiz+bv6C3vq9EtpqzrkeRK6qilpbt8nkPYdoy/7WLxM=,tag:yyn4grg49nF+LRnl/usLrg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcFcvOFhUanAvbHFtTG54
            U29qbTg1bmg1Q1hjZVdtTEtaaEM4Y1dOdkRjCkhtK0tKQllQeXJGRmhQNU05aGRv
            SUZFck1PWkgyS2VnK2RQbzFHa2FwWDQKLS0tIGY4Wlk1aW1ZTFZTNzd3bUJRS3Mr
            dEZsWURjREhmVWdlTThHbzNYTjhuUHMKfOocVq0oKcNWVy83Qsn43VMLiFg2M9C4
            VZ/2TiH9lsyY7p7IST/6407BLJZl++SkDQOq5PA3LYR3seD4d9v96g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:10:11Z"
    mac: ENC[AES256_GCM,data:brXr0TOXtrQxyG5+Ft4gNHKyrBrMky7j677JMe9JtlUzu9Bt7mzmx5sgvV1IoUPyRylsrCuHnN8311IFbircPRXMR54lfX+GugDaHgoiWKYB1UePcNW8tHE3Cu+/Wv96QFqo7ClKjr9RoX5Ea7Y3bhj+S04SgxTHUr3ABeqBYsE=,iv:KRMDcQZYPCJKenu6cy4AIM7cs1hBtIB7qy4foV1F+Go=,tag:BeufwQjLkQnNPdZ1ZGQStw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
