apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Y/qpnIObYLCEaNZzFfhCGV+HSv//GuP+vXIdyxxLJEr82yRCbu850A==,iv:RScNEUu9Q0NOkO0I6IG6ei1JBXk+JrbLXkRkSoYPT80=,tag:axFRG0WEuyppf6W2om7uUA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbnZQaU1Db0p0akhTRnRw
            Nldkc3B1NjJDNk9hclJLejFOMjBOSHpTWEc0CmdVU25vTzM4NHVUVGxoWGNLemgw
            VXJQZTNBYmJJVGtvN0JRTGR1VnNRV2sKLS0tIEpYenV1QzVkcXhEV05Bc0VMeThL
            WmwvaGpXem9MMzRXRklUdGNFS29oeW8KiUjiGp90xmNhEZ6JZClqJq3wIQ5PGTvE
            B1DKuykB8nvI8id2thViiVJHZq4HZR8slfJWH8GzcSfhEUq52kRTDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:17:55Z"
    mac: ENC[AES256_GCM,data:vvxkrsU23NgN0TDyHzZyV7WZSQ7KR7LMnsiskpQkLpRlT5fAuWp88ySoPiymJK0pjg3G8wrQGZtjbNMjCPOK2Kn4g2W0E+S/bAnJUNITvl6OcoRtgIKBwzQUjN43WGnMHdbr7C2/7e/wt2Hhwh2FK/s0ZeToEk++wfj2wcmwXSg=,iv:/U3oGj7vk2uXo1f1sq2M4OIrZ4RXhMe2Bf6axNYQQ14=,tag:gQ4Ycg2KTU/4HMYhpkNh8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
