apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:2I/1TDywn8g0eKBIMuNnvwNzT5dJKNC0MMDdccV/SQM+PQi7CtHSPA==,iv:U4ZUmPUSL3lTdvdaOhhGQNQRb6j71AsouBqtZc3Aw44=,tag:8Qd3+I6JB29odCCq4ls/aQ==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkS3NtL1RUSEpwTUN5ckxV
            Vkh5WkJnalB1UHVVaHBXcS9HR25ybkVyQkJvCnR4VENBWlFUSkcvdEFmaFBvY3Rn
            RHpqVU4xaWpGZ2pFeStTUUdRSU1xQjgKLS0tIFpsbTNuMWMwYjloOWFobXNnMEV6
            dUtFT3dvRTV5ODF2eGhYUkduWi9YamsKhGvWvTWUFYrGdTuSekVIzACvutvXcLr+
            jkuQ5i1A9RYYX2wzL1bGnMt4k/Lm0x8hwbl5+UxcfIvMl7l9DEpTTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:25:40Z"
    mac: ENC[AES256_GCM,data:JC6kXp79YQQRsTp5/AnYFpmWrUXPaA7KBf5x24h+oJ4/xYjA9K1ihYlbVCRBtv3qdtocQuCifZil/bC1FNu1U3DUwV1+5qe8spqgv2PUiXu6R8+U13TumRUwsq7c7zzgEEkktLZ7RzeLbnIKk1BdFxxItxpSUij+EyF0268+96s=,iv:8bvHrzYa7UocYgNUhuzsn0oiogylZZpj5jmmRQ/ahKE=,tag:3ikq22bp5Kl4yF4iNqi6cA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
