apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Bm+wpFm3TigLTMq4/GAmDiD5mdOy71ajCcprM0RpABEuRz6Ts+dQZQ==,iv:m2wJv/18QonYrSp8BaEOxl3klvkmUN9uDfEmGmGQmUw=,tag:dAtnKWMlPVHM8PPpAmKWWg==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbUlqTkZ4a0tmMHdvNXh6
            V3Y2ajVBRm12ZCtJbzJCbjRnQ1FYQStrWHhJCmFzVUErdG9FTGxYNkJQajV6a0NW
            SVdtNW5UalNYQ25EM3VTekkzTmd0ZXMKLS0tIDdwdHRrWjYwZGM2eThTM2trU0NP
            ZmtDSFpBUTBvaHUvYzNxZkNYMG8zakEK0+l/HrS6cV3lWKlSy8qUlj3mSqtiZsCk
            Si/ATNm3Rcq1X9Xo9XLSgDOATnIl5rPlY0UVFMuZYltKe7dZfsWyAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:47:21Z"
    mac: ENC[AES256_GCM,data:/dB34YH4zTcc1eHgNXtfU/Em8GwxkpG8OoFEaMq8k9OZV5h5vo6KFDUuzJIv3LoGv1TbfBDFncW8PdO2t/3+dTn2zFoIEQPex7DxVszhni0sRYedKQ60d3AKu8KvM+2xhrivUguDeLhi2H1+6n2ozxBqY2yKDjGXnn++ao6goCE=,iv:gwFftv4hdRZ1clUgODjaPBqGtpeMT1wQk5mMyGbvefk=,tag:PITpeBdtmqpK1URaGbTstQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
