apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:cadHzEVR/9QokDDrC5V759bv/frbIFKB6F/SHB5PVDCxX0xaWBbbjQ==,iv:4YW2YHs1dPz0jCJzjw2Pnoy9KvMKV4VtX5UUKl0MlGM=,tag:LEhaZBQZkXfQufC6cpvlPw==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweGFlU2l0cDR0ZFZiUlN3
            dDVxdEo4eG1XU3ROS3lDUFJzYzJFaWdNU3dvCk9IbDhtS1BlclN2L01ITmgvaFFl
            ZFQyZ3ZBR2RzZmJKcDM3NGtJbGVKUmMKLS0tIGpneUtwdlNrOWdDNldySXpYbVZn
            c3BSNyt6OGZjYU90YlloWldWRFVLc1EK7jqQ6CE8Mdvd7DF5ML/x+qQzw0HC/elK
            J13Tzlj5LZe7Wv7PqMXCoZ3ruK56BzjcosrmsywOGPg0YVlkPMUJpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:04:12Z"
    mac: ENC[AES256_GCM,data:UeZmAuK8g2h9hhMfCH1z+W+OCs4TqlCQz+jmxuMyuOouZUunthZIB/wJDDq5p4lQyuoZY/psBP6ZlpgE0Il/7w8PxqfIvUkjFLhVKJArF1AkmrT7cMCYTSmoZrkeG7gemsK8OlcrY3FXQjsljohwCr39plnm+mX8GfrS6rW9zRs=,iv:ipsQzQU6szZ/2+6S8KkhILDUvpJj3Mr6xn9ETchl7FI=,tag:Yca+FM65gFvhI8fDrwJqnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
