apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:UOilF4ZQr8066LzRbfGyRB0dYKqZ63H9aKMUz86z3ap+WnKR9DieNA==,iv:1dHZJOEW0Pgz1VNoRXwJXq/gHKjWQtR5w+4xaITg7iY=,tag:Jeh+AFOLTx1nz+9cudRFFw==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRi8vYklWYkVXbGVMcGtL
            VkNhQzkyeEozVVRDaEZFUW42YVdFUjFNMmljCmxhTHd1c3FZWGdSYTRja0lVNURx
            eUxPeFVvTGpPYXVtaHhzS2pqR1dJY2sKLS0tIE1Pb2wxNGZSbHRnOSt6YXVtQUZn
            Z09JQ2lpUDl5eTNPNm95VHJlaFVhRGMKMt+yao0gtKELtaVkIVih/05pHKNVs+XV
            MlwFpt14rm+FnH6C+oDesHR8nQU3dTICQewXzO+SfM2WV4vbybGwlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:20:58Z"
    mac: ENC[AES256_GCM,data:0xlhHqLP9Hd8E+m6EVsrSUbUYSNJqCFwhxpdc9yLWzsvtbBJr42BIpfmAYkZJAa7eCZZneqn1mOR106bGzm2htyc4hUiDKudgCSL38q0t3+rwMkge9NeSXxDIp8pYcbJSy/WPy4i0HYJ9r9Y2/b826+jcbCuI8cBtCkn2Dv6fRs=,iv:In1TxOJbD2sFKkD+6qZgG/egHwCMH8s29y67l9Iu3Lg=,tag:a6MwncOD37oLzU4sdd5M7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
