apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:qprtt/SldKarza74PoJf/jGcRFEHQB4LFG1jvSULGxWG1yXHl1gHWA==,iv:+IY+43kmyEA3trmLpM48B8rbzDm3ksxlfYBrCVcu9cQ=,tag:KXm0VDbGA/ftZTW0NPlxzg==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNC9WNjBxMmdNZk5FcjI5
            YlZQa1piL3l2ZlV5K0RERmMxUFVFZURTelVnCmpZSEtCaDFHNWJkYnAzMmtMeGxC
            WUIvN1laOElqZ2lRbnFNT0FzRnFtYlUKLS0tIHkyTVA0TlNaRkRHOG9USUpDN0l3
            eUEvR2hBaWppbVZMaGNxdmliZzN1SGsKYTq7YJcWap/MqS4k8eIcNgS/BlUpPOHb
            kryVwxrX37J+kwfNlI2XsMhSnHThfCHvjIWBRpTRJnrQQPUDpIsAHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:09:51Z"
    mac: ENC[AES256_GCM,data:Zdd2DCyVMfMxwf1+vo8dd7p+Q79Lygl1hAkVEf9apfuIkIqWq/7VGB3Nbj4nOhmfrucvEWBQCk/toOf1DAL8GvEOrV9ZHxWY8EL/VLoFK1FtqKN+fQvTJv1lxHGfHD2Zmmtq9MFXiB8HScslw+1dazLDFN69nahQazQ4vZHygQg=,iv:ZJxzcyGKDpxaHUTj6WCs3pBQWtszJHM8k/wgSfbnAWI=,tag:Y52DPhDgpy7ddeX0PVUZ4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
