apiVersion: v1
kind: Secret
metadata:
    name: vernemq-secret
stringData:
    VERNEMQ_PASSWORD: ENC[AES256_GCM,data:gPhAvnFkG+dX9D06SICvKA==,iv:Ljzl0p/LMjGnewLlCe7ElORiJT9gwpuogB1xhdiWA9Y=,tag:g1T9ePFDN9pNjoU5J1vV4A==,type:str]
    vernemq-password: ENC[AES256_GCM,data:evZNtnrdJYDZDA3Z6URyjQ/WFXoIMaN1/oxJDnmsAZzbA+GZSkJ9JA==,iv:13qU7b+k6xPqoIAUAIusDDXG32yitApn09uf5VIzC6E=,tag:84YPOT9jZyhn9N8nRvYt4w==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeGJPeXQyTndUT0FqVWtm
            a1lCejB1WHZacjdxTjRCaXlKbkVvYmxxbDBBCnNvZ01zUU95R1Nkd2o1VW9aSjJi
            NjZMMWRRNE9SK3VVcFhFWHhXc1hZWVUKLS0tIGdpajBzTldjTWJrcExGZ0VNVkIr
            SXNEQ25jQ2REV3I5bmpGYjl1b2tIbU0KFnFE3d3KhP9VdNmEOr30XIMMYExJAkCQ
            Cam9LgMn0vW9Segr2VQKsteGzJoGYkwA9byJZmPOBRyD6CuPgxeR3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:04:46Z"
    mac: ENC[AES256_GCM,data:O37Gj7LKe9DrJTH6ijZ2LeVxXO375V93UBhaHdaRlnBwBUpQvn+DEEE6yNFIvoXk0H4exgjku/JA5hDMte+nFXy/Wn1V5K29cJ5vWxollZygBqV5lu78Um/kRIR5Vce3Ldjq6a58Ca9AUOxTrQMPFwD4uiFyEFT89T2/wX2SiH8=,iv:yjvrJ1ZrT+g6ZQlc71VpH9EG80wC21Mr8SQ748DM/mo=,tag:ReFNYsXmX37Thvw7tlyd/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
