apiVersion: v1
kind: Secret
metadata:
    name: cloudkey-api-key-secret
stringData:
    api-key: ENC[AES256_GCM,data:C8JIp6xn8Bjjs/GvYuPbEhWT9ByK7zL3/JAllCyPLf+3DBE/mQ==,iv:rjkL/zoAFd7wf9+TH21QrHG60nhFkukcM0PLPe2CO0Y=,tag:9K/huHT/G/Xhbk/cs1Qrww==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWa0NKRWgvK0ZtMVhKWm5n
            V3ArdUczTTdoSTdTZzVWRXhIL3F0T2drTHhNCjIxWVZXVUY2RDhkbFltMmIwNEVy
            UHdvdWtBQm5na2gvQi9LTTlQZnNXd1kKLS0tIHJ5cVk1QlNmRHFkeVpKVS9CeGVD
            WWgzYW5tT3pNOVg2UzVzS3hicVE0ZDAKgT5GYmyksz4jl3wYBgVyHD6kV3BDT3/f
            tBMI+sWaDYNdfCT05eRcozdRK4stYTCIS46BAHkPVlfZGN5Vps8CfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:04:45Z"
    mac: ENC[AES256_GCM,data:cOqtWjc5s0vP9kZ5sJdp8pBtC8m95bYb+VdCp4HWQblkgEhgPkMlt2xFbl7LOyQrbCRcg9yUhGgkVHQAIuepYur2rUXdbSR5Kn0zu3//bB0z5N5rXkE1IgfiTH/A2wUrbo3lJhRl+u9AIXULQavXFIgry9N+Yv5mFZKuuZ9SAZw=,iv:zfsmjRg6+KUR0UUEKo5oXs3pxY2SkEwmpfKKK03EKuk=,tag:nx+kw71L6O97Ra5zTLG53w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
