apiVersion: v1
kind: Secret
metadata:
    name: cloudkey-api-key-secret
stringData:
    api-key: ENC[AES256_GCM,data:xkQRsswbRGRLnsunTVIHHI+RnwzlvCPesxAKJdPBsobOJwffgA==,iv:s2aL4edVJuAGkq4xAZ2jCOB/lP1ZvBvkAayA+1c1inw=,tag:UWI1eJB7ZdkYBuyh0gwC5A==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeTB4dWxOb1h3VkxjZ25q
            aFhCMlhqZzBTRytRVFFLVnk0VFduckFSNEdJCi82TG55YW9VSytIOUcvV1ZidmVQ
            QlA0VlYyeWRzNDhmVEV2cHRQZ1NhcEEKLS0tIFdvb0JkSVdQWjY5Nm9Objd0ODcv
            QjZaKzNxZUVYYi9tOHQ3MVVOa0ExVmMKMoRNbkT9S/XiKJxs8Af3CaAvDYRjJkNP
            nIjTuMximPTAwid2dH07B05Bw+R4YFz3SDEMCpaJ7kzTOe5bNGPaMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:26:23Z"
    mac: ENC[AES256_GCM,data:vuHO4RXOQhDfJ5iE9YcO+rFWUCT9vBMVokvA81j+p0E1aVkL7u/StK8UQLEvdW9odkPgaqAe/Tqq8dqZpPyGbJPtC4Fscn2seXajkVIAdvSz46B8uqUHTf2qxU7L5lx2oKKN63K5VJPLbUEU+o1Llsl0idilCqBf3CAxVtWKQTQ=,iv:yrlFMM1j5zaJevn35D30IJLzx4PNKEsPLyaucUQXfX8=,tag:IfYk5UKYl+X/5BWaR6etTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
