apiVersion: v1
kind: Secret
metadata:
    name: vernemq-secret
stringData:
    VERNEMQ_PASSWORD: ENC[AES256_GCM,data:OptKXrmzSSeoXWAL1S7heA==,iv:aZBRcBzFjZvnn1YSWvMTsdW5r1fgm69bCUfjQmfbYRI=,tag:jGI01KYzG/KJI8kDEstBPg==,type:str]
    vernemq-password: ENC[AES256_GCM,data:qJZTwTqKILAZDIa6Df3hx7HAC9CoESQwIOBwj9NbkWedsYxYMlcPrA==,iv:BVqjXpRjbPMaPC3iBpjNFZDWQ5EI6sIUihfFyciun5w=,tag:3RgMOKE8OzjrPnFSmAwwag==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNDVScDlQT3VOOFN2cjQw
            N2Y0MkhML3V1eFFsQWk2eW52QjVOd2FiU1hrCk5qM0dMYml6K0ExTzR1RFZxbkFS
            RUR2OGt6ZkFGVUJiNnRlSWJlRS9mSE0KLS0tIHVIRjNHYk1vVmI1MFRtWDJKWFpO
            OFE5WlFPdmI5WlIrbFZYL1JoWk5wRjgK9z21enACfpPaSqhQ6teRbRX4mFZP3JjL
            HULhP0LqHoqk1qY3CwTKNER9rtxTy+uwvajr6fsgGqGwIukgab4znA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:26:23Z"
    mac: ENC[AES256_GCM,data:SxMlpH0w+WD053YbhbEFWpc4PvMobFJPFvhB7iR7uuQ5iuz64NOqr/9BmfAwTQnEG0nrTEu6NScOYYIddd1qqIxrmRv1noBZoNPem4Q26Hr3vH44pGuSO81KzWUEnaMgUqwWDvyJVoPx5zC7YYm2nIUydSZq7tJma38IyTHqtTw=,iv:507DfP03uAa8ulV7LkGrwZHFRzw3UcUFBEvnJYiNuhI=,tag:GZumv7uJAuhUMNrsHhyTjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
