apiVersion: v1
kind: Secret
metadata:
    name: vernemq-secret
stringData:
    VERNEMQ_PASSWORD: ENC[AES256_GCM,data:H3P0fxKohIlzVqa+qx6E2g==,iv:VtIlnN7JZDiHoZjZtIy5afW9Ar6UuW+ISclG6xdgUzU=,tag:sWPmKiUFKb12Zxs6/5Je9A==,type:str]
    vernemq-password: ENC[AES256_GCM,data:EsnZCEY61uXEN6TIkcfGnZ6EkptgD2fqnqVm4LFhwQ/EwrofwGVdFw==,iv:FlC88f6ALpL0j7vFLwfqm70+ykfpfsi/rAOHaG2Zb18=,tag:dHzGuNKbwckdPtCxViWQFA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVVc2UzdWNlhLbStEYjZP
            WXFWNTBCOTBsUUZObENyV0lZazBGTXo2Qnk0Ckh4K3pwUTNaaGxkSzk4RWk5bGZl
            UjhhNCtxMmJBK0F4UXM4b2Jqc1RiTXcKLS0tIHNuUU5xcXJJN2VXb3pYYkhxTytW
            RVc5QTY1M1pKWVpWYXlQc01GcXpPemsKi117AQQDUFTvII6YBOwkzJ5ntlCLB7Sb
            KjZe7+9jl2NH4r8hXumo3bzOi3fdr/idQuKzGsuQwdxV9+QKRwukPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:10:23Z"
    mac: ENC[AES256_GCM,data:uHtxhDq2m+wGvIwqeaQ0gshRdm4nojYKQ+y2TS9mlKSjFXNFk/lvqpzdwO0JB356bJTq62hr/2+2/OmYIW6ZHpA1+jv1DLNuzchm/6yNqmaCZ3AFj2j26nfpQC9q+Ih2ZP2p0c2ZUFgeCfeg4cX+r1LE3/uTUGzbXsXecd7XLpg=,iv:vIG9fBL+6HjO0QXqPKM29iFl6tuhCurTwpdAqzm8bw0=,tag:OoiR2dNkCZLagt7v0Ed3Vg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
