apiVersion: v1
kind: Secret
metadata:
    name: vernemq-secret
stringData:
    VERNEMQ_PASSWORD: ENC[AES256_GCM,data:tz31VgXW0xxpsFCPdCEzxA==,iv:9uVA2Cuy2O3g5x4ej4Pq/QI5eYmFO6VxyYQWh7kEjnc=,tag:WJhyrXeZZEMTFU854os5Xg==,type:str]
    vernemq-password: ENC[AES256_GCM,data:HY28w2dmjOXONJhDNoNfMJZ6erN+gpWQ0yIfZEHhZ7T4C8Ks8j6abA==,iv:1sio1ACpFUFuxJa5Gz4/jpkoiN5kpD6TJvbM4+wcAfc=,tag:TH071HvfvNbNLhrXWCCntw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dG1aNGExRmRydWRKNSta
            cFk0WEJFVlJvRzlxVzRkYVRDZ043M1FzOTJNCkJLa3ViZXk2UTBKQ3hoQ2RwK01M
            eWEzMlBaSVVaQWo2cVhoWlBPS0hHQkUKLS0tIDRTMkI2N0c5T1lxSUZOWTNRb2w2
            VXh1cmVJN2ppT051ZnY3azRJdllBRjQK0wSmmGMhzXsf9q6aR/CQayuebegWWoc7
            RKNBK9EvWrARSzJ91Gu+DQIsaNJ3KOwaXRLcfgRugnJn4NLI70KXuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:21:32Z"
    mac: ENC[AES256_GCM,data:CuSDOND1GwyG5d9xcjzyZJega84ZczKCZVkVnFu6M8nDAFeZQCLfZj6TsmH7ELjjstRgblDoZf03WbWCCHbHufCfIdwu2mMsDiKIBe/gaVN5V69eRS4IABtY4yXPDMtOe3UhPxkbi8hzoZzyj8sD7WMmyyQMALcx19bOj5TpZug=,iv:pzE34vcOUSBn/BbgmYSl6OzykYm3XHWVEVzS/oGnnqw=,tag:7ElGuhjgohqq3DNLwiqKYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
