apiVersion: v1
kind: Secret
metadata:
    name: cloudkey-api-key-secret
stringData:
    api-key: ENC[AES256_GCM,data:rVAOvX4MQLvaKNd8eepxSNhgGSfGuLVMAGZFkn9IHH5FVzG3VA==,iv:YpDPuEqRC9nulwB0uPULk4DktvujQt+GAw+HxM9/XJw=,tag:a+U/zs8lTVWVfRUdnxN2Xg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MHBvTWJ0c2ZTbTlaZGdK
            ZmNnNk9QOVJMSnkzQ1FHTS9mRUNvcjFINjNvClh0bzdwZ24renVweTdadFo2NGRK
            aUVDbUJna0NTbC82QUovSmJZRXN0TXMKLS0tIHNnUXBhU0x4dnpkdFFVdE1XTi8r
            T3NFT3hhMmtvYXhVQVAwQm9TZUh0dE0Ke8+wEM4Zw76poJ06D781Pbk+VlTa39Br
            29JPNQrT5hiQPYmYApYCjjq9DkdOErt+tWiVZthJYYSlqlgbYvdI7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:18:24Z"
    mac: ENC[AES256_GCM,data:yTKF4FBZ20WP1kSRcqV6mP+kGRDOTo8K/vN10hCuxRQX+/dUX36RCxvkQtaNf4RVJArFD2aM4UnfpDabI8tJULF2lH6ry5UdglxBVnJR7VO8e9UTx3QJOfvNYNgk8jJ+F5k5ta+WA1CZa5/NEHzXTyu+qfbEpTCrW2mG1YropeA=,iv:eqXxLtM62jr8/an8mZNLjUQ2vrSTG99TuZlfsFgLvLc=,tag:WHs5Rbf4smN0QwWgc2w26w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
