apiVersion: v1
kind: Secret
metadata:
    name: cloudkey-api-key-secret
stringData:
    api-key: ENC[AES256_GCM,data:f/PIiR7cMkk6QlfkfViV5pKUJHsVXf/BSllro3rARhuZr0mdqQ==,iv:uoNCig//+rlH+U1tLBfOld+zkkrD75oclSbgmzhYZF4=,tag:8StuNIND61qDucn8LW5flw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuS0M2bzV0RXJHclRRc2xq
            clpIZElQY3BxYVhKTDFsMlhQWE9abmJoQml3Cm5LTDNOM21BcDQvcFBWMVNBWmtQ
            NTZWRU41bkRCWW5vUjNrZzQ5aEpBK2MKLS0tIEZDV2RHeDVvV1RUOFhGbW53cGtx
            UVczdFpOTUsvaTVHa0hxanZxYWE1ekEKfy1ko1Q4lzRUQJW+fkuB1S2zQZQ2luNN
            IK828dtADnp7Vz9poeuZ6EzzRc6KmhlXAXKghI6z+wsh91HjD0oveg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:21:32Z"
    mac: ENC[AES256_GCM,data:l9g8QckXZdA/7S/LdtfVDmgAEjI8+HHEcWbg24B9Anf7Ujv0JvS5PpTdAaoqbD9pS7Uw1IazcJrkmQDQ2GRTg/3bjoIc91KSMDQ4XtrhtLenOihYMKyVXqnoeRW+Yqee7xyDT7botY87jgjlD9RoST0vNVzDVGPRb/7Mj9DgL1Y=,iv:wiLCY+5yBc7ZzQJBeQ5PuAH6mtmqvUFJmGP57eQmkWQ=,tag:c3CSxkNerN/sawIaQAWLgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
