apiVersion: v1
kind: Secret
metadata:
    name: cloudkey-api-key-secret
stringData:
    api-key: ENC[AES256_GCM,data:Va+iwsO0nLRm+WwpspcUDYTJE2saG81rr6AvWRO/g964HhsIxA==,iv:wdaxdsaOh+Ut7FdaAGtHtk1oCDjQYKckjBpAbJ4Cai8=,tag:oyj+hl916QT7+ORnZxy3mw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWiswUWd4enlzU05kc1pu
            ZEdLVklnT1p5aGdPUmNrcDltb2d4L21rVWdRCjVTMUtSZXplUExaQSthdFVlZERp
            YkZIeUZ5czVJSWIyeHU0TUlWekNZYUkKLS0tIEZHQTU4aktDd1dOeG1PVWhnamR5
            L2hCMyt0WWJwNU9uMjVnNEhIMW1SYzQKyy//W+G3QQC8Zkumiw85x/8z6bboEpJJ
            pYe7oQY9SIDvz/jnfHHM7kZWupooDLD3QWiObAsekjgUIUaG0s+f9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:10:23Z"
    mac: ENC[AES256_GCM,data:GSxqoYyv/gl+7BSsRv8g+jS6VvL+GTbHKdarU1q3IR73XgiMJ46e9mG0K6og4I2uVM50HjVR7yi1e91F/1rsfw409pWgrsMtns2FUCIlOGbSk6tRn4RuWd4sElo/twsnbFllIFdpBvks9PnAZYJn7IGCw1P5RRJHcmck74Rc6Zg=,iv:91wk/J0bmnF2CEQOlK8F7KreCnRgF/Uk1qysxM+FF8U=,tag:93B4Kjk707MNyqNIWV8EvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
