apiVersion: v1
kind: Secret
metadata:
    name: vernemq-secret
stringData:
    VERNEMQ_PASSWORD: ENC[AES256_GCM,data:exVX8rEnYA9qw1xGj9zgbw==,iv:PWneVP404oSo3nHB5G0pmv0lwLFnwhKQMoVmWt6KzOE=,tag:QndItBfI849IpEQtN9oaXw==,type:str]
    vernemq-password: ENC[AES256_GCM,data:C2wGM/kHbdH8xr3ABs4gKQVKRk6YqtiBhJo4wF8wjbksIEDpzumJRQ==,iv:1jeLQuQxCfDhQyeQ2s+2YN4iSpqgqfmEpZf5+MCx3KU=,tag:OyEEzl4+u3axbf++yGtT6A==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUHFTVHhZU2QzZHZQcDhP
            STk3Tk5YU2wwS29HN1FMa1V4Wmc2UkdrdDJnClVBS2tjd2FUWVZ4OE9uS1U5N3B5
            TE1NaVpvRXM2dk9LOGNRaVRFd21WR0UKLS0tIFhibk85U2hCNWdrdWVla3dZSnBt
            VkVKSytYMDQ5R2dseHpjay9vcWVBd28Kncitxho2YEwb3LIcwCbHcJKA5Y3WDtxn
            htC00FcslnV9vrj7IgHulG6Yqpqw13TDpb/ypF8PeqLWkauCWauKBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:47:54Z"
    mac: ENC[AES256_GCM,data:M23NNEq16NparXZc61hfN+b9Oy/0Q0NjlsfcHPqKAeAWeaKWTPWsGOd5HK97FRA1u/RRja3GhU1JVlINnc7VbGV/gXY//pk1GLu1yoj0kO8QevhwAcvFunEMPN5NiQqBWTkjWvBGUMgDmwimf3rhRIWOfBQWdD+57dcx4TAGthI=,iv:bk1/EfaxOXYBn3oA+2vTyFGVdCxoxrwRUs9xgXqO0Vs=,tag:Ro2C1qzCRkyCVKaSfBObUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
