apiVersion: v1
kind: Secret
metadata:
    name: cloudkey-api-key-secret
stringData:
    api-key: ENC[AES256_GCM,data:NC/ZcWcg9lLU40KY1g97r8UdwUK9vhB4Z0SskcyK9HMwYDChpw==,iv:Qga92jB07CZ5H2jyAbf9xjAB+meruwMubgOmkWTvcBQ=,tag:Sq3RimxjJzMGKn7BYY+teg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NzRsdGNKTWkwaHhWMEd5
            L0VLb2w2NDNBOHRCTHNjdmJRSjhiVkp3eDA4CkFVWVhxbEhjeFRsMWhDZ0wzZXk5
            ZFJzYUZ3RGVoWVNCL3FRREYvbmFnSXcKLS0tIDZueGN6MkFLTFprOG9yaGV6UHpI
            Q3dWbWNWZkpMRGVNNHYvcGZjUUNmdXMKL6kLV7H6g8QErZQaNleXXrlcTiWsd7KT
            m3UDUthoad46/EVEuHnrhDR/rk4wuc/lzgC130BpEcDBhQGP7xPjxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:47:54Z"
    mac: ENC[AES256_GCM,data:pg9ZuzMa8A28Aoc1cdAkoqCC2SJslEDq8szI3KkBI0CFwZB0FEtGjWXPbWd86rsdJYqx+6iszq999R7BSE4+wGD+kXlEF+FYHBAcFHs5xzqOw26HBr19HgtoI8iEBNY2CPk5XYqqR+DAsi2EMAQ+OpA+EEFkM8jyO9Bje+RO7Wo=,iv:MKwCa/7ao4EDEPbdwUuctSQwt/ncQpj521pCp3T7sa8=,tag:Lbz84ZTmHxeBUa0N+YBl3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
