apiVersion: v1
kind: Secret
metadata:
    name: vernemq-secret
stringData:
    VERNEMQ_PASSWORD: ENC[AES256_GCM,data:CgKl9LMIIjGbTEDEHJK/gA==,iv:Ump7ByuJNfyq/h/WGaz8+I49ygpPH6V8N6zGZ5sGZTE=,tag:r0Z9jE7JG2KJiVQqo92nXg==,type:str]
    vernemq-password: ENC[AES256_GCM,data:00t36JrtUPTJpB+wg1oNG/nJIRT4yVV4ggdD4xvwjKgGzw9RjSw9fA==,iv:P+8ekcR0kAp82dfL2VFNfN3tC9FktVqvNEPGK0cmGF0=,tag:o16wZPN3AjzGOqtd50biXw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTa0FEbmxkRkJobllpVExR
            RVdpV3RqS25jWEtEWlpEZnE4UnhUT1lJSGpNCmY0NWsrUWtGZTlzUmlyTUJUYmMz
            cHpzOE84dUV0bklUeWpEYllTL3BQZjAKLS0tIFgyamtCcUtYSG9COCsrc0ZQbHky
            MUloNnNObk5ZeEZXZVF3WThhNm4xWGMKlcROyo8M709EcPffhV9EcjxUc3Ja2Bbx
            ol+cC6F5lBYsX4Pw8ACtAi04G4YzS/v/MzrfvJhXn2PYP0GN5yCcsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:18:24Z"
    mac: ENC[AES256_GCM,data:sJr0Yekaw3NIRKowtFqeiH0snvN8P/7b9iOQxw3f4lus/a2sufdrk6Z4vLI+d9L7AJVrXsJXaLSLRMb60Nczx4OMuIECITTtVxeOYDkJvV0wQcSU2EHW00A+QY9cfgluqtSR14AkrNwqE+L419AoAzYaECOSD4Tirf8XszSbcCU=,iv:4gFJJsBK6VBxyWSKWvS6xbsIRaQuTohuw49Pj5q/deE=,tag:Ojs9ltkT5YGGbktX2OEMIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
