apiVersion: v1
data:
    DOCKER_VERNEMQ_USER_VERNEMQ: ENC[AES256_GCM,data:F7BzAQ350EHOhaX4Fv3TIQ==,iv:boJxzYUMzt2Yltf1gsEDRvKOqgEkaJYTX1DPJ4vtyK4=,tag:eLjMnbtQgU6aABRTUlhs4w==,type:str]
kind: ConfigMap
metadata:
    name: vernemq-map
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTHJEUVdwdkVFdGUzbjFu
            Z1JOLy9ndjNjRlQ4czlOUUEvRnYvZHFTNFgwCmJBVUl0ajdROWxycElJYlIzSGFR
            MnNpVGJ0TXgrNWN2ODNqenYxS2w3aGcKLS0tIENJTmRWaHVvZ0NLTTBtWkNXKzVG
            L3l2UUZ6Smt3SXdPVVNZTzNVUUxMcjAKkgALezeBMczy+015iko2MVEhsbdr5pBY
            6D5xh85L4BRutF/B9ExsOaVs/7buip+K5smPRCClLyRGofx9hxGUMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:18:24Z"
    mac: ENC[AES256_GCM,data:L0tsOpY36RY2a02ocwwFf1J0Hs3lpCUU7ymKOnHzp5KqzzSe1XbQzAJzJX2d5ze7yk+5hAKgyPpwSdkFj7SjYhIH+Ph6kVS1xgMfoNs6KRmSkgznkqrV+38JjeMJFkNdk3ILKdv3oe7ovZ9b+mGPlL4VLw3u7dL3ZCeepmCoY6o=,iv:Rb+U7cYlkIzAU67dst8+ugWS+c9mKoSumZDRZot8ZC8=,tag:1s78XiePBVSZdZCxKDpwlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
