apiVersion: v1
data:
    DOCKER_VERNEMQ_USER_VERNEMQ: ENC[AES256_GCM,data:6wkl1c71KM80de/vrWlPMw==,iv:RiLcvXn4ZEP3jnB7AYJGrzmxbiHu8u0VxzgM/R3fvkg=,tag:usKEzZxIEdMXxmNP4oHBDA==,type:str]
kind: ConfigMap
metadata:
    name: vernemq-map
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNVR0S0x6N043bjZMaE5p
            bS9jMzZsdXA1dFkwbUZTUU96cXltZ0dqZ3pRCnNGZ2pka3VPbkh3UERlQVJZWFRT
            cElBT1JuelRtKzFhL0xpRFNZT3ZPdWMKLS0tIHl6VVNHQm1pWmxsaXhVOFNma3ZY
            L2FPamJwMC9xSnRMV2liTVcrT0dBMzQKrPTpSTDbMw6lzHV9+sI2SuE9bUTlPZ14
            VtThCFRFst8ZWZxziTv9EUgNLAGexleVNA8IDoDHmBqORDGTgaJPig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:21:32Z"
    mac: ENC[AES256_GCM,data:joaa80Ly8/xJCnKOIA0QlM2ZTpa2kOqShmHLmOIFZ2YtWZEXDvi1U3Y5lY4A1NBwwYvoTvecMo7q4Ya9iZMV1B43OWQpDVup+k8O8ttxMcHaUnOi1bS/fmMFxZKHxxo2RyRysuUQ104Fje7Y4auBgZ0erBEHyURusrRuP5940ww=,iv:J8T/vZmmg1NYQxDZooY7OX8I1u55keMfpuOME3P1oO4=,tag:Eb0osJNtINFfsCf5XBq1pg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
