apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:boEmYEjKC91/tZev5JNZJ8jqbcSKDtO7qvhlvQuBWtQILJrgTwKMoA==,iv:8mN38FhclnnmcvoLHPPuwtyiKIUsqR2i+HTvurScklU=,tag:n3vhGMvrJnZm8QPralEavw==,type:str]
    username: ENC[AES256_GCM,data:c1iOv4I=,iv:kp/62W2J08fQzOLH+txSoR1wZIdge9dy7Paf7+F3TAY=,tag:TmxITtNKo2H6+A4dj0r4sQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNjRUNks2RFFqN005UGFL
            UzVHMENGSkczNXdmSEYranFUa2NwOTBwVEZzCi9JRGZjODluRUYvc09aem83SzNU
            Z1J1L2t4RytrNjNGVjkra0EzQWdtM3MKLS0tIEVCWnRvcEk3Mit5VEp2ZWY4S1U4
            Zmlyb0UxWjZTeFNMcUV4ZmxRSGd5Qm8KaKymp2r71zf9wu4YzzGJxuqPckUjtoMP
            plKFoL/JzAtixJUHsRGOKy1DXL96nW/dfvT3lMRXXwG1G+4nzkqtYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:10:39Z"
    mac: ENC[AES256_GCM,data:eb+8BafvOIm00WHaj81Ww2uXa994vhhwMGSt900OO6Gt8D0Psxe7P7ePpXHsejxAl5wu5ycp49QZAkalhnUnHM5byYSA04xKIbVx9FkGkxDdokgO+67cfUcQBGwOOdV1axYCYaWE7mwL3yvwffU0lqnCsqBkxuHZlJjjgXFZh5Y=,iv:pswp0jWKrXqZMQnPkrmXoNhZrz34+E30CSnNfqY28dA=,tag:18k2U7hkZfflp0Ud2ZeUAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
