apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:jjgdeOEDmSDgxqV/Kfn1WtB8z6LpSllfkF9P0VoLR9mQ+rJtjkImgA==,iv:Hg7iobYPxPFB7os10nQquAQ9shWen8WW2fRAjdLhsbM=,tag:/20ZhTWn9wW4kAtrGy3JUg==,type:str]
    username: ENC[AES256_GCM,data:WgsYm8g=,iv:lekai2whwbXNzKGI+9eWg7b+Gud/KSR6oj+HYmI5HmA=,tag:sAxx8YfVnYeuCi2s/NSF6g==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOGsxbTdZcWhJZllJb1cy
            V3ZBV2ZmY3haMWFDT2paL1NvQlUyZ1BNUEg0CnFOMFVGeXBQSGdUOFVLTWxmMVJO
            am0vUlhSQ2ZYWllmMi8wWjRwZVhBeGMKLS0tIE1lbFNhYVpibFRaTU5mUXdIUjhm
            dHNvOWRMTVdLSTYrUDBXVHlrdi9WOUkKL3am5n2koJBIz8XSsyzs8M4VJHosuWvQ
            Km35JvJKX+bgw/2egkm5etoJkJmesHjID67mE7Cq9hx9iWgruCKvYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:26:39Z"
    mac: ENC[AES256_GCM,data:cA83wSULP/v20QgBb7rQNcJ+25E62IseaJT0PVRC4v/D+jUFpihVfZHG3kSC95lu/jvXR1eWqayq/KwQBtIgujvQN1BY/emQdJtY1uLDlUUfi6/2mg06VgD5HlYCg4zlil9J1sgI6/b33p4LISSGE/O5sKB33SkICPvAWesySSw=,iv:+4pQVGXnTfGTRTfRkWRrEPxOXuvyRh4mSkZobhufdHY=,tag:jDOWZV8tMDKHbu6zONoiPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
