apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:wLqM41+7RivKtzfxnNL7bS9yQC55UK+BhYEo61wh12zhAeJo7Cd6tg==,iv:ceQ1hVsprhDX/j+4ZrdHvg/r8m8GWrzkBy1NcBKkU/E=,tag:qlxlSQhfLUq/LEY7x7Zyrg==,type:str]
    username: ENC[AES256_GCM,data:j0rFyvI=,iv:up+GoKL31F20pP2FnfxaG9PtD9Sjpp0R2Fbrp4wfqwg=,tag:+0Ac3rkJdfXoalPK6cKd9A==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTDVHWWRzWTJnTExSeVJY
            bFh5QThQQk9nbXRaWmdnaThEK3ptcGUyUkZZClpXUEhNVDEwZ3I3UDlZZS8ydjdi
            dVMza0duc0dBamJsREpENjdYVFBvRkUKLS0tIGpSZHlmblNhenczSXBHblIzUVlF
            Q05vS0hWUk95dHdtV3BIYU9xRkw3WnMKBbNULNlT44hFUbyUFiX6KofXuJ6fY0T7
            LOOGq/W4z6zOdYeTUbgXx9q+4a1p1BlGtIiJ/8zj3K4rhp8HnTmoYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:48:09Z"
    mac: ENC[AES256_GCM,data:Jxv8lkDfFdPtrzAlEfsX3PKeejlh90mQdGI0nMdUb5nnFOQzTer92I+ctyLKvv8n28cV/LrfUXoj2r6b4bSoiw7JpTQTOhJWcLMlYX2grDpTW0Ngj2T3fss9HCo64cUFIP1nvbv1Hj0zSzpJqSXHQxSgMvKz0Gfv+kElFiTbkxk=,iv:Jxmq+0I1FdET0msGyXoygVeFgGiyF5OeaFumfXaT5Ug=,tag:F5vppUBirRk5rMekBZXt8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
