apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:Sl0bPa1KJlDmmcETyTH2mTi6m0qC/f8yHnxUAWXBSw6MqVOwObuytQ==,iv:CMaFhOroQv942rOGaJWlNxXtIheU82wqp7pZOWfzvM0=,tag:8kgqHfVmcdvnkneHseofuQ==,type:str]
    username: ENC[AES256_GCM,data:GBwMG+o=,iv:8XK71f+uh5HgMQrEPp6yXpekzsHope2YiOuepxbiz+U=,tag:lYffwHWVENP6KbNBUAV+9A==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRmp2Z2xLNmJWVGRJU3BG
            THk3Ni8xV2ZGRE9US1VRanh3Y3J5aVFzcnhVCjQxOUdZSzB5TEVWVjlCbnNMcVVm
            Z3RuWlZMK2ZuaVlyaWlqU0Q5SkNxdUUKLS0tIEpkeFZhZ2prSUJ4RmhXRndXcXZO
            bHJtYXZ3bG12ZnlDM3NOWnE5QldHRlkK5V+M8RQkmV4y3u1fzcs3fNgG6J8N90SQ
            7dxRF0CaISvNh425EgawCfTnR7U6PmJKanLImSibLPzQ7cFnysJy2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:21:48Z"
    mac: ENC[AES256_GCM,data:fULZD94SJJ2MbWkM+hDTE72N0d3evGQk2XZhe4uJltgWHBbstKitMKL2NYHkPVIpelrp+ac577uLCm1jzjpH3MsKyWkEoz4Pe/UBgB8VUmzxi+ePmi/rHC4I1SYelRAnhCucO/nA2wKkxsPX4E2uDOdpqA4sr9Ogeej1u1Ii+/E=,iv:4fOc8DRtgzCpO/Rp4D7Qkw/5CyCYgeaZfbFpYF6c6T4=,tag:uXv3vJQDmUiMqXAG0uGZ2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
