apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:uVEXvfANGk9gGZd6ZTAFQBtWDr1rx0PPyJecwXG5ItHXY5ounEXymg==,iv:d/2QMntZ46s1nQ07nCdZy2/icAvjVBJ0Wcy+1bSLCxg=,tag:By1PJiVzAhS9Fcwg05Zjiw==,type:str]
    username: ENC[AES256_GCM,data:A8Tiv+w=,iv:6rnm7dIK3hDqIrFRCXB7+2NBjb/vWTSvFT3ydSOxCBE=,tag:Lci7PWwoQ7kV4rfZL8fuVw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrY2tYNXJFa3hoNytJZTVQ
            ZDlUM3htOGNKaS8ySTNGRXhvdnVUS01sd1VBCm9EcjVLYUZOUE5NVDU0NitTSk1S
            UHhSYjNnMUgrdGNtMXRCbEZUeVNMMHMKLS0tIE9FUTJRb1lWNmZ4YjAvQ3Y1a3JQ
            TFk1UHluUnAvNFA0V0R6ZDhRaW5hLzQKFpn5Rnyb+MnL6/KxWN0CzMIXWS57Db/r
            wpNoEA3cjdxAQ7fCBklXbbDwLN3IXNko17lTaYGBmsRvN3dj532N/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:18:42Z"
    mac: ENC[AES256_GCM,data:ktsizVnwmyYumnhfCbwi6a1PM4iWOKZPYGEHnIyboMpyQLWofb2ohnS2YJGsiBsDJpR7IKgdkptkLxJFbwe9iv7rckfTkCPAuejFOwQmQzKoclBr9mJ3pcsHz6521qtJ+9lhT7QPrv5eU6TjSX8yySWzVc6VHKqlgDeIayUccoM=,iv:JRKTZCjcM9FxR7yLsO0LX4z4UmWtBOXqE5IxI2Ki3k4=,tag:tMNrjpoPqdwlhj9GsKR5mQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
