apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:7Resym8wTL7tK386aucZl4SxoII8XK34gZ2ka55zhlo/aMadGoYbRg==,iv:xBtITr5P+6fGkm1Cu57IA/0GovqGNB7XJvzFEenJLMs=,tag:1NX6LQ2AZhJsZ9CSOMU6/A==,type:str]
    username: ENC[AES256_GCM,data:n4C3QTw=,iv:lwvE3+AVTNKtaO8iqfjW31thMhoI0GsvOLvjtHIQE3U=,tag:8iRFm25yBDl3FTkp5R9rzQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabHpJZm8xUkdWclEvV3R0
            enVwNmVXTmRrZlNHSkdVNFVRZnpYeUo2cFhRCnBJNittT3JyUS8vYzlPRnpFS0gz
            cU1jZTFBRnlrVnFibEM3Sit3aUFYSEEKLS0tIEtFb0dqK1NCL3RFdUVPc0J5UWZn
            cDdxakZmU3hlODliUWJ6N3pGQ0RUcVEKGQ0UfimpUL9KT4qLRZcFUw43O+bpmZh8
            zcw7Z506DJYajrBwaKLwng+gQM7xAuMdKB6MjBb4Vyzamua09jsZMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:05:01Z"
    mac: ENC[AES256_GCM,data:B1GbB/FwI1gL4/SVYHR/ilIfonqwivBw6Ho6cu7Xgx0WTWSOqx5DiUmTc6YWkOSuRnHjbQcqXa51hy0375UtXNd1LBjzCOdTgFIYiEENyUiyPw1dTxZEQLnCWQmYjugul0yASMJNRcLd4fxzH+Nqj7XQaiX0Ubzo3vznVjrsSUs=,iv:uY5x+4lCKS8HoPhZ/7k8apxAqoL8CqOyOrBDXkUuwN4=,tag:oChxW0vqARHh+owBZ2p4RQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
