apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:jFj+2VY+mrtcbRFLoA4OxZX4,iv:N9C4550u6tCdzjfuVjcOSnzSnD/GcCISFl/HXnu3pqI=,tag:tk4br9etm11qFPmMZyjxeQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:8TV6vffeVgT8pcXOXxesJ4G6L2SzT6nvsmT1MGEy18LnHQRW,iv:fp2xEhru6C+pYI7ocXD20hl8N/oXhWhyxkn1xsh6WRE=,tag:9iDxkdBJaalyLg4VZc6NRA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:G54nKmZHwW2fDbw=,iv:mxB1oL5zjqK0qZqiR8ZwBGyDJHjU1Shc3SxcxsI9ez0=,tag:Aoo7evViRPLr+M0J6oAbow==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQlB4d0lwNlFzMWhrYUpi
            THdzcmtXMzQ4alAyOGk3UlJzOWhOQU80d1gwCjU5ZkpWckJJaU9mQzV1OURQMXRJ
            Uk9kRFVuOTQzY1cxN1k3OFFMbmw5MTQKLS0tIFQ5b2J6bzhpRm52WklZNlpBUmJE
            eFh0S1YzNGVhU0oxU3JyR3BWWlA4TnMKdOuA6dVYihCSJ+wI6PT/rYr0TFozfAab
            WoF0RZ5K6KV2bFCjT6djvNmjWw88PgyDnu/rgydeMnn2SgGz+JH6JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:25:42Z"
    mac: ENC[AES256_GCM,data:Lps+zuXFqVLX87rNMUZ0PTcdlTqYFc5fX0NkSLtDbLU98NZedTSzGom57QxA4DiJt5ogpe0I+hqlEhM3XzLgLZJAoYKf/tE1+E56LknPKM1qdyfFeI3voS5gb7YawEiLk6a+dztrwcS1P9ft4xrzGndjcVC+Ag/FzXHT44jnTTM=,iv:za0QFCcWkA0pUCipLsjyrYaU7naiftZCVACTxFLhe0Y=,tag:ff/lr0Gqo3LQDuIZkXarVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
