apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    FACTORY_FLUX_PASSWORD: ENC[AES256_GCM,data:zBorYNJSCKQ/uPSnGHli9Q==,iv:Cco1bJ/koypYf0InI/tReT+Z9sIMrq/o9YhiPi9U1z4=,tag:O3FxpJht7KYD98ntNtPjeA==,type:str]
    KERBEROS_JWT_SECRET: ENC[AES256_GCM,data:LxOHRzX9NejqpGx1u7Z3,iv:wwySmL7yPOakcmXwC5+2Z7RM5Mnjgjf7OKJr3MTPcrc=,tag:vyovo+9Db4BmPd0JIDYkoQ==,type:str]
    MONGODB_FLUX_PASSOWORD: ENC[AES256_GCM,data:slYs+97r9gqIMyBCS62DZg==,iv:6EmiRiQmAJ5XH2LYD1zlkDeYIuCVlm2QvYUjYIuYPFo=,tag:DdbMR+8kJS3tYOgY7mQktA==,type:str]
    RABBITMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:MOExBqqK+FL31n1guYQuTA==,iv:TnLMdbS2NzDNofNuQBEuvE8Bt6/TFL7ZT64hGNfoHVI=,tag:jWY10te8GoJslhFIY9E/Fw==,type:str]
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:tOKAuGZAemR60GUf,iv:fTXyJhAPnJAu9FNBUrwcAU1FoVu7vaww13xWDYS0U7Y=,tag:dz0AwPx3hJkoP88JPE+d+A==,type:str]
    TAPO310_FLUX_PASSWORD: ENC[AES256_GCM,data:2U6nuNmSqQ3wAQ==,iv:GsExdu3lF19AE7dcIXqV6+Hnk58VGi58MdUsQbZRdiE=,tag:BKJY+bkmurs61hUkq2jOSw==,type:str]
    TAPO310_FLUX_USERNAME: ENC[AES256_GCM,data:oNT7B2ZVRjHr4Ko08vZP,iv:xiIhTbATe8xqSGcdQ6aJzZNJapKj9JaPq/NeVtzV8ZU=,tag:207Fg89oYTVFJgqfDCZo4g==,type:str]
    VERNEMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:9CobaKwIInkeWB71n+hFkg==,iv:PmPJsT1tLFwv80quZJRuxdqgMc0WLnpRsIznRABucFE=,tag:Xk5mKeHUj7vVDVpDaOMwvw==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtci9ZdjlxT1kybFlrbkc4
            V2J0VHJ1UElyeFVRVlBvdHdiZ3Q4UzM4VlJrCjBGbmhtY0QrWEtaN2YvRDBSR25y
            UWI5aS9FSU9FYTBlU0lwY2crdnhtQTQKLS0tIGNBU0dFR21DNDhibytQWjUyUkxi
            bG82ay9yMkxhL2N2emE5L3gvTVpSTjgKNL9qZuFzy7DbIunPVy+9eWOKnaRsuQaf
            sezi5K90Ts2nEC+kURi/ZnsdiaJyXTm2934RZaG4kMd8Lx9AZXpKig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:25:42Z"
    mac: ENC[AES256_GCM,data:l8cJUzP8tKLoCXKMC9WUqkn+RG6ARCoabjXrwijk2Ix1xPmfQOtlJugvehemwgOFJCxzJufPPym2x5QsxuYuHWchgXNY1ldjB61FGVMi4YA0nxE/Op9C75LvC/IGQ6gG3yUMFdc1deulyUaaILRNWh4tE7pXw47vUvuAkM7fwWo=,iv:uFjVIRAGqWLFUB4rX7QcIj4Wi3O/KZbQOWtVPy3a0Yw=,tag:0Y+pPia+kBb5Iw/awJHaiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
