apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    FACTORY_FLUX_PASSWORD: ENC[AES256_GCM,data:+HLpSoKOS3/1JDk7LJlVLg==,iv:AgctxxZuaLU+enmRcZWaZ6ZuZ7mxfazy1XmIvKoq2zI=,tag:B76ALnlJtq5QwnP8KOe1cQ==,type:str]
    KERBEROS_JWT_SECRET: ENC[AES256_GCM,data:N4p4FAdT17WBnJLP8nEu,iv:6//Z/TB/1WV8X0LC8BxP0ntrIqXr51s1E6COf2eMOCI=,tag:UYij+YHJTC4/sHvJL199KA==,type:str]
    MONGODB_FLUX_PASSOWORD: ENC[AES256_GCM,data:5ykmqJm8rXx6XB3Da3ojxg==,iv:wLuund+wMM/sKseoNZqEpEpyiBNKGKg76Q+UOmCcWyY=,tag:qyjXB+OcgJBFiYR2coDuUQ==,type:str]
    RABBITMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:iq1dGD+SHmT0IaGtI6SiMA==,iv:++pfDbEpOr/U1+tCS4BGsjfFsFi7liUdcTaR6e+B8BU=,tag:kiXrimaBK0iKVLuFwj2kHA==,type:str]
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:FR1C38rOJWZCecIJ,iv:3pOG3az5HqLXAMuxv8kTJIWoKXA+Mwrnz8uC4FPCVOM=,tag:uj2ce2O4OFqWdEXki86CRQ==,type:str]
    TAPO310_FLUX_PASSWORD: ENC[AES256_GCM,data:8/xFGqgCmjdkRA==,iv:5pEemv16ZqYwkoXxlFdrGAQ2XQnJdrYBqdrn29MNhLw=,tag:PQLkgUXMHORY8kpodSnWwQ==,type:str]
    TAPO310_FLUX_USERNAME: ENC[AES256_GCM,data:X99maOfebP9MKhn9BcjA,iv:WIeIdZ6wTfoO518p0ptIl06YLWrwx2nuPtxUroyMQfY=,tag:g4DYb5ZlWlcyDW3pc+KDWw==,type:str]
    VERNEMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:OmqNLXAKawSHI96o10Mtaw==,iv:66XChBkuxncFe6aDA+ZUVo/GXCAZmIlmH9x9Pf5xtP0=,tag:rEhzZiwjm+KrMXdsppYldA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNTIzdE5OLzk3aEl0cE9U
            cExTT1ZjZE1rOWQzMXV0SjcrUUNvSEFMQVZVClZ6RGpKRnhEeWxjbDZqMTZCbUhh
            YWsvSTdzK2I5L0tXckJJZTY5RC9EckEKLS0tIDdDMFBTdFpIclBHdEk5NS9vYlNi
            cVpaR2lqM1hnWFM1V2R1MTJvOU5yNUUKip7c0ulMFeQUiFUzvn+CrS363LdrmA4E
            Fv3p6+E10fTgtCxk3fSQDIrIAxI+CXeqNGqNNEsjuhlyLDRO1xFhIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:21:01Z"
    mac: ENC[AES256_GCM,data:KXbTy5uOIQpvufq7HBFMNsFRl59Jt3gvjyrcPjkueFPff5CoDDUROkKTa6v92bwJSPwDkEYdWwIZ4AHi8cXpB90i0nNGhBVvVW4D9y74YJfl+KoqVIgYbQTFfQ37GrEuucqkBr2TuYnRve6ls4VCLB24xVqsDa4XSdhRYr9RjHI=,iv:/0rErP+uypZc7xRGeF2uvXI/WKfPUD7JJAdkOwuUNZg=,tag:vj/biqupRoSs8bVLoM4TjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
