apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:RooanhqUHwV9Hd/aLoL+C24s,iv:Ti+fMO6wy0R3i/fAMjG2DfMgVU6RUUHAihWZAUV/SZc=,tag:VxkPprwCfoKHgY0kdRFm3g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:vzDL4XGxjHOoo+yXHpeMMX9v17JIRX+CK/Je1T5CmZn/OHeO,iv:foT7XgaItLecdWGJsBZPdTY7rAqPe2a1C18M6VmzuwI=,tag:u1A6DpBpLHwVoGApj1OG0w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:apdr7BAbibOAqUg=,iv:EmZGHijyeE8hz5w7miugxT6EnCZJ92PgFfLuHeGzh0U=,tag:vblbVKDSl5MMAnY16lx5pQ==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YkNwcEZnTTM5SVRhUUpq
            djFxMWdDWDFtcmxxMlVxREhmWnkzNWZWOEhrCkpoM2ZHdXpPVmovT0JsL3FxcWZa
            Z3FxOEJkUzAxczFjWHREaHJIM25TUFkKLS0tIGU5VFpKR2NIWDZRZ3hGYmFiZ05m
            Sy9BMWJUdnZZVmhjMk1adE9LRytwcFkK9pkJ94LNeIfHZw3nvd2q5Xo0coi65k3L
            eHup36mTUQ5bihIDGHW1MYjk4qIK+Eaux3KjpxFeZpco9Xfin4LArA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:09:53Z"
    mac: ENC[AES256_GCM,data:jXco+9qRTB2e10CFSD7PrpfZrSO8GpfY9DENqETHRezUVTwAo9de9aQ1t9TCRMp9867qXKOEi8WdIvsXURjedNl7/NBmOuekCVozUVGAhBiFx+UnwZYfe8xNyTK/sxLwQFII1ay/D7SJM4zaPinnGroju0exZoivi5LX5QpJuYo=,iv:NIj5Ot87PAQ09euAdoCYA/xdSSF/MoG9K7zUFAqdq5E=,tag:WH/h7SqVqTdg1NWV7dwZYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
