apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    FACTORY_FLUX_PASSWORD: ENC[AES256_GCM,data:QjhLttjoVgjtJEL/qeW/Bw==,iv:xX5CyQB1qX+grYIc67SI85d+Zibk8m5iyP3Xh1tSzlU=,tag:OtuAWACFu/Cq7U3kBERR3g==,type:str]
    KERBEROS_JWT_SECRET: ENC[AES256_GCM,data:/WJhPtrAZPAf6pfftt14,iv:EN2WZFt2kYwH+IQHwRXcavWCbIBQXmiD2gTxk+5bItE=,tag:1udIVTbikk8zFbJ4dnS0AQ==,type:str]
    MONGODB_FLUX_PASSOWORD: ENC[AES256_GCM,data:G/cK8f5xLylK+EzGJVPFOg==,iv:vNMq9w8AkMJzbtQ8sS0eUj4cWINLPkeTUifUgNrO2pA=,tag:xkuc1x8Zhx5fzIvtW3hquA==,type:str]
    RABBITMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:BTZw0loWGBArapz0sXgAHA==,iv:c7iX3V3yNPzZdBf/gtq1H4WCgVDfMwA520MYKP9mmos=,tag:27+aw/2KB/2lA4uCcWh25g==,type:str]
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:uaJM8qZ7ODDY0qFh,iv:8SCECdQG+GDw9bHB/PNp6pc/jWF6r93AWzSWUe7s2ao=,tag:w6OK7GlESIHHNR3Qk4kTbA==,type:str]
    TAPO310_FLUX_PASSWORD: ENC[AES256_GCM,data:GlANFqqtBzO5CQ==,iv:671PhlNMaJzTt/4F+m8gWyypf1PmsdFILA6gXlfrqfo=,tag:UkKzdW/bDIYV2OeO+rC8Nw==,type:str]
    TAPO310_FLUX_USERNAME: ENC[AES256_GCM,data:qMShU3k47eb5A+Z3asxA,iv:EZl2E+PUdQcwl9/xK+NLHwuG/iOY/cLfWdISWxfp2m4=,tag:vgwqHSBg7nH7EwkwP6TXZA==,type:str]
    VERNEMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:eSl4P8EAmLTRHjvhJKAKoQ==,iv:eQdGoraIyAKHm4z6Qsr8LZqCKhY92oj6ZvNQ4aA/0HQ=,tag:4WGe7vWqsrjWYavOzUvZDg==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT3RSanJWZW5HdjIySzJG
            QnpFclBFeFhLTHN5TVJnVmpra1hVVEZUMmdJCnZvZHliY0lIWXp5UzVvOWVOczFY
            L2txSkk1QnNNcVFlVzAwSjkrcGdnQmMKLS0tIDNGRUdkSzNZYytUN1BNZlY1RWtL
            WUV5NDRxM0pzNUNUWkxtcHhHdHRxeG8KAXUP+1HOQqoGjaeaVwWztyeREw2NnAnb
            ej89vU/InR7NtuVwpyknMa8fKdquBHDnhuUcYEb8zVRopsdUqSHRYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:47:24Z"
    mac: ENC[AES256_GCM,data:BC7UdXxpXiht+uB4idmPiBKJGIZxtJCa2i9fxC5uo9ZiqlRuoKjHe4zhWyV1TNkN3j52SWBC4ZcyPafbwZkq+XpHJ0YotgEF9/4jvhcOsY3AvWGzWUauKyiFG3ZRfy3NWG7e5Uw0GBioeJLl6nrn1YNcFBlpOJQJ/mG9em/PwhU=,iv:T/zuRSDnvdHtMjQarwTyk3CP/o9uM8rZWtGy8a5z/bo=,tag:RQGD+gKJ4wzbaq7HfEeDFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
