apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    FACTORY_FLUX_PASSWORD: ENC[AES256_GCM,data:k4VtDrx1kj3j48sHg/TCgQ==,iv:E1469SqpFSSD4rFFvepV2GEsUe9yIaQ8NQ2XQvCS5jM=,tag:Jjc4kPeR61sN5VuON+xk+A==,type:str]
    KERBEROS_JWT_SECRET: ENC[AES256_GCM,data:LtL0rukqA4XciNM5xn/R,iv:caUADnqJQvyIQps271PhQshIe2LZdhPsJU2qHrnl+HM=,tag:wbD3xfFbNVywwGIFhffnWw==,type:str]
    MONGODB_FLUX_PASSOWORD: ENC[AES256_GCM,data:i1W/Z/zdFZT6L6HMKNeqrw==,iv:OcNSeBlrN8W1TvkMgoRhBRSN7X0UikbqJvboLewGDhA=,tag:tIq7lGk+lHcvf3ewX9jw4Q==,type:str]
    RABBITMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:Hgrjn2Ph08rP9gJIJ2mxkw==,iv:ZCRSv9f0QZi0Zdy/rtIbh5TvoYL9uOExjzv/2jqxvr8=,tag:Bx68O8Dv+odqxU0LWEDjYw==,type:str]
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:Flk0kCpDJalAYHin,iv:lXLVLXhQqGVX4eS4LSe+Ga6rqv4MaX0OZVUUX4Epsoc=,tag:SQXcNB8gFoLZQjrcsynpPA==,type:str]
    TAPO310_FLUX_PASSWORD: ENC[AES256_GCM,data:cvZKhTLnE7Tjwg==,iv:jCInVG/eDh86zLG4KZLLgkK/0IXfG0I1E/ahK7nJHsk=,tag:rrbG30UeHRiAWLalEHBfWQ==,type:str]
    TAPO310_FLUX_USERNAME: ENC[AES256_GCM,data:A5g3eUyS6JldNqXDZMrR,iv:DyA3wn0CzTjAdScHl1nVnEC4Zad2urks8yvl/M0aR/k=,tag:fs2wP7ViKoJQlLNOXHz7og==,type:str]
    VERNEMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:B6N/Tj5uZ8/ijy4p3Owyww==,iv:UnXJ98GCY6dt7plRaiC3pXbG0izjNtWvCA80TnBE73k=,tag:xf/rDhul9TAoegDWjr1rjQ==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUGFjQWF3Ukc1S1V2dXFX
            NE1HeVNrT1ZFSVVRdll3c0JNcDBiZ1NkQ21BCjhKeWx4U3NCSkcvcnZBMWx3dllO
            dGt4RHpXY0ZJYWRHNXl5SFo0UzVvM0EKLS0tIG5DSndNL0NHdGlzZDVkTHl0TTls
            TmpnZFdTVUhPK0VyOVQxUHF2QjNzNDgKoLQyd+4MHKqSn6TYGY7Tn0mN0D0bri/n
            TXEKfeltZM8o14mOAUr9AllD5wYCY11dNJhf8e4hjG1Ga1sjriFB4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:04:14Z"
    mac: ENC[AES256_GCM,data:xyFo0u9lFwlqHG9NHiaIWUukvgLV91DF6kylQcwQ5QFlJ3l55kN7GinzYZetAcm3SowDZUGXJX9Dvt43YshUkj6Fg/JpmvLfwti2Q/0LsF/MLcduDSrvwv6I5Gbpc6odYmbMcv56ZZJkiJG1n46b0MO1l04oegrNXTOeiBTSKxI=,iv:X5QcL0Aihlm8H80wNRhFsgLzXvk5w0KaA46t7vM1mC8=,tag:n7pQg5gMEj3gg8b8hT3W4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
