apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:U/lZQFgkXcJTcoEGJfmiK3BP,iv:3K3Zbrqj0Qo8h5eol6332XtZvC7b1LYq/qKQUwVi3yg=,tag:BXGYGCvTbkZfovhgQIAdOw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:yAQYL8MI58qyx6+ThH9pRoWobA4rBaEkuZ/LWYJknCJYABUQ,iv:eWZj4rV+4bYmOxhtijR3v6hQkQPsNR7ZmiMM9Uu9p1g=,tag:vWR8bbUgNC5R1VJrGOc/Dg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:FQ3D69wcveNpHys=,iv:RadZS/3MgwhOVD3Xi66iQLQ1/PiWhDrGjOMwZ9XnlLs=,tag:DMwLGZv6TxNzOPfFSpI30Q==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQXZCUno4Z01Rd1FUWDNO
            a2pwNUJ0bXFFWnpvUVhhaTdiUEEzVVVpckJFCklJK1NiRUo4RUdJd2JSRlZ1MDhB
            dU14SGMwRDFPbXBaQ2h1WDF6WTBXQTAKLS0tIHdDUExRYTNub3kwQ1VEZ3UzRDNE
            QVNoTTRjM2hCdmhlbVVRRlEyY3MrREkKw7nSUUf10aAYUuE5vLpc+lo3WtVU4p/s
            o78g3qLZKB6kr4+R3ghqO82cqAk0aNQnAYaIEzsobrPImzjL7JvwUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:47:24Z"
    mac: ENC[AES256_GCM,data:EXYg/DnZLBk0zCkSMT93giS0MtvwILDAVMiskXaR3blE9q/gD6a86kmGnJhFOqJJlHQAgyysxX0T4gOgYw5CdNfLHeNGk/zuch9imspoXkKp16k45kD6LGMDeiGg8VKP5WwJdH8qHp7E16FbCPhROzJhc5ulSrk/nAvrGpMWJcU=,iv:2RQLe0UeOzVhGCOAfQ7uIw3oH55fFWfPu4zjk1FfVi0=,tag:ct+FjO/29A0ZaxkakMCA0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
