apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ca67gr6uvDojMDIreqmw9gyw,iv:ieN4hmv4cd7bIeJ2a+iff6hwCBN9egCj0m0AFcEBAos=,tag:R6qolkN5lZ4WSLngnAiZLg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:cF5EWFW7hfync/0CFmmj+q8kTzDZ85hYxTRnJzv6WCr4NyHl,iv:n/uW+0OCIyYzpPPpfRXwXuyLumdm24Es7nFECtSbZZY=,tag:RvN9HDXNWcrwI/v2trtTJA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:jCLNn3kw9gdHplE=,iv:f3L+RllEvPyXNBflynVo0aiEVkIZ/dHt6/4EqceVN/E=,tag:3vT+/5atrFFzghZXfM2Ymw==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRWE4Vm9LQWhhYVdZbjlU
            MytHdHVjdU9nbW5KL1dLeENoVWg5SUJUNGxzClJxbVJsYW5jUDhwQzBHOVh0Wkwy
            SThmOEZJUHp0VFhzbG9McGNVSkxGNWsKLS0tIHE2NEtHQ1czeG84SGZqc2FudHNY
            RkI5S3d5VVhVWG1OUGVIOWpwS3U4LzAKikFwNhZBoJDxPKDdVg9R8FMShkxoyafW
            NGRfkl1j3LW7UdB0ABlic4vjA7tWqYDGrjzLaJY/hNeSjI4o7go79Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:21:00Z"
    mac: ENC[AES256_GCM,data:GeesxyVwb3dEBQVyn/Ds/fVXsL+qIG7CaNKpJ4XflNc1yZkZGp2bMSG1L0NJYa2dsaYDBO+bDfuz/eHduLORKWgceknfJ6BDGn0phEaeGWC1E+4y4m7WbEM2gMbmQ6TvRQK2YF4VughiJOZu93hNqk3mXqKU6fTbtd4GqlAP1Ng=,iv:+uzwMUBXHt9643CmpTDP162/RYufbMM/So5IOVNBqU8=,tag:DruilSBacjNrFEkB9jKnqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
