apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    FACTORY_FLUX_PASSWORD: ENC[AES256_GCM,data:XzBNXJfAsqdNvfdAxQNK0A==,iv:RMnnkgscdtu5haP6Bl2Wj/rkMU8KHCxPH9XTbg7UOTY=,tag:ReaFlh4YsNe0UH30W3UrVQ==,type:str]
    KERBEROS_JWT_SECRET: ENC[AES256_GCM,data:jXsCNycY2uASSkkXINmE,iv:SwCTnfsTrODYW+6CyXmt7vmjqkFjq8kwtEODeFJALIo=,tag:rmwtvGOQlHpcB9ZgTeQFsQ==,type:str]
    MONGODB_FLUX_PASSOWORD: ENC[AES256_GCM,data:TgIqfcL3XMuYZlEXmkux+Q==,iv:aYUA8xxqOawRSzYeSF0ej5u0EOfpqlpG8dfuA3HKXT4=,tag:u1VKnpyLpsMst5T4l6l0QQ==,type:str]
    RABBITMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:6dAwep0gHJP/IAo3YVvNsA==,iv:W9NrJIWFOJyojHX6u2lkb1azaXx9v2YUzj/ew3MbReE=,tag:1gLTcnzvFGLU/vaZU4dd6w==,type:str]
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:a2swRF+EnmJ4Ouef,iv:OO9KMOFWPm/hQ270+O9ve5iEmtHCAga2OYGIpBRZzPY=,tag:vRHsSmQjPuT/LMEua5NAPw==,type:str]
    TAPO310_FLUX_PASSWORD: ENC[AES256_GCM,data:kqgSRq+vvm0PkA==,iv:T3IMnBqGkMxPsrFrZDf2YlJ2R92O2+xLKowX3Qp52yQ=,tag:J2AFga3PxgFcQS2HTDYXeQ==,type:str]
    TAPO310_FLUX_USERNAME: ENC[AES256_GCM,data:tbbfaMeXYLsL5gQ089MU,iv:PKhCbmFwmD1wmhgjo0iSWENfn3sWz4Mjq/AJu0pEnQ4=,tag:4QNNbUYEEFgXXzN3JB0niA==,type:str]
    VERNEMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:Nm58Tn7kwPBwSRBmogJB7A==,iv:1R56SgOhm9wFUhU3dVXHNlfTBVQMLcTXZS7CHtrwIbo=,tag:wwbYxQxcqTdN+TpqWUXAuQ==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSTdSZnlkSHl0akEzbFZQ
            ZWJSTWMwdkxlMlFaVE9DNkx3cFVIM3dMMjJVCjJVOENHL1ZOek0rQXRkeC9IMnNS
            ZXo3czhPY2tJT2ZmMHc1WFp1ZDltMXMKLS0tIFZsaDErUFpiemhaeWxhM09YNnhM
            ZDlaNndHMFhabGdMRmtUWGExYUlLRGsKDzesaR0OUj/LV5uVAzL3FopayXtEdYAo
            LlDbyEi7pkju5ZujHSC/1gU+cEChQj26c9oVn6MsuxI82WI8Etqkig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:17:58Z"
    mac: ENC[AES256_GCM,data:54+t6/qfO0Z0jtKboGmTZcAfhCvGCBUzK6jSyiU5e0miItETNoqKcoHmF+frUGrZ0C1C+XkC0/A7yf4cM/DYHKddiheAXogAkf/L/8c+9N2g9woJZlEZB67V/jHOu3W1EJ26kvevwDkwVPxqPfnoKz7hxJsmHPlA3l1lDt/7QVM=,iv:fccUZ8GVhILU6ksy/WLsMyAtrMT83CUAwcjqNbPp7Pw=,tag:IusCt3MMX5XvyMMwI6sXJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
