apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:DH0M6ZnQM8DriocZ3oPb+O27,iv:eOFGJRH+fPEAEc/I3czTqFMYgVJu3n3iPGM7pfEZRVk=,tag:mzmbwdUOehg4a/o1SWckMA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:UniThF1feYWjwhayU1ts907JGQTvtrv/oJJfNueOn6kmpWZO,iv:03Jm0CVgrHQjt/wkdT57SceSxYlRfVIF5sBufcCW05Y=,tag:sf/LflaQI4IAX9TNSsk3fA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ybLiXBHh09EhpuI=,iv:YMhxhH/QD29REmJBAEhzU6i6INfOcoIDuLJu48pTBRM=,tag:yYQjurt7NK3GOLiHld67tQ==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVXBJQkNRL0diakxFTkNY
            KytaZWUvMnJjVThUeFI1bUJTKzdWbXhqcWhFClBZRStRdmlmT2RSdUxpRllORWta
            R0ZqLzR6c2RiQnkySzZIcUFlZnovK1UKLS0tIFV2YzhZdkpYL2lWYWNFaUFEQmpX
            RWFXVVl5K1E4cDZSNzA0N0xldmhKeHcKcNTKTh8W5eb3afXKUX0ljfeZCL/cy+as
            cOpB1FIOTjJTja8Fc6q7GqK30q+6y0ODRyqsqtM8dNAZHESc4qPoBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:17:57Z"
    mac: ENC[AES256_GCM,data:xKpaVXD60L7B6fsSUTCB01RhAXbNNoA3/KTNs66qyj2qxgAzKagUPEwqGdLk4Ojr/BMVX3+6CJbEzVxL1W47V2cD7vYu0ji+7BTGe7BbX/h2tLxCNg1ucbQFpwIaHzcxTOAB80ODP5w9LTEN8jb3394KXz7V5luxbESATrLqF1A=,iv:s/3LQzgHcX0MMBYRHZs7a8KIeOBDhzQeHcpz36GZH80=,tag:SVrIS2RgzRFaUHyn6RJ8Dg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
