apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    FACTORY_FLUX_PASSWORD: ENC[AES256_GCM,data:n2QfvdfzULZoDhszCJY8xA==,iv:Lp/q0TRr4hxl1R7HEGX0equg59QQefW0gEtgXhQBcOE=,tag:uaZQM8/Guiw2Dhb6oDAKgA==,type:str]
    KERBEROS_JWT_SECRET: ENC[AES256_GCM,data:ht11hBjcp7HPpcCf5W+3,iv:eGqzCavvP11tlgnspzgpQB7N4Tx5GtqdYsU0KtJOkpA=,tag:re7i+YzP4aRQw7e9ELJl8g==,type:str]
    MONGODB_FLUX_PASSOWORD: ENC[AES256_GCM,data:OqNfMvYohDlEDTQuVrzC1g==,iv:LvkZbh/SgHkZjnn4j8yTcNqKZKza+iYyICAYnXiYTGI=,tag:iYLl0R4oRtql/qB+1XEuNw==,type:str]
    RABBITMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:rFuTisfZZCpM7kpIC1rtGg==,iv:wOsmgeqZIazh/T2gGV879r1baJbVnxGwA+x42yiwq3U=,tag:Er5ShMXV/g/6D7r2D3gU6g==,type:str]
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:3FpR63hFwimFzoiZ,iv:BIHKRkXL/fBrfowTkWLc0dQtWc6UISkEtTIliuHlZiU=,tag:0fQ/mpfliYU3y0zwUX5R3Q==,type:str]
    TAPO310_FLUX_PASSWORD: ENC[AES256_GCM,data:pKQsDGWAyVr9vQ==,iv:rIX3lRwqEXfvmN5VMA37azuVHGV1qbPdiGu8SXnfq00=,tag:UmqaRM76EsME28aPPGMP3A==,type:str]
    TAPO310_FLUX_USERNAME: ENC[AES256_GCM,data:ukW2ZJZ6uAWmMLWdeow6,iv:4Y+8cSLcogXmkuGdD/dxmOZH3ukBoqOxDEROBV/KYag=,tag:iPA0czvB0EEHynRNId3f2g==,type:str]
    VERNEMQ_FLUX_PASSWORD: ENC[AES256_GCM,data:Hn7tEwKXKUJ6ldgdY1nePw==,iv:JpKgvC/lEzJ2ux8w8k3vaNUQBJrerMdl6Ne4olCdZko=,tag:o56udFzQ7QaPyx5oJb7yxQ==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTHM5VWNDVkFKWi9qRnpE
            SUM1RFAwazJYTHdNSEp6Nlo3eG8yajE1Uno4Cjd4dVJxMFQvWTN4bjR4bjlQZzNQ
            OTNqbXVkQnB4WVo5MjJWNStFL2dHN3cKLS0tIG40TWV5ZzNlSEl6WlF3NFoxM2dW
            VENHczVBREM1NWZ5Rkk2THdML0RIR0EKZrVAbPiMPG6tEG8IZfi4xZkVzRWf+Q+L
            w0MPKTk+aYq+RgFcQC9xbTPWT7wqeCFlovtPKnBT+TqqkOLW2iGJWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:09:53Z"
    mac: ENC[AES256_GCM,data:RMwyBfR3xhECXJ/WTFPsp7yHI13qW3sX2OWY//aRug82CzEG+V85CS81x8t1efBC0c3kw6i+Fut86vv5GZVwfIF8BFrpDlDxqBu0P1EN1i4hfXnbQtj9+flOtOV9wCjH/wGwkCZgtdo8Z9fIbpQDO/EewSDH5W12IDtj8n1hjQ4=,iv:MkyXhSupW5jizP7xG/EwYYa6Z/CvXz0K123kyx8tLGQ=,tag:4LY5oAGF77X3IwkFKHOxlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
