apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:eV5N2wXCDG4HOa+U8zWob2qQ,iv:lao0qX9T7yIUDF/2oP6QfvtMznI7aD34DrrqGg/aevs=,tag:ypQFCkvZIijqjOW6yfjpog==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:7e7XwN5dRS2zJGfz0f+1pEiGWMhJLs5Wttg2V9J8euEfwuCO,iv:TZf+9rI5a370UoPYA4FOsvMTpNeDKZ2xftfwGvx69eQ=,tag:u57RdSrgyAgTnhj3GLKxug==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ssOGieSlCbmmlxk=,iv:DofI7WGkEhDMtLGmrwJb1dRYbM5SrQJpJ6C2LDx3yXw=,tag:fGcpr1fOuZrmHWTkrjSmHw==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZkJmMGFYeVRVUmYrVmxL
            UFpsS3FucmpPcEZTZC9Cc2UrRlp0TmlZUG1RCjNyQmRBcVUzODRnQkdMV1VueDBh
            cmE3T3IzcGFadVNwd0NzVnZqYTZxdXcKLS0tIGVBS2ovVHVqNEh3NllPTVgyS1l4
            WUpHTjNmTjh1bzZlQTdBMy9GUXRTaGsKRkt2anoBxTTP4z5XzyFCVK66XkAwok6d
            uiSYtHpIuMVVt4kOJzq9V8sQRZJVc7K+fkQVOO5Fh5GgC4RiGvojKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:04:14Z"
    mac: ENC[AES256_GCM,data:Nc8XTPSU0CHZM3dO0rdLEZA89mQHPHvwtZbpcxGLYlSCV4asHay8/ibBb1B4DWsqp67y/eHR7Tnm+4vSMxwC7fXttPHOTS7YdRqMoQQs5nMQJWXYkGrDDp4h9T5w/xWgk1+MkKcaGDpL55emPXibPw12UuQZmI93RE4s6I2tE+M=,iv:S19NQOrS5pjrMoU7kIk1kvudxMJn4teOI6XrcpXw+0c=,tag:Nh2ZmcUFBKmV3bRSolj05Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
