apiVersion: v1
data:
    AGENT_CAPTURE_IPCAMERA_ONVIF_PASSWORD: ENC[AES256_GCM,data:g1S9E5iw9sKQYw==,iv:WaH8HK/r+dX4w2kjor8HN5xfwpRHajiMfoJRLsRdmwA=,tag:07aoB14DTKdfarYcliWwtQ==,type:str]
    AGENT_CAPTURE_IPCAMERA_ONVIF_USERNAME: ENC[AES256_GCM,data:PdtJgZumUgZtCweMfaS5,iv:dfLOxDgpPDWmIra+FKqJqm4Qdf6N4yTq/n0DbBbhMpc=,tag:OVNDrBgMN89cKuHrPQzKZQ==,type:str]
    AGENT_CAPTURE_IPCAMERA_RTSP: ENC[AES256_GCM,data:TNKeRrgyTJSd1DyxXM21aOZVQ1DbsZyMDqbI/qflQRLO3Hz5PAjth5eLCzEAxMPEcZem0sgpJzXTTTyI5+ArXn2n,iv:1fjimM8c5k1SA6T7kB+68xdoCNOKp/VBDcm/gSdr/m4=,tag:lvYOvOi05krYQ74h9OJcSQ==,type:str]
    AGENT_CAPTURE_IPCAMERA_SUB_RTSP: ENC[AES256_GCM,data:iZKlkQ91uyjLh2X1/kl6C8tufQpgLZtLoz6ElQF9fPCdthhLogiSRs7l1onjcBwzyVKuKMn1Y4/QTVfH787Mpiso,iv:ns+SQjc26AVnLx983HyGxbxqufQs8lt98Zl3LTgnFt4=,tag:5YzAmTIPeZ8nln1Rk3Up9A==,type:str]
    AGENT_MQTT_PASSWORD: ENC[AES256_GCM,data:tl7fjAcLrrX87D6ZPufYwg==,iv:ukIkAxiVNQVco5NSgf1x57u/d8jJOjoWF2/kw70vngw=,tag:Kii3mSnk7+jG+FoW+NOeow==,type:str]
    AGENT_PASSWORD: ENC[AES256_GCM,data:gY1Uh1Obt3yIzHH1Ga06Gpgb6OZxfWWg+7D03STBsBILJJc/1spB6A==,iv:YOJqJX5hrFF2d/AoKo8ea5hg122eaD4jNWRmhvU6BhA=,tag:/njh8Q2a0QvIBMqTOczslg==,type:str]
    AGENT_TURN_PASSWORD: ENC[AES256_GCM,data:iPl2L/byG+W30PMgAd3kBb4e4vZzxxuJ5VDGAg==,iv:K96K3DMgaIszkgMDy5WJ8JqeQEnKf1GDdilDobGLBEc=,tag:8waNTJYEppTogQ7mk7D0TQ==,type:str]
    AGENT_USERNAME: ENC[AES256_GCM,data:rBmT3a9R,iv:0R4cO+LHVevEtEXAfWBxXehfnViIKb2YUKcbZv6HLCk=,tag:X8T4origMf2v4MGXb00ZfA==,type:str]
kind: ConfigMap
metadata:
    name: agent
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MU1oTFBKdElhazFHYnds
            TzRSQnVDd2NNRHpzbitYQXZNbGhNZXRVQkRnCit5SlRQdDh6TDdHV2tYL3Y0N3Vo
            Q0FJVnNGYS9xUlU3WkZSSlpLNUptQ0UKLS0tIER2dkpUUXA4M2dqNEJ3KzRXb0g4
            dVdQMVBUcFN1M2E4VTNmTmFPNG9SRXMKm0ZPlN0msHagS0Dy4bvIj5k9bh32971X
            Vn/l8TtW2mTQ/qX0S29z60FwKbXUYT9XWn3GyqUx/vmFod0Y1eSobw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:04:29Z"
    mac: ENC[AES256_GCM,data:KF5/9HDap++eKhFGIMwptU9PpYio4OsqK8ek4O5wJmmIZtr3RtDXNVCSvosn2PatY+Y7aekSTuuF3JWKbNatcX/7BLZD3gRa/T2JBWB684e/7MBan/W20dFXpw0/ihd2V9XRDS+VVH4vfoxrj5njayD8Gl9naBdkHBPaUWIKGeM=,iv:d4zI/pjeTqA9VrDxyLxh5gn1FN+FCk3BhIzdYztkW74=,tag:QqFhgwTrVqKXXQxZXNltVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
