apiVersion: v1
data:
    AGENT_CAPTURE_IPCAMERA_ONVIF_PASSWORD: ENC[AES256_GCM,data:Zp1oBQQE9QB5Fw==,iv:lWvv/zIB2/BaW7GfsjhEy1KStTIn3bKTc+yhjwCB4bA=,tag:VH5iy+7+qY9h7pm9j0drOg==,type:str]
    AGENT_CAPTURE_IPCAMERA_ONVIF_USERNAME: ENC[AES256_GCM,data:j9L01J7dTwReS1FO3Rta,iv:hxpjyTGyvNv4Na18xPvj8utrGUSxIhdmSj75zNYRcsY=,tag:j3o6VDCJ9m48bQXS3UfUWw==,type:str]
    AGENT_CAPTURE_IPCAMERA_RTSP: ENC[AES256_GCM,data:wycvLMr/Vt8N/omuBgIdE68/gNt7EyEfYoXVjHRxhnUEL6V8SayomboXN2Sn+K4V8hjLbYq8OYs8iUH+8h+D/wKq,iv:C4nrviV3J6VZLYeaextUWmKyQcSWet1i5Mtofu2QvDs=,tag:qO2S006yEW3bR+zfAF4WRg==,type:str]
    AGENT_CAPTURE_IPCAMERA_SUB_RTSP: ENC[AES256_GCM,data:lOoz3NJ83hju7MwmaV44PBPlkXxOdR0zJGvkiYoJRVVYvBh9MjSTw8IPk1Nrkt3+VlZQOhd+7eaYGRIDa1lSEifA,iv:pUk51wh+I7rfzFJ/GqrRmxNkXRB5b8esNOkVIzaPHmw=,tag:fLkyLWMbM/jCMJE0/1RyaQ==,type:str]
    AGENT_MQTT_PASSWORD: ENC[AES256_GCM,data:kp6jKx1qsZ5EsHvTK28Iag==,iv:e+4YujgNNFrQyV3qNbi0vEGORGmA6HZKWhZNHNmcchI=,tag:4V8NQV1pURlnTnvDmadHpA==,type:str]
    AGENT_PASSWORD: ENC[AES256_GCM,data:9B8QKFoqfyVB0veF5DxWbO7fuyRGh46b+dX1+j6hgNvCCjc7Trerng==,iv:txDL/Za1AOgzb30vzDE5Ea+pHqeaRVahhLEf3ovApdw=,tag:wz0sH/GuliWPsliVAQb3vw==,type:str]
    AGENT_TURN_PASSWORD: ENC[AES256_GCM,data:ShsZoO7aLOIYCsywhn4aib+SKtZu1Mnu0Z6pNg==,iv:hzs1i/nN6MVF/84+qWb9TV3Hyof7uVCv6m7372+xeSk=,tag:DcOzXOCTif6O9Q4litSY8A==,type:str]
    AGENT_USERNAME: ENC[AES256_GCM,data:GYB12cDs,iv:XzyleEWschFcYof05XkHhbxHCNkQPCKF5zxTqsyMzfk=,tag:uKfr7d2le1kbZkuYdpdDyQ==,type:str]
kind: ConfigMap
metadata:
    name: agent2
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RlVVSFZkMTNWa2J1bk1x
            azNpTisyNWVVN3FLd0UzK0pydUZET1JoRlZjCnpkUjZGY09WS1RFWVZyYW54K2tn
            bmdLL3RBZXVYbHRianBmUm1rak1NdVEKLS0tIGdsb082NmNsaVM5Ym0yeHpraGd4
            YmFnek5ITVprdzlLTTRuZVREUUZWbmcKhBFImagCmXkUPe4skvAol3XfRTXPM4M4
            OhaEgtJs08OQQI9ghBwD9bY6C2H42Pf6zp2JEbs7rdDC987nGBhpQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:18:11Z"
    mac: ENC[AES256_GCM,data:phKViNBnujFSLchHS2Ygffx+J5IcN0mklcAq4Q4H6/X84GLXZCIxi2+bSSMYTniuO7/YrLiaCxCZtN0BGsBD1cPc3DWbKFs1T795vlqYLLLDVA7ZtKHG0YQCl2MD/NKiyZl9lyOX9lBZ+6Agms105krCXCS6+wm3pTvpDSEqnUU=,iv:HyxQM+fix2lkupNQq7P9M3NCZZQa0DQa8OS8K2onxY0=,tag:y71d7S0VYIfExkiVuwQpOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
