apiVersion: v1
data:
    AGENT_CAPTURE_IPCAMERA_ONVIF_PASSWORD: ENC[AES256_GCM,data:PZWsAVVg3bIvPQ==,iv:T1gLewkWgwTinrupGrGWcCXR0vAH26kxEbMG+PC6KNQ=,tag:D5f/v+EhG8VZeSTrBYfo+Q==,type:str]
    AGENT_CAPTURE_IPCAMERA_ONVIF_USERNAME: ENC[AES256_GCM,data:TQPoLEdrNoXQbrH+Twti,iv:ZzRYhLzx2tf7yBkf6NqTwcNSp2nHc8IyZpgALsgnb+I=,tag:7CepSSzPlA+OF61nE+lM5g==,type:str]
    AGENT_CAPTURE_IPCAMERA_RTSP: ENC[AES256_GCM,data:YcwUR0xlPIXMK0JxfKXHgO2mFLTbZKtG0W/EHnn/57bBicBCQhlv5yfSObIR3NJQaJO8bsqWQcQ5/pOFE9JTNynr,iv:bIjHkjp54s0P0P2WR488OyyAM8G7vK32LSE7wpmKTMM=,tag:z6HCj9HG2ZjKmJwUwX4Y/Q==,type:str]
    AGENT_CAPTURE_IPCAMERA_SUB_RTSP: ENC[AES256_GCM,data:Sp3HgthkjsxJmQHE+jDTw3bzIGy+aeic3Q+c16msRXc5WLBTDzAustIBfO5yANAspybaxBWxu4AFp/Z6spJLHvsg,iv:Yya1WuQH4FrmuxkJTeLvm+qviS8/PfJjAFttcw526n4=,tag:aMcvXpct0ckmRkKbdoqIxw==,type:str]
    AGENT_MQTT_PASSWORD: ENC[AES256_GCM,data:4AGHBKXnNarqVVMCtF91ZA==,iv:+FivBKwVSNrI6s2YS0aWtN95jGHPPQSnKEZirphbwBI=,tag:eMMcO0oImokS883cN4KCyw==,type:str]
    AGENT_PASSWORD: ENC[AES256_GCM,data:4tmQ4KvnVDE+9FdM8NP4NuSncf29qLVSZdre6a9xuz9zo3eFXRRWbQ==,iv:e6oZ8AImfZDihpbwUm1oKNn0KavaEBhzAI4YOhdFSZc=,tag:AfARPGP7lj9451Uy+Oitkg==,type:str]
    AGENT_TURN_PASSWORD: ENC[AES256_GCM,data:6koOo4tCxn70CjItD+f2oxIEVO+rSTKdhO1dRQ==,iv:W1gq/s2UZodOxVmJ/ddNNmRPE/HHK06GiTtL2LMrHNI=,tag:de9zwfxntsDT+pCxW7fd5g==,type:str]
    AGENT_USERNAME: ENC[AES256_GCM,data:lpyAaBGN,iv:Vl7KhRzGSSu8YikrQVSZULW/tUQSCYM8yLZITCyUDEg=,tag:ljzkrnBBOfu67cCgrkII8w==,type:str]
kind: ConfigMap
metadata:
    name: agent
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcXplTTVFMWpyK21JSWF2
            bkxISWU0NUJzZTNKNUp0MmFPZkM0aCtndDBrClovK2gwQmhITzFadU4yd011SFJl
            VFNQL2kzWS9HcmJKMFpXQWI4TFJGMTAKLS0tIGtnMnJ4R2l5cFNDR2V6R29JTlFh
            Qzg2ZE9RNXR0dmM2VHBlT0Qyb25xczQKngerAI9OriEFT1W1JJfwCwK2DEj5ebDS
            u+GZV8ptLm/y9HQHch25BU+vUpqBR2LRg7IspCfoqW74L3VByG/vHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:18:12Z"
    mac: ENC[AES256_GCM,data:oxBJsRZVhJ+b1igMYqeoqlYcabehAAAF8zjBev2461ehlKF+EgvzGc4t+uotyDW3QcdD4BLo8Xio9HNC3+VdYrA6sThD62wS8Y5ZLPJANuQDvl0Eqzanyv+mQMtCsXQs96dGBqX3Yz3VgQBnLnErOyr/4OEiahmkFjnatLiNNMY=,iv:sC9t7pourVmji46Nwcnno4/TtBsNZqrlsPf502tvOP0=,tag:K2teftzfFh1st0YSNZihWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
