apiVersion: v1
data:
    AGENT_CAPTURE_IPCAMERA_ONVIF_PASSWORD: ENC[AES256_GCM,data:zST65fp6R4LEiQ==,iv:d80+YA7O+BccLsqtl0tsProgjgqbfLOA/gG5UKMiu4w=,tag:jtiNKyoTUOhWeNh1JbDSjA==,type:str]
    AGENT_CAPTURE_IPCAMERA_ONVIF_USERNAME: ENC[AES256_GCM,data:VhX0e4hGPbRJz24pAorV,iv:L26Jocm8no6DqaEP1nOO70BZAHVseKotTDhP1a4xX3Y=,tag:o3bfdH5tvEpAawIXbfwKtg==,type:str]
    AGENT_CAPTURE_IPCAMERA_RTSP: ENC[AES256_GCM,data:7ozPyJ7ioqy0CZck7FqyvBusRDCLC8wNQon2iRI2yL8kzP+iAsclOkHgVjaS5gEP6ltVvY+EImS3PpIw3CZK1isb,iv:rsbiOpifJD6+hop/bwIaPwjPAMH17iT4ctQI1MOKjIE=,tag:APwSbPZmcu/89RaqtNqUjA==,type:str]
    AGENT_CAPTURE_IPCAMERA_SUB_RTSP: ENC[AES256_GCM,data:bAfVC2D525sNNgzmcrBO2TKxmVI5ngFNYobjm5mx96A4VAs7zwrSf6hDMXtVnhBpJvvVVgTye80c6MFsR41+NKZE,iv:SN5YYq5m2DVxh+8WUbMuxowbw0j4HOT2jydPuFtzpNs=,tag:IVad/0DpBEmjX7W/ZcqIvA==,type:str]
    AGENT_MQTT_PASSWORD: ENC[AES256_GCM,data:cog62p/aZ30HpBtjMPIv+A==,iv:N4Rewte5Vk0bCLg7Wk0LXhwAX/8MmWlaUi5q9jeHfm8=,tag:hLpPIWThz2JsBTQ0rIN5mQ==,type:str]
    AGENT_PASSWORD: ENC[AES256_GCM,data:G02dvK/e+5gLlLEVRkOWna0P/9jTaVTmlXwvIvgGHk55Q0NU0iGMKA==,iv:Us8gRSXLJzjwq4wqrHIgILJS1dfuZ/DfGnQhLg7nfJA=,tag:xK+NpwaaUraWEbYU8GkeJw==,type:str]
    AGENT_TURN_PASSWORD: ENC[AES256_GCM,data:D5Es6lBG7AFLdah7zhEMV7cVd3HrDmdCMcA86Q==,iv:A4w5PpW+eOXgxF8AN8X00ab4eMraZZnaEZK0+212Xzk=,tag:Im44HahP2SOwH12kRdZu7A==,type:str]
    AGENT_USERNAME: ENC[AES256_GCM,data:PYDBAjwA,iv:2muWyToy45WJGy0rvsE/aE7TQjfXTpnADFFhct9lIbw=,tag:BcEVxUqJuY0jduChWQnlog==,type:str]
kind: ConfigMap
metadata:
    name: agent2
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTnJWYks0U3BhMVdvSlpj
            dThvckRXQWF0WlRMeUJIcGJlOFlzZlhkZUVBCjYyb3l5V1hCdkdKQjFwTEgzcVNw
            SEYzM0N5bGVPUkRRZzFvUG8xUTR1V2MKLS0tIEVGQTBEWFdkUUM4TDM1NkpsRTkw
            cGoyeTBTM1JJTFdDTFJJQkJvNi9OaVUKzFk++Swd3hSyjkZrjcBuj1aq4aqM1N4v
            GjiFX563YaB8PGExfgRDljW0eW8NGYpsWaOZK8IqanSrK3C70rmXFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:47:37Z"
    mac: ENC[AES256_GCM,data:uBCVAHHgSYJiupQwTGFD5gFBrKKR75kEhu9trNmHHxjFCoX5vtSlYce59NHs2UHJpa6QI1toaDXXJ31FYEbIFkOx4+BjrdVWWAxSOiEGsnOY+tjF+efmRJ46JEj5vXkznZnpwsMIQxsrsKav4tA+2QR69lNYuRJf8lic4MJ8Ai8=,iv:SM/g44Sl0NbuIUnbcsAsv3WTmHTnxTPBp0CpIj6We2I=,tag:6Ryg1SB9SCNpcFPf25hwfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
