apiVersion: v1
data:
    AGENT_CAPTURE_IPCAMERA_ONVIF_PASSWORD: ENC[AES256_GCM,data:cd8QNYu6+cYL/A==,iv:jUXHqLeEd/L/xx6D8ZsK6joymPWR8obG03fKeSMlVCk=,tag:aFLF+jCWnZMDGSLwbODeuA==,type:str]
    AGENT_CAPTURE_IPCAMERA_ONVIF_USERNAME: ENC[AES256_GCM,data:YKt/hVBwpwDiqUywh88Y,iv:MAEp/uF8B32kKrzHX2FPyDeCtBkIyLrnSYNygJIGuiQ=,tag:YBeIP2ClUSJtjGf7pNvOEg==,type:str]
    AGENT_CAPTURE_IPCAMERA_RTSP: ENC[AES256_GCM,data:OfgVDvUgEjirGhZXOBXkZu8vKepbaZFMGnwwJbPCS/I6jOQkrPBqDfhdX7CpI5spjoYR8u6Xk+g5AwItcHMt7cOU,iv:TDRmdxe38wp9kg3d4LR9MWTqCRu4qIKQVBp4+WfXw4c=,tag:HLMIJxRuKdKVc6dQT9/OaQ==,type:str]
    AGENT_CAPTURE_IPCAMERA_SUB_RTSP: ENC[AES256_GCM,data:Q42WNFxq7AHdwS6kW0+b05cGh/vjiyMEXkCbvB8UhbG2N/4LNyFwYQk6yBdxOP+ajG88MhQLKae4BEARS199aFqg,iv:S27QyopjMWCX+UB+Ue5pAWuS1e3h1A1NIH7Z2ctvBsE=,tag:W5gAsfZYhcHD5TfFVlQArA==,type:str]
    AGENT_MQTT_PASSWORD: ENC[AES256_GCM,data:lKVdFdCqgx/PSTnQGuL1zw==,iv:Plj/7r63LnXhy46+l3dDJQxDcwTfkD+BB55uKhjeUqk=,tag:eE/hJqYUxf8H5UL2WYvqSw==,type:str]
    AGENT_PASSWORD: ENC[AES256_GCM,data:i2FmwAFLAoOHFdrrLLp2463eLdyHPaTZZYp6vdvM/Tb2N4VyDly6sQ==,iv:3Cis+3PN8y1dbLSc5tZ+G6T1z61/YX6j7heCfPCO3uM=,tag:NEKh37/r3mjxRRzlwxF9Gg==,type:str]
    AGENT_TURN_PASSWORD: ENC[AES256_GCM,data:QzpL4NCDT9Qy7pEWFvWdXztMLHrDMpDKG5joXQ==,iv:AVforEvpJkusVejQif/e0YeIcWmy7+TyqduXnzG60rg=,tag:IPicaBffCIW2hmt8xI8agQ==,type:str]
    AGENT_USERNAME: ENC[AES256_GCM,data:9UgBqu+q,iv:ipe/sgqcs+b+XAuDJ0pueOOUM/qRWBvSY4OeZsAOaaU=,tag:JmqFWDpLGJhYDSVNX3qXOw==,type:str]
kind: ConfigMap
metadata:
    name: agent
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSDNaYVNsdEFwQ0d1ODEr
            WFVDUU84UGpoVHAvUHV1UWlRSzNTUjFOWjNjCmJLaVpBay9ZUlVDSlczMkNGOEhy
            cmV0U2NvNkFKTUoxMlNFM2t4TDRuQXcKLS0tIEJvR0lTdlUxcjhXYVkvc3l5Znlo
            cGZDUDN4b25hTGRHVC8xRGs1NXZlaTAKtC7iRT2R441e/iKF1QiC3w8Bk7DzwLow
            jg82JHQ0ScHXzlgjfwApokZH9W9IGKg+jm7itvqKCrGu7KzIC6gWwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:47:38Z"
    mac: ENC[AES256_GCM,data:8yDgwMlMSwiQ1+O0Q0MJ2z4UWCgSnnFeGf1irGRlBa5IqtivWNub01yO5JkJN/lADCyfmGObKTIIpHCkUb61sUOt0FZyxKmHG4PryEvAqvxfdvox0rOseeAm79cwCpf9OIRRiAh1dDAyS26nc0h03mgPa0aZMcFMtaAVQbNQOIg=,iv:0i3zAP7EBPDfbA7YoqCk18eHwbr8zApiNyI4wxIejTk=,tag:u/Bipg2dKyBpPv8bt4WEzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
