apiVersion: v1
data:
    AGENT_CAPTURE_IPCAMERA_ONVIF_PASSWORD: ENC[AES256_GCM,data:pkMvBYzvtRIe/w==,iv:s6cCnlHcw9PcXuoQT+FgBKHOdCfu2RVXB2e1iub6qNk=,tag:NSx1Ao4WY0uWVHnyVNHh1g==,type:str]
    AGENT_CAPTURE_IPCAMERA_ONVIF_USERNAME: ENC[AES256_GCM,data:OpIBEVyLM9/V9m7XkAFz,iv:bMvWXwRtC2oz61d4vlw4GXEV70QD6RR8y65ysqD6FTM=,tag:C0BIKf6lHGeTSpoCHem/vw==,type:str]
    AGENT_CAPTURE_IPCAMERA_RTSP: ENC[AES256_GCM,data:5HQ5ugN1NWHFPqY2ZZ21BpAH9a2IVRwm20ozz3bwshBYIFDACR9F9ZkP+six7awnBK1gomI4DaIGtdHwzAlqJEKO,iv:1+mUvMmyv6XdGogsrj++UtR9n+Ni+4vKK77o19Xw6Yc=,tag:lfLDg5kxD/am7Ubomfr3tg==,type:str]
    AGENT_CAPTURE_IPCAMERA_SUB_RTSP: ENC[AES256_GCM,data:RQ3q93lNCvonXSkSu1mH4cClqek9zPjTrr52E8NsP2fLlNKV+4/zuUc0AlTg3EvCiIRhLnnBxskfoAz5MUR1gj+7,iv:+5wMDc3FO2EPjx0L6EL9jT5WYji4ol9siJrni46dCl4=,tag:bhJtwwSE8SP2LQMEZ8GPZA==,type:str]
    AGENT_MQTT_PASSWORD: ENC[AES256_GCM,data:qbJKWF2mazj470wF/GQyqA==,iv:9zs8nPcmBJOUqiY+qXiR3aYeRrrVhLH5oeaIByrJYLw=,tag:sScpJhhzg8Xp0NnVXHsgcw==,type:str]
    AGENT_PASSWORD: ENC[AES256_GCM,data:neGsFwsrQnhMFwblmFBBqXOPlv9CajzynWHyGeFe8ZFIJni6i7YWcw==,iv:CpessAwp0gzFU8rUSbbPtklo6uLv2KEsJU6QsyPS7T0=,tag:Qm7n9ww86uiBeUObz8OaSg==,type:str]
    AGENT_TURN_PASSWORD: ENC[AES256_GCM,data:CIyoWA4w9kJdixkN0/QXhszqoKDxyk5rQJWVQg==,iv:QbzdOA082UK1+MicVCv32+07Wb4mzacW0/iT5SOpEHo=,tag:HWCXZPbFaenmgJa9FiYyZw==,type:str]
    AGENT_USERNAME: ENC[AES256_GCM,data:qdsPjv4R,iv:XPZlMeb9/NbGc1ep91uUFnReOAFyrHClPPCxCG7jd6M=,tag:kPBC6UfXKqTS5f9GKUr2pw==,type:str]
kind: ConfigMap
metadata:
    name: agent
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0azZ2QmdTdjBlTkVNa2pS
            N1p0ek1pQnFBNGJkVktxWUhnSHNYdWdPampzCjlieU84ZkJVcjlaWXZ3bEpGT0sr
            SiszUlpxY2U1SUsvT1VDZ05qZTMvWFkKLS0tIDI0MXhwWlhMWmJVSU1GZ213Z2cy
            OU9GSHlUZ1JnZEgwWnc4cm9UUHdUbUEKEPocdOn/BQ3n5d19YgiHAg/ED6uMN8uA
            wjxtWtXl2sjRbDDMXO5SbMxbZFfYD+9TZn0JpWXekLhqql35qzBZCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:26:06Z"
    mac: ENC[AES256_GCM,data:7w1ENN5ilohi7uDYpEYxLoMZMRCAZLfSaegINbEwNyRvXm95tXCRMSpaNzxx6AcPG52k6RM+kcbPbEv82I9N8JmBoFaaIYaPPp71MSa2X0TUketdq9bPhPyL6yX69VfinPrxqDlevoGveaQvN48qX1cUN537JSzaZFjEuNUhddc=,iv:Unz/YXdPmINvu2JSCa6Yf6ew8VnSb51x5pLYyzgc29M=,tag:GWN5c/uJT2iTvCpXNh0cvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
