apiVersion: v1
data:
    AGENT_CAPTURE_IPCAMERA_ONVIF_PASSWORD: ENC[AES256_GCM,data:7Y3LR4FWt+0pFg==,iv:zfvZ6wwa/Y1LtAwtxg4egF8WrtU1vCuoLQFxN6Dxf7w=,tag:IizAYekzm1cKqNHM7LQEMQ==,type:str]
    AGENT_CAPTURE_IPCAMERA_ONVIF_USERNAME: ENC[AES256_GCM,data:QtmxVi4seZ3OQy/9nM1I,iv:SmvUHA060GwaK0o14SGx1yANjxCFbP4zqngvQjh4++Q=,tag:C6W54gwf1rnB7hB9htd/7A==,type:str]
    AGENT_CAPTURE_IPCAMERA_RTSP: ENC[AES256_GCM,data:q9L5PkmD19q8op3xsxOjxurEcxdy8YqUuTdlkR7R/GlHO7Cb5n2MiZZBOV6ighAVLvPBeWB2j9TMQyCCTnap/hfw,iv:Efu3YwlLQY8XZUw0jlDDkTTO+2sFG4yQ6DncykB5oyE=,tag:cGFvHMFJ5Bm7BXjcaqYe+w==,type:str]
    AGENT_CAPTURE_IPCAMERA_SUB_RTSP: ENC[AES256_GCM,data:Xtzti7irwanSG2hhxrXQST1bk1ZUHp1ZS20xB7Wu2eqDyBihCqBjUg7ozMlhbECI7ZdymytoXN4klBdiQtOeHO28,iv:An60Mb03Jtz4BEeMO+jZypHUBW2lRtSiDxFdJJalSk4=,tag:XZbTIsuwyLGyyeafdoUvOg==,type:str]
    AGENT_MQTT_PASSWORD: ENC[AES256_GCM,data:QYz/W97NbXtaR6peP0qh4g==,iv:1VeDHtqRNdyH4DkAuzgHbJqno9qkBa5aVYZ/Fkxnmwg=,tag:UQABP05NCIxeSq3dQi3oAg==,type:str]
    AGENT_PASSWORD: ENC[AES256_GCM,data:qb8Qs9SNeqEnqe2srpkM/1aMaO1SbKX91J6etsADZVGJujf0s2FvRQ==,iv:aSOh0RIDMgxElmkL7cx/34q/Py0t19uUyy4u1ofuHMQ=,tag:a4fWXXsa3ihKTlagK5mMdA==,type:str]
    AGENT_TURN_PASSWORD: ENC[AES256_GCM,data:YDrI6Gl5mPO9NMoajqthRZngQ5Rd6yKK/FA2fQ==,iv:/Um0xenf0ZVA7oJQnuGo6W+nJGrCc8+isza0dl4gSgg=,tag:OG1XoHua+1wC3R39gTjROg==,type:str]
    AGENT_USERNAME: ENC[AES256_GCM,data:HSJ8CaGq,iv:OYc6NC/eyauoHPSt1mbk2sE45cZU9NViWdtvQiZTMDE=,tag:lUtqYeDUCRAecT3/qspDdA==,type:str]
kind: ConfigMap
metadata:
    name: agent2
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MDFYRVVKN3lRRmY1UWZn
            bEVwSHh2cWdkSStnRDNic1BnVUZXbmxZVTJjClhDb3VvbWl0U0ovTm1JVk5RTFg4
            ZHBJU2h0RW1XMHJTcnNqZmFYTXlNVEkKLS0tIHpEY05mdCtYK1NkMmZVM203cEdC
            Y1dERGsvejBSUCs1SFZJNXJNSE9rYm8KzL/oAQyssfnwiRTj1qag/6u+en8NoXla
            YYcqZ8/ynByArsOyzBPlwRHK4RvVxMMZlWQj7R8gB7kSwcEhhB+Pqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:10:07Z"
    mac: ENC[AES256_GCM,data:N8imD5D/RbLh0SJzC9sc9XAm/oytJtiplxldojcnyg1vE+aCBgmokDjsjcJYlYRD7LUyJ6u/3wHmIQlm5/TKNK9up8reJOa+hNkhOx49dpW8tr6Vg/LmV2JiPi2FamRlK202IbYTbrpEyx6L5S+R9p0xDhpH1dFslQ/Aa7tr8mo=,iv:cZXiyqJffKsaHOSoYa2GQOeb/Nff0dc8X+EKyFYeQCk=,tag:FiDurTonVMTBeC7+VjxRDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
