apiVersion: v1
data:
    AGENT_CAPTURE_IPCAMERA_ONVIF_PASSWORD: ENC[AES256_GCM,data:oohvefLm8nEgww==,iv:r+BSUBD4ywzYU8nA3pevuEVIlzAYqecnnvbn9vyXB/A=,tag:EJggbGSAWumpMbz3TtEt8A==,type:str]
    AGENT_CAPTURE_IPCAMERA_ONVIF_USERNAME: ENC[AES256_GCM,data:3Y2+QZzinb5gB5ON7KXz,iv:4fnMOcmBwKwmm7CVBxytzC6O0HG5dJd+zN4pk3Inhx4=,tag:Y2E2Lyg3b03gbMN7X/KkrQ==,type:str]
    AGENT_CAPTURE_IPCAMERA_RTSP: ENC[AES256_GCM,data:YWRs8RE8FfHQZmtA4yGn9uZa2YdgU/GBEgoUw8rlFznpMxK4u6b0g2Qz+m/aLmv0nW+edTjlAiYysQ0OR4KvENxk,iv:MRGxSiANFX4Iq9AWM/WYqFutOof+z9RaxIuBw5rF7bw=,tag:H/4ueNG0lD4cvaR3Qf2r9w==,type:str]
    AGENT_CAPTURE_IPCAMERA_SUB_RTSP: ENC[AES256_GCM,data:cEABBoatZsxJGp1jTD9HtMH8NCMpp/J2f80uV5HKcT6npt1orL7eM3wUXQtn9Rvq2/H6SZMFs1uDbTvz7B4bQDKk,iv:x2TbY94Zm72NtvBr7x1hK1ocEf/ux2OcNQH7YD6AZbw=,tag:bH9rDZCYTQUNxPV1Om9wtg==,type:str]
    AGENT_MQTT_PASSWORD: ENC[AES256_GCM,data:u/93/At/FdFxhfzlW1Kegw==,iv:+iaspS2UzXO74SV6dFN3qohiMAPZdyGjxoXdScef4nc=,tag:CLbqXfuSl7vvQ8nDzOTqow==,type:str]
    AGENT_PASSWORD: ENC[AES256_GCM,data:CUnif5fYuTHTXQkmsMgYQW348wxljNI4UqvjZpK6prbeeOJ68MhPOw==,iv:yEtu3s5ggyQYzwPTIRuo2Pql5unjuf5lfjmfN8MEpJY=,tag:f2Dc/3YwfvEJcF/37mXRPA==,type:str]
    AGENT_TURN_PASSWORD: ENC[AES256_GCM,data:fhVcoROgLFygLzFiRHLmgYliOsJxTfhVdQYY1Q==,iv:i1teQpCvQZbXUEYlzwT8gZgH3aukkWEKqvuKI8QjN4Y=,tag:wN4y1So/bbMWbFfhcs5vew==,type:str]
    AGENT_USERNAME: ENC[AES256_GCM,data:/4em/QpS,iv:SsvGl2SZcUO1nm5nqACsWjkpb6UShc0sg4u7Mw0SSKU=,tag:Jk/tq+P9ufflwurkE36hvw==,type:str]
kind: ConfigMap
metadata:
    name: agent
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoc0x4VnlDSDQ4aVhZYzRa
            MXh3VWVlbUNlSGs0TlBRSWFwbngzTitDaDJZCnpjV2o1Q3JEZytudWU5Ym1KbCtr
            SVdjaTNVc1AyVXlvYWIzRUVtMUtqSzgKLS0tIHBPQkI3czBjK1V2bGZHa2ZDamV2
            eG9DSkZBYzNFWXpSeDlUb3JjVVZpMUUKNOf1WQFPxB5XaEqRIpU3EdnsUMjuAk05
            15Xq+EAkomVMK+7S8H7zAYX7hOfTH6H55xIJ9kMPbkISpKCJOZWbEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:21:23Z"
    mac: ENC[AES256_GCM,data:Gniu42I1FFtvl2m9kyZTmllvEyjSVWiChNKDX+hNmiW4vR3k8V7y7Eu58THYNgdgHLK6Cn+MheOAkklCvvLXXs1aAphkxlGQoBYm71rLQReoxHv1Ft22NwD2395mhxmYOiusd6u6/AoKzzxE1RET7TGKvNQNV3bf6o3EJtShyPY=,iv:m6cTElYmB8dFBFBhNRdfLhgFUfDNY8D8ds+B05vlAmI=,tag:W3ekZpwb6iPosoTgLhRCSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
