# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    patch.sko.ai/app-template: common
  name: vaultwarden
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
      version: 4.6.2
  interval: 24h
  dependsOn:
    - name: local-path-provisioner
      namespace: storage
  values:
    controllers:
      vaultwarden:
        containers:
          app:
            image:
              repository: ghcr.io/dani-garcia/vaultwarden
              tag: 1.35.2@sha256:d89a6d21e361254670c24a4272b4b5f245e402c284f2f55de2c379fdbcfa1fa5
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                memory: 100Mi
              requests:
                cpu: 100m
                memory: 100Mi

    persistence:
      config:
        enabled: true
        type: nfs
        server: 10.10.10.110
        path: /mnt/storage1/home_nfs/nginx/www/gs-farm
#        storageClass: local-hostpath
#        storageClassName: local-hostpath
#        size: 1Gi
#        accessMode: ReadWriteOnce
##      data:
#        # Avoid a name change with the app-template v2->v4 migration.
#        suffix: data
#        enabled: true
#        type: persistentVolumeClaim

#        statefulset:
#          podManagementPolicy: Parallel
#          volumeClaimTemplates:
#            - accessMode: ReadWriteOnce
#              globalMounts:
#                - path: /data
#              name: vaultwarden-data
#              size: 1Mi
#        type: statefulset
#    route:
#      app:
#        annotations:
#          gethomepage.dev/description: Password Manager
#          gethomepage.dev/enabled: 'true'
#          gethomepage.dev/group: Cloud
#          gethomepage.dev/icon: bitwarden
#          gethomepage.dev/name: Bitwarden
#        hostnames:
#          - bw.sko.ai
#        parentRefs:
#          - name: internal-noauth
#            namespace: agentgateway
    service:
      app:
        controller: vaultwarden
        ports:
          http:
            port: 80
        
