apiVersion: v1
kind: Secret
metadata:
    name: vw-secret
stringData:
    admin-token: ENC[AES256_GCM,data:Ddb18hYfNbv6bdIELku0/0GDlgyVc00NnVHWOCEQTjwT7UGLXJaEEA==,iv:+AJ5+X01IQf7yu7UPdHjw4AyU4klev0Fa8dhRpPBnIU=,tag:6RhIv7e7NrJlX5Apd0YNMA==,type:str]
    smtp-password: ENC[AES256_GCM,data:HJ4DUp92CnG/fvqXB6lXDbRl3A==,iv:JckPw5mQNIfj0/ffdsXzzln9VJH7vlLzDy0hJAI+Cos=,tag:sRb+q1KF2eru17c78Ie4Sg==,type:str]
    smtp-user: ENC[AES256_GCM,data:UYSK7tfNS7LNUsMkOVrZf4S8,iv:00cijyegdbX5wYS6XGkCyg5SfftgxLdV42O7ufgsiyI=,tag:ZLm+Ydol01x6L2ASiT1icQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQmNLQWo4NWE5L2dZdTJj
            L0o3QnFaaisxS21SMXkxZHpSS3YrSVJCTFVNClE1N0NJUDR2dVMwc2dBbktIOGIy
            Ny9obSs0ZmZ0TUNpWGpyLzBZNHZrd0kKLS0tIGZrcXlBQndNaDZVUUc2eUU4N0tH
            dGxCckI3bm1xc3RwUEVBbDlvY0RoeHMK7t/FV8HAEG5gNIKHGgtMMvtqvyINM6dT
            eUe9kyT6Fap6iC1UvWvoxjjtAd6pYvG+gB6oHlfpa0Ppg5uYA+RQgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:10:14Z"
    mac: ENC[AES256_GCM,data:qJa7BfS/n1Hkpwsbd10M3D1iBPNCc/VxtYuBRQz2wM2tRmDnYxNAxUFhHwHqzGnM1lhnuuW2zyT1QyBv2OaWlcWXLPoo8e2XLyakuSn323mT5sMMx7zWWxjYYVW/cCVtkIHJP1/RdbpKOwLW1TQIXok+jecp+2+7fyAPWP12E00=,iv:CgjSqueRTSfPNN5fTd7zD78WSe29hYi99UfgFz8/wBQ=,tag:4QZ5DuZwSYdENJH3SIrLEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
