apiVersion: v1
kind: Secret
metadata:
    name: vw-secret
stringData:
    admin-token: ENC[AES256_GCM,data:M2GtuGzYcTACbNF9d6DRxj2smwWAPjFoDdZeqt3KlfuL31nXQPPhmA==,iv:c7aV886cX9TI3ZtFo9w+/Qj/IEkFSMIEjqPKWBsh65M=,tag:Coi4RRIgX08Ofd7oHkOivg==,type:str]
    smtp-password: ENC[AES256_GCM,data:I2ddTqmpilOgTpri+1yKBT9ztQ==,iv:TGUqcVPlHqsoTLtwBjwV9JW7DBf7V3Ol6CgmLA42O/o=,tag:q+YJvqK5NbWCVw57/IpgRQ==,type:str]
    smtp-user: ENC[AES256_GCM,data:B2ubM4uiIV5h7wojbewU44W/,iv:yCE9tXpT6nJBMUVwg1CzxOGm0MjZW4mmwIgNn8LBrxw=,tag:jHo7TiYsZYVwRSd3sPVhpw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldFVXcVB4bHI1eGsvVmpG
            TWVFa0FkZkFRbEdpdFd6ank1YnNQZzN6K1NRCi9PZWJkeHJWRDJ5alYxejNBS3kv
            Y2NyQ0tQOVIxbER5NTdWL1dKMnlPTmMKLS0tIDNXYU5qS3BWRUd4YjFVa0ptb3R3
            M0cycVZ1TGdNckNKMkZqR09rZUN6bzAK5xNbRMvmzQfxFLZRHu4rJoP+nHmSVXZn
            Kik7kG+tTQxkocHiZEUHYEAZXbnJnvvOKHwIZ+EipyKCHcUEKmUZqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:47:45Z"
    mac: ENC[AES256_GCM,data:b+c5bbggIwYL9VnhXEwVe30U8BNuMuQuA6ABNeMLueu/d49I+FC2Gsenxlh0SLoeWvN+ghTd64fASCSjNkeq3HOa+hJH7c0Qm+zju2Dfejzyh7CE9XWBdnDUMj/y/543zDdRuYjVdzoDpw3WpJNr+AoDjMitrfFNeEQ+ZoBcaIM=,iv:jusAY6d8O9l7Tyoo2R+o4IKUqU+r8lKb6d9Ktg/osoU=,tag:E+INowjrSuFbjzoCC4EOZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
