apiVersion: v1
kind: Secret
metadata:
    name: vw-secret
stringData:
    admin-token: ENC[AES256_GCM,data:laQSyWr5wppGNBf0w+0F4fMIUxK75xWf8Vi/M1C6uTjB5bbRDXgBrg==,iv:PwGiPOz6qzoE5pxW/8nXLkeqfsxoiUiUrz7EBThvCf4=,tag:UyMNFvd5XBPC/Pl5Hbd7ZQ==,type:str]
    smtp-password: ENC[AES256_GCM,data:mDxezkiwbKGpsaeaeV+3Exghcw==,iv:UfGPM6fXrUzhP7F8Nft1fGgxsGDnM6+5s3fCvAUnLkM=,tag:kuMc+XWpvFoqmRZs1W3Eng==,type:str]
    smtp-user: ENC[AES256_GCM,data:YxtWFF70I6MGs2b4/ry4WQKf,iv:nvEdwho1N3VvUQUpyu/z6bYVVVPT81yBIQWwB+ex0Z0=,tag:4FytjSX28fHNPbc+GHHaKw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbWtqeUF2VWo2ZHE5a1JO
            SkZpdkdEaW0zQUxHbXB6aDJUa1BVUjJxaVZrCk11TXVXUDg1S1NZN0pZT2lBMlNL
            UzlUNVhhOTNkb2hGcDZpRmRMTTgwRFUKLS0tIHowT2JKTXhyRzl3VDJ4L3lpb0ta
            S2tDWWJiSjl1czBuVzFVRktnMU13NTQKLKt/1SCBm102KC8pIR1/J3YjCX+Bz6Yd
            SfcnF/SlTYiWY5ZavQuxfa62F6/7G3VZWf16YrZQ3uT7qHhu3Pqd1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:21:23Z"
    mac: ENC[AES256_GCM,data:OIOQJ9Yu/jaqUDaD4HtTXt8XjS6nDLJGwKe8UIlwdgTCKBsaKujLIJNN0z+3RtDRbu0fEItlTAsYFg3LbXHYsW1bMrEPPpAj1zU072p+qIui/7G9NdcPg6DRHvwrms0vKexTJfqdwFKcnshpwcojdbTJmCHBRcl44LPOltymlPg=,iv:yJ06sgAuW1AgJHtbFqcGEFaPEN3FPbcWNPmL2X4Shak=,tag:rap347beuB0tOhPxtyUx8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
