apiVersion: v1
kind: Secret
metadata:
    name: vw-secret
stringData:
    admin-token: ENC[AES256_GCM,data:ZW65eu6436bEWsMqIf6oCPiOVeWAQgIHPYtQBz4OLJVuGV9dGwq9GhlON8EIPf5lYOylu3SNwOSW6BPKGo8qBcvJ5ZKny55Xyc+3up4j7DJKplnp+6fugTcfAYeWc7ocA2gHpmWa95JNwcG02WTHztTul8STwg==,iv:B2tBSqGeA96Rz6RHZKuKLTkdkC+9qOwaPi8cfK2BMP4=,tag:FYG4s+oIc/dtTZw0WXuAyA==,type:str]
    smtp-password: ENC[AES256_GCM,data:RhC5hMBvQlmnThAAgmmLjLt0Wg==,iv:9nwXdM/5NhyWvBjanTQanwX646CIC/ik1Q2Jt8CLIJM=,tag:JVIqHC76nG5fd7hErO5mQA==,type:str]
    smtp-user: ENC[AES256_GCM,data:5cNPJkIe0vzxeDolScizB7qf,iv:8r071FzfWyw8ZvUvxDL1EzSKVU/Uw0ZBJ1O8tH4z5JA=,tag:x7rMN5pmXlUR9zWSwfpakw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTEsxNnJ1R1pQVFkyN0hh
            eXJ4TmRlVlIvdlB0S3VkYzJQcERmNEVpTlFVCkdIVGJleGY2WkZvamFEb1pEZFgy
            czB0TncvUzNSd3VzdzRjNFJ6OXFQRXMKLS0tIHo1dnFldjUybmpzQlRWYVd0MUJU
            Njl3WGV2ZXVMODZSeGhvTnNhdFltUHcKHY9G8VzTOdpakz5G1LATwR9+lrnT+Pqn
            0Q9ugEpLP5CcOy5Z7rEUzPXKIn6BY33+eEA/cSHZS6WUzDn7NT0j1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:26:14Z"
    mac: ENC[AES256_GCM,data:agFJx9V4LIZCckyYgI7puYLbKoUniGWG8lnipHvJomMy69HmMCsdiJ4G+he5L2D165EZWUhzCAjtnPGA/gJ3GlpcHNARGJ4DLe8Fnua29AuoG0/hen8OreAUCcsOa3VOHpibfa0LnPitdmyCWEXyZnU1hLLc1tG+iR7G/rEO5YQ=,iv:f3b6DNq+MrK5WKTD1q3vXF7uPzuopr29NPvwAZA1sME=,tag:bd0stuexuw/LrXts9YHH+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
