kind: PersistentVolume
metadata:
  name: data-vaultwarden-0
  namespace: vaultwarden
spec:
  storageClassName: gsks0
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.10.110
    path: /mnt/storage1/home_nfs/nginx/www/gs-farm`
