kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vaultwarden
  annotations:
    volume.beta.kubernetes.io/storage-class: "gsks1"
spec:
  storageClassName: gsks1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: data-vaultwarden-0
#  annotations:
#    volume.beta.kubernetes.io/storage-class: "gsks1"
#spec:
#  storageClassName: gsks1
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 1Gi
