kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vaultwarden-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "gsks1"
spec:
  storageClassName: gsks1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
apiVersion: v1
---
kind: PersistentVolume
metadata:
  name: data-vaultwarden-0
  namespace: default
spec:
  storageClassName: gsks0
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.10.110
    path: /mnt/storage1/home_nfs/nginx/www/gs-farm`
