apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:hp2aRvwCSYJNnlC1bJCea7VWl2wuQQ2WkXeR7ixFimI6fSqFB2phpg==,iv:8+APKL4x0+NZ7KsOfZN73pmv5WoARRvgQloAGQrNxTs=,tag:AkuFZ/qwLnGxJjg4DmXo7g==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bWJmT0swV1lFZXgvR1F1
            L3FHUXRxTFNMZ1RaSnAwdXErZUxSOGJMYUFvCk9kR2pDdjdXbGZjQ0ZhTVFETVMz
            SElXbnVsVm8ybXpZUXYyM3FzRS9IR0EKLS0tIG01RFo2STM5c0YvNWZWbTNZRXRz
            ZFoxM3pORGZKeEF3bFE5VUlkL3lQZG8KLMIhLUU4ZlN9LSXW082J/x71eG0eXiHS
            uLAEpAv7ka6pCM0GzSkByQkTahVMEWercdMg8q/U+w4yZj7VZ8Sdog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T02:47:23Z"
    mac: ENC[AES256_GCM,data:UP0hu151p+C+5UkMTmd/bn6h1wVP5ronY4bOUQsoXYN+TyEtxsDeEREdBPuy52QEtDYpj90Rs2+ACzLhcCy324DVgFaoKPYNx9yZy2UauZ45IdQz+lYsThZ/fuxJYyy//19/7pFkX6opO0Zh4Oi/R2gQYnscP+sR0SdEbrk+/Xs=,iv:rCpctg00oSYg9N4UAyA314r2aEpiaPMkDlPinCe8meo=,tag:aJZmPHSGqflskETqUIBHCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
