apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:AEQ0PYLc8nHkM1xS3AfVZBajW8oZhLzJBVfr6Odv2nHGkVx2XxZd0w==,iv:Guc+CNT803s9+upHIjakIAUvZpDTr52V8MDpAotZC4g=,tag:9+2uFl+8WgpjqoXQ034lCA==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOGMxVC9nTjdRdmtySkR1
            MEZKNDAzK1h6KzU2c0N1empqekl4dEFBK25rClNCRzRtQjByU25oZWV3VXlvNmpC
            MWFnOGlicElBeGo2R3Q4Q1VWbnVLMjgKLS0tIHNYc3M3aGwvOXBPUHNoeU5QNk4y
            S2hkVHlwa1FmN2pHZGZRbEZUcWtFcVEKq8+cwP9qVxksHMQeBdBaOevjVgu8ms8e
            ZFGtgV6UC8T8Ga698jyg9RJnJTGFZoshi8UTxlk2ZTGr7vyYc0cBLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:25:41Z"
    mac: ENC[AES256_GCM,data:Anf1O2oGz5A/jxN1f/P9G30R/tnrhaPyQ/xqv4NCrD1fmq+5uy3QlUy6rudIVIv0kDmjPDjBBaBvuCSSQ+HNWbwMsh75BTfd0CT7sqJrVjDIat4EY5+etOD+6MDQry0Fa5zQs6ToTW9fancatmjFk41TRL1S+Dfm8iFDskjCVFY=,iv:uBuSeSukssqruZLC1igwjKM1fSkJMjyJfG+Z6uu1+Hg=,tag:g7D1HA8C7gkHs/pYq/focQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
