apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:xFtM/NQZ2txNBC+ECNb1Ju3GJNAut9lpqXJE1h1o9+N6f6BMF1eSTQ==,iv:NT/mBZBwBwU41yuoMQl84npOV7GmZuieDbXkxICZLWQ=,tag:EaohaQWBBnswVf6VVmtZXw==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQzVORnZ6YlZzQ0dRZTFp
            SG0waEtqL0x0cFRPKzNteGprSmFmOG5HVFM0CjhEcjZ2UzhGYm5XMmxaTEdrTVpS
            WW5QUStDTDRCRW1Va2hCSlY1ZUZuaVEKLS0tIG5RazN3RER2SHpzODRIbE5EUkwy
            OXdROE5iR2VFOGRRQzk2RHhQckhKdmMKpTrkSyA2sBl/SsrsElZJ744YH0cMl7bT
            EJzKoQYWO0kQKBHG6rmte31beeDnBCxhxCsLDLqd6Qa1HqY57PHG1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T18:17:56Z"
    mac: ENC[AES256_GCM,data:FFfXYj7QqU9bbW0Z5Nzle8RaTaAn2CPSNSskQHdpx1Jl5H7V/2pGKnk/gbZEtmSCu0ORBXLWDv9aOpho9hX/n2hTGyGiN3qDkLIXNUfg56tLX3T0xSqefCe+bRidar17GSB4qShMxDyDfPUZX5cK0fdmvbUSOsYoZ2XdYzWOxO4=,iv:FKf7jfby8lEh20WWo/kHFZEQU+83VV1Pac5bE25xWsM=,tag:KOuhc6VLv1JAbaph6RXD8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
