apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:NblkWX9aDD2HeYZ8ftob7qllW2s702hb14BRMfBird0xoiCCd95q3g==,iv:x7b6+ATXJI605XXgxM+Uos+cMR5EtrOOe6Mr+Bmchok=,tag:Rlb4gACWMjJYBtor0MjPIQ==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQmphcFJRSi9GVEdpTW03
            bUJGWjJGQU1kV29SRHRHek9TR3ZxL3Z6N1V3Ck5FdVgxMFZWVjg0a0l0azArZm5V
            c09Ja0FUV0tvZTJTdm8wcWIvL3orRm8KLS0tIE83MWhlU2hIMlNKRWVtcFNvT0lJ
            QnRpUzFTcHltbTU2WXpZc01oU2hoWWsKQWV99+3/m0gbBpM6lnvBmZDt7FE/rKJm
            fI8MEUiE+6hM/gKZ6WhD03T/yX7YXZTPveDajLNwh4bCChwPBl/t2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:21:00Z"
    mac: ENC[AES256_GCM,data:q6KzqW8e2fRUy6yPMl3Tr+UM4DDjBrBQZeT7LdRu/RE3eRwJPr7b3jVRUEwUTge8SDRFDvbBFwB0kGBsGZubP7FDBYFixRDC8oR5RIvmICRkDmqWnvUaWCUyCkkD8FhGT1//PP1zxYhKmbj7YZGR6dpVBj3B2mCRcxqHzk8vohE=,iv:05o6matVcrvnfGVqONy+E+9xmaXu0MNRif8ziS/5y+E=,tag:IojC/LMhkCc4wfCWWP271Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
