apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:/D32bcu40dGo0hSee01lmZLF9T2OCiBJor3idHR6Yvk4Sk6GjRYsMw==,iv:rdbnew0wsgDIl2FaQCSMEVLjrsQrAB6wmdEchDy+bV4=,tag:Bl/1Rn9YHLgPMPGc4vfZ0w==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YVRxZHFQaXp1eWc0dGJF
            SGZYcThyVTl5bUlQR2xuWHViVURMZDhuVDBBClZ1OWp5MWhoRERuZy9wTTEzUnBX
            aW5PV1p3aG1qQ0VCVy81T3hSZ0FVb0EKLS0tIFhSYzZiWndTYVJ2TUpQR0hxUkN4
            eEdLcjY0RmNQMUYwOXRYRUlsQWMyVFUKe8lEAnGtty951xeZe6u9CSjbKIf8WcZT
            5X/MUcMum1CZced+Vqmye1jb4/KmJZF+d7kFG4R+WpVpDro4Sg2tyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T02:04:13Z"
    mac: ENC[AES256_GCM,data:zCzgQOq2Sr0g1xfkn56MNHTyL5r2NJn9X28rn4GhRwjQO3m28h/ydKKIHBsaZyZEEb2Qxnqw9R/UUkrtieTyz8j+i82v+WyrOodwnlVg4ZcaQ7uN1EYIrFUcqK71y//nQ+bGec1zrmnsukik9Gw2lBOz2H1C9xZlgbF1000YAy8=,iv:UvkhyJ5mIai4dYGnbSO8CvoC/6xYmzn6ehKbfwl3KIk=,tag:UZvjGy+RvHUFawviPHRDCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
