apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:yyDlTgGgHcV+dn6/fSKX/MgbWiuqg1CsPCKE9Web1Um3/ocB6FxFoA==,iv:fbNij9+7BscSrIKnKQ8hJNrFnqA+6YfXIxg0pcYm5io=,tag:5mj59+ju6McgOrzp4+OJEg==,type:str]
sops:
    age:
        - recipient: age1puse8jhtwqw87w9qr9j4g8dajqccn0899vpyc0wnn9y2e6wz0cms2g895x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1b1pyMzZKaGJxRzFTbStG
            VWxlMzdpaTg2VXFLVGxyOXo3QzJZd1JDR0hrCkE2Sk9yazFyUFZ4K0psaU9zMzhO
            V0JEa3psY3NJcWorUHVHUXRNNjhZUzgKLS0tIDVQRnhISmNjSHhNSEYzUHAvWEow
            dkUvV2l3dmNGWGNpWXROTDVBMXUvSzgK2dwjB46VSp6koBOpCeYVPrWcHa5uCSBm
            jH8YxMvRDdNaJUja3HtsW6pWkVkP+ClrUWbg4bmvLfKaxyzrUCYGoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T03:09:52Z"
    mac: ENC[AES256_GCM,data:lZZqhzrrECdC4ooiClCGSceQgKO2Z6Je4VX2VWLifgOwe8JmLle239AbIlANrxgZ+X2YyoRL+deRhNtxC0EVs6hGYYuEDvbHYJGrST+/7UUwuDWWttegYvgy3PGs3DPMWiC0m8QQlKx+Jguyg3ubd9t4YOHhYjVhR3Oe817n8OQ=,iv:NkVNm6yUFEbbWuG5+4h5O43eMZL9MmBKzkQueUP992k=,tag:vtugFMNX6QlRlPajULPbhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
